### ISSUE TITLE
Charts are blank with new implementation of Opengl NEWT

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama.old#3238]
**Describe the bug**
Charts are blank with new implementation of Opengl NEWT
**To Reproduce**
1. 
Launch Tutorials\Incremental Model\models\Incremental Model 6.gaml
2. The chart is blank (gray because i use dark theme)
 ![image](https://user-images.githubusercontent.com/6105384/137138210-cdef6c3e-d0c6-4992-83b4-15d56be16f08.png)

Tested with `-Duse_native_opengl_window=true` and it produce the same issue.
There is no exception in eclipse console.

**Desktop (please complete the following information):**
 - OS: Win 11
  - GAMA version: git
 - Java version: 15.0.2
 - Graphics cards / Display system: Nvidia

**Comment by AlexisDrogoul** [comment]
@hqnghi88 not sure I understand. You mean you have blank Java2D displays *with* and *without* the `-Duse_native_opengl_window=true argument`, but only if you mix with OpenGL displays ? Is that correct ? Or do you have issues also *without* OpenGL displays ?

**Comment by AlexisDrogoul** [comment]
Should be fixed now. Please reopen if not !
