### ISSUE TITLE
Windows: Unable to select a Java2D display hidden behind an OpenGL display. 

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama.old#3325]
**Describe the bug**
If a Java2D display is hidden behind a OpenGL display when opening an experiment, it is impossible to promote it to the front. It it briefly  visible and then immediately goes back behind the OpenGL display. 

However, when it has been "shown" once (for instance by moving the OpenGL display aside), its behaviour is normal again when it is behind. See the video to understand: 

![screencast 2022-03-14 22-45-04](https://user-images.githubusercontent.com/579256/158209456-d8aadb58-1a93-4fe9-89d4-7f9ac12cf39d.gif)

**Expected behavior**
That the behaviour is what would be expected (ie. the Java2D display comes to the front when its tab is selected).

**Desktop (please complete the following information):**
 - OS: Windows 11
 - PC Model: Parallels VM running on macOS BigSur
 - GAMA version: 1.8.2 git
 - Java version: JDK 17

**Comment by hqnghi88** [comment]
It works on my machine (hope it 's fast enough).
