### ISSUE TITLE
No info on system's memory through gama.max_memory 

### ISSUE THREAD

**Issue by DAM-Philippon** [gama-platform/gama.old#3360]
**Describe the bug**
Hi everyone, 
Facing a bug with the value of max_memory provided by the agent gama while doing some benchmark (equals to 0 byte). Not facing any memory problem while running a model though.

**To Reproduce**
1. Go to Library\GAML Syntax\System\System.gaml
2. Run the experiment
3. See that the gama.max_memory is equal to 0 byte (hence gama.free_memory is negative)

**Expected behavior**
I should be able to obtain the max memory and a correct value for free_memory. 

**Screenshots**
<img width="411" alt="image" src="https://user-images.githubusercontent.com/61393694/165493678-dccb5980-b61d-4331-b829-de9dad45262f.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.2.1
 - PC Model: Macbook Pro 2017
 - GAMA version: GAMA_1.8.2_MacOS_with_JDK_03.23.22_00531c7f
 - Java version: JDK provided with GAMA, version on Macbook: "17.0.2" 2022-01-18 LTS
 - Graphics cards / Display system: Intel Iris Plus Graphics 640 1536 MB

**Comment by hqnghi88** [comment]
There was a casting from long to int , i dont know why as all the computed value are long , so why we need to return int at last??
<img width="255" alt="image" src="https://user-images.githubusercontent.com/6105384/165554119-fc3687d9-933c-45a6-9c76-62c89c34e5c5.png">
Anyway, i change all to long.
( Btw, you have the same name with my dear-long-time-no-see friend )

**Comment by LucasGrjs** [comment]
Just tested that and its working : 

```
gama.version -: '1.8.2.202204290307'
gama.free_memory -: 3624522240 bytes
gama.max_memory -: 4294967296 bytes
```
