### ISSUE TITLE
Recover model tabs after Gama crashes

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama.old#3363]
When Gama crashes, it cleans the corrupted workspace after restart. However, model tabs are lost. Since I usually have many tabs opened at the same time, it is quite annoying to reopen them one by one (and sadly gama often crashes with me). Is it possible to save somehow the open tabs and reopen them after cleaning ?

This is what I get after crash, restart and cleaning:
![image](https://user-images.githubusercontent.com/18676913/166666241-1986e055-a3e3-456a-8453-b876f3280beb.png)

This is what I would like to get:
![image](https://user-images.githubusercontent.com/18676913/166666364-2e570237-2d02-4499-a032-b7b3acbf24a5.png)

Gama version: 1.8.1
OS: Win 10

**Comment by AlexisDrogoul** [comment]
The principle of "cleaning the workspace" precisely removes all the metadata that can be corrupted, which contains the one keeping track of the open tabs, selected files, etc... It is the same in Eclipse. Sorry !
