### ISSUE TITLE
add the possibility to multiply/divide lists element by element

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama.old#3364]
list<float> list2 <- list1 * 0.3 should return a list which elements are the elements of list1 multiplied by 0.3

This already works with matrices.

**Comment by benoitgaudou** [comment]
The reason why  it does not exist is because + and - have not the classical arithmetic meaning on list, but it used to add / remove elements from a list: 
```
l -: [1,2,3]
l + 4 -: [1,2,3,4]
l - 2 -: [1,3]
```
Whereas on matrix, + : - is used in the arithmetic meaning:
```
m -: matrix<int>([[1,2,3],[1,2,3]])
m + 2 -: matrix<int>([[3,4,5],[3,4,5]])
```

**Comment by AlexisDrogoul** [comment]
Just for the record, the workaround is of course to use collect so that `list2 <- list1 * 0.3` becomes: 

```
list2 <- list1 collect (each * 0.3);
```
