### ISSUE TITLE
Minimum duration slider wrong color in fullscreen

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama.old#3365]
**Describe the bug**
Run any model with a toolbar , press esc to put it in full screen

**Expected behavior**
The minimum duration slider color should be the same as the rest of the toolbar

**Screenshots**
<img width="1440" alt="Screenshot 2022-05-04 at 21 50 09" src="https://user-images.githubusercontent.com/3928502/166707993-b2ed1d83-862c-4a8d-bbaa-4abf636a40d2.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Git version

**Comment by AlexisDrogoul** [comment]
Please describe the combination of dark / light modes in the OS + GAMA, as well as whether it is obtained when running from Eclipse or from the release.

**Comment by agrignard** [comment]
This is what I have with the last release (GAMA_1.8.2_MacOS_with_JDK_05.05.22_6f6d34dd) and from Eclipse when my OS is in Dark Mode

Dark Mode (following os theme)
<img width="1440" alt="Screenshot 2022-05-06 at 10 55 34" src="https://user-images.githubusercontent.com/3928502/167064562-3f4e570b-7b06-4c78-b1ad-c9c72693aeb3.png">


Light mode (os is in dark)
<img width="1440" alt="Screenshot 2022-05-06 at 10 57 45" src="https://user-images.githubusercontent.com/3928502/167064585-3ada1e19-6d8b-4792-9a8d-00d3fd30695f.png">
