### ISSUE TITLE
Windows headless wrapper is outdated

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama.old#3367]
**Describe the bug**
A _lot_ of development has been made on `gama-headless.sh` (for Linux and MacOS systems), but the `gama-headless.bat` has been a bit abandoned (by my lack of knowledge). This may leave some troubles using GAMA Headless on Windows systems.

**Expected behavior**
Update `gama-headless.bat` to be more coherent with other system's wrapper.

**Comment by LucasGrjs** [comment]
Fixed the batch script to make it work again on Windows (must be run with the cmd as administrator in order to create the output directory and the log file if they are not already created)
