### ISSUE TITLE
Unification of the method to get file from URL (and json handler)

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama.old#3375]
**Describe the bug**
Unification of the url/json handler. 

This issue needs to be improved here are some note (with certainly some wrong naming and concept, don't hesitate to modify this post)

The concept is to compare what is done in  ```GamaFile (Webb)``` VS what is done in ```Network/Websocket```

 - Currently: In file we remove all the library and we call http request to get the file (using webb)
 - Trying to unify the 2 method 

For json file we have a serialize/deserializer.

**Expected behavior**
Only one method both for file and for network

**Comment by agrignard** [comment]
As far as I remember this one was not really an issue but more a design note for future development to unify the way to get an URL. 

Should we keep it as an opened issue ?

**Comment by hqnghi88** [comment]
One point was that i used a different jsoner at that time, but it is fixed and unioned with the Jsoner (it should be webb or not?) and shapeSaver so i close this, feel free to reopen or even new one for "union"
