### ISSUE TITLE
Can't limit number of cores used in Batch Headless

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama.old#3376]
**Describe the bug**
The `-hpc` flag in headless batch to limit number of cores used (like in classical headless) isn't read by GAMA

**To Reproduce**
1. Launch a headless batch command like `$ bash gama-headless.sh -hpc 1 -batch Optimization ./Tutorials/Predator\ Prey/models/Model 13.gaml`
2. See max cores used anyway

**Expected behavior**
From the example, limiting number of batch simulation to 1 core

**Desktop (please complete the following information):**
 - OS: Linux
 - GAMA version: git
 - Java version: 17

**Comment by hqnghi88** [comment]
in fact, i cannot launch headless (both eclipse and release) for this model to test. I wonder if it is the model or headless problem itself?
