### ISSUE TITLE
Side Control refactoring

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama.old#3378]
**Describe the bug**
<img width="250" alt="displays_opengl_sidebar" src="https://user-images.githubusercontent.com/3928502/167196827-bf6bd745-1a72-46b6-8987-703e3f165273.png">

Remove most of it to simplify the GUI

1. Keep Keystone as a clipboard
2. Move the camera copy facet in the toolbar
3. Move the layer display control to the top toolbar with aspect, transparency, visibility

**Comment by AlexisDrogoul** [comment]
Done in the latest commit (I forgot to mention it): https://github.com/gama-platform/gama/commit/cdb2394ebe7f1f58de71f5c5dc3dc80622d745b3
