### ISSUE TITLE
Horizontal scrollbar hides last item in the models navigation view in ubuntu

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3379]
**Describe the bug**
On my laptop when I hover over the horizontal scrollbar, it appears over the content of the model navigation view and hides the last item even if I scroll vertically to the maximum. It can be annoying especially if you try to scroll horizontally just to read something in particular in the name of a file/directory.
![image](https://user-images.githubusercontent.com/6374469/167238575-c254bf24-1fa2-4e20-992e-45252dd9ae3e.png)

**Expected behavior**
The scrollbar and the content of the view do not overlap

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 
**Additional context**
Adding some margin at the bottom of the view would solve the problem

**Comment by AlexisDrogoul** [comment]
Workaround and comments here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=519728

Nothing we can really do in GAMA AFAIK for the moment...
