### ISSUE TITLE
Cannot run flood simulation experiment in Headless mode

### ISSUE THREAD

**Issue by DAVIEPHAM** [gama-platform/gama.old#3380]
**Describe the bug**

I couldn't run Flood simulation in headless experiments, many times I set finalStep > 150, it doesn't work, but < 120 is fine. Sometime I get the same problem in user interface.
**Screenshots**
![image](https://user-images.githubusercontent.com/83625165/167247626-8f308262-0e1d-4ea7-94ba-99b108ff6ac4.png)

**Desktop (please complete the following information):**
 - OS: [Win10]

[bug_log.txt](https://github.com/gama-platform/gama/files/8644811/bug_log.txt)
[Flood_Simulation.txt](https://github.com/gama-platform/gama/files/8644812/Flood_Simulation.txt)

**Comment by hqnghi88** [comment]
Hi,
Can you post the xml used for that headless running?

**Comment by ptaillandier** [comment]
It is due to the use of the parallel facet in some "ask". The use of this facet can lead to some error with the MersenneTwister random generator. I removed the parallel facet from the model. It should work now.

**Comment by DAVIEPHAM** [comment]
> It is due to the use of the parallel facet in some "ask". The use of this facet can lead to some error with the MersenneTwister random generator. I removed the parallel facet from the model. It should work now.

It works now. Merci beaucoup à vous !!!
