### ISSUE TITLE
Problem with the access to the doc from GAMA for some plugins

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama.old#3385]
**Describe the bug**
Sometimes, I cannot access to the documentation of some operators/attributes/skills 

**To Reproduce**
Very random....
 in the interactive console: ?acc_bias, then ?lane_change_cooldown, then searching the same skill attribute in the gaml reference search engine of GAMA.... after some times, the documentation of the attribute is not accessible (not yet documented).

**Desktop (please complete the following information):**
 - OS: windows 10
 - GAMA version: git
 - Slow computer

**Comment by AlexisDrogoul** [comment]
I think I've found the culprit (compilation of models using this variable). Commit on the way.
