### ISSUE TITLE
Testing all models packaged with gama

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3390]
**Describe the bug**
For every gaml model package with gama we must make sure that:

- It has no warning
- It compiles
- It runs without crashing
- It does what it's supposed to do

List of every model to test:

- [x] Physics Engine/models/Testing Steps.gaml
- [x] Physics Engine/models/Perfect Gas Chamber.gaml
- [x] Physics Engine/models/Eroding Vulcano.gaml
- [x] Physics Engine/models/Testing Restitution.gaml
- [x] Physics Engine/models/Stairs.gaml
- [x] Physics Engine/models/Hello World.gaml
- [x] Physics Engine/models/Tricky Fountain.gaml
- [x] Physics Engine/models/Flow on Terrain.gaml
- [x] Physics Engine/models/Play Pool.gaml
- [x] Serialization/models/test/Test - Create Simu From File - Graph.gaml
- [x] Serialization/models/test/Test - Create Simu From File - Container types.gaml
- [x] Serialization/models/test/Test - Memorize Experiment - Topology - Grid.gaml
- [x] Serialization/models/test/Test - Memorize Experiment - keep_seed.gaml
- [x] Serialization/models/test/Test - Create Simu from File - Topology - Grid.gaml
- [x] Serialization/models/test/Test - Create Simu From File - Crossreference in agents.gaml
- [x] Serialization/models/test/Test - Memorize Experiment - Topology - Graph.gaml
- [x] Serialization/models/Serialize Operators - Save simulation in file.gaml
- [x] Serialization/models/Serialize Operators - Serialize simulation.gaml
- [x] Serialization/models/Create Simulation From File.gaml
- [x] Serialization/models/Serialize Operators - Restore simulation.gaml
- [x] Serialization/models/Memorize Experiment.gaml
- [x] Driving Skill/models/Simple model/Simple Traffic Model.gaml
- [x] Driving Skill/models/Advanced models/Traffic.gaml
- [x] Driving Skill/models/Advanced models/Simple Intersection.gaml
- [x] Driving Skill/models/Advanced models/Following Paths.gaml
- [x] Driving Skill/models/Advanced models/Drive Random.gaml
- [x] Driving Skill/models/Utilities/OSM Loading Driving.gaml
- [x] Databases/Regular Database/Create and insert Agents from and in DB with MySQL.gaml
- [x] Databases/Regular Database/Simple Agents tests in MySQL.gaml
- [x] Databases/Regular Database/Simple SQLSKILL tests in SQLite.gaml
- [x] Databases/Regular Database/Simple AgentDB tests in MySQL.gaml
- [x] Databases/Regular Database/Connection Test.gaml
- [x] Databases/Spatial Database/Create Spatial Table in PostGIS.gaml
- [x] Databases/Spatial Database/Create Spatial Table in MySQL.gaml
- [x] Databases/Spatial Database/Agents from Database in MSSQL.gaml
- [x] Databases/Spatial Database/Agents from Database in PostGIS.gaml
- [x] Databases/Spatial Database/Agents to Database in MySQL.gaml
- [x] Databases/Spatial Database/Agents to Database in PostGIS.gaml
- [x] Databases/Spatial Database/Agents from Database in MySQL.gaml
- [x] Databases/Spatial Database/Agents to Database in PostGIS3D.gaml
- [x] Databases/Spatial Database/Create Spatial Table in MSSQL.gaml
- [x] Databases/Spatial Database/Agents to Database in MSSQL.gaml
- [x] Databases/Spatial Database/Agents to Database in PostGIS2D.gaml
- [ ] Databases/Spatial Database/Agents from Database in SQLite.gaml
- [x] Databases/Spatial Database/Create Spatial Table in SQLite.gaml
- [ ] Databases/Spatial Database/Agents from Database in SQLite_QGis.gaml
- [x] Databases/Spatial Database/Agents to Database in SQLite.gaml
- [x] Network/3 Advanced features/1 Pong Teleportation (send agent).gaml
- [ ] Network/2 Available protocols/Arduino/Arduino Listener.gaml
- [x] Network/2 Available protocols/MQTT protocol/Example_MQTT_Send_Agent.gaml
- [x] Network/2 Available protocols/MQTT protocol/Example_MQTT_Receive_Agent.gaml
- [x] Network/2 Available protocols/MQTT protocol/Example_MQTT_Send.gaml
- [x] Network/2 Available protocols/MQTT protocol/Example_MQTT_Receive.gaml
- [x] Network/2 Available protocols/TCP protocol/TCP Server And Client Example .gaml
- [x] Network/2 Available protocols/TCP protocol/TCP Teleportation.gaml
- [x] Network/2 Available protocols/WebSocket protocol/WebSocket Server And Client Example .gaml
- [x] Network/2 Available protocols/UDP protocol/UDP Listener Mouse from Processing For camera.gaml
- [x] Network/2 Available protocols/UDP protocol/UDP Emitter Example.gaml
- [x] Network/2 Available protocols/UDP protocol/UDP Listener Mouse from Processing.gaml
- [x] Network/2 Available protocols/HTTP Request/HTTP GET.gaml
- [x] Network/2 Available protocols/HTTP Request/HTTP POST.gaml
- [x] Network/1 Get started/1 Simple ping-pong.gaml
- [x] Network/1 Get started/3 Broadcast to group.gaml
- [x] Network/1 Get started/2 Broadcast to all.gaml
- [x] Model Exploration/Experiment species/Experiment and simulation.gaml
- [x] Model Exploration/Multi-simulation/Multi-simulation.gaml
- [x] Model Exploration/Batch Simulation/Batch.gaml
- [x] Toy Models/Soccer/models/Team2 Strategy.gaml
- [x] Toy Models/Soccer/models/Soccer Experiments.gaml
- [x] Toy Models/Soccer/models/Soccer Base.gaml
- [x] Toy Models/Soccer/models/Team1 Strategy.gaml
- [x] Toy Models/Soccer/models/Soccer.gaml
- [x] Toy Models/Evacuation/models/City Escape.gaml
- [x] Toy Models/Evacuation/models/Goto on Grid.gaml
- [x] Toy Models/Evacuation/models/Move on Grid.gaml
- [x] Toy Models/Evacuation/models/Continuous Move.gaml
- [x] Toy Models/Multi-level Data Analysis/includes/Common Bug Species.gaml
- [x] Toy Models/Multi-level Data Analysis/models/Graph From Bug (Mirror Graph).gaml
- [x] Toy Models/Multi-level Data Analysis/models/Graph From Bug (Distance Graph).gaml
- [x] Toy Models/Multi-level Data Analysis/models/MODAVI.gaml
- [x] Toy Models/Predator Prey/Lotka-Volterra (Influence of Integration Step).gaml
- [x] Toy Models/Predator Prey/Lotka-Volterra (Simple).gaml
- [x] Toy Models/Vote/Vote.gaml
- [x] Toy Models/Learning/models/Mas KMeans Interactive.gaml
- [x] Toy Models/Learning/models/Mas KMeans.gaml
- [x] Toy Models/Art/L-Trees/models/Tree and Seasons.gaml
- [x] Toy Models/Art/Gama 1.8/models/GAMA 1.8.gaml
- [x] Toy Models/Art/Mondrian City/models/Mondrian City.gaml
- [x] Toy Models/Art/Mondrian City/models/Mondrian Generator.gaml
- [x] Toy Models/Art/Radiohead In Point Cloud/models/Radiohead In Point Coud.gaml
- [x] Toy Models/Art/Voronoi/Voronoi.gaml
- [x] Toy Models/Boids/models/Boids 3D Analysis.gaml
- [x] Toy Models/Boids/models/Boids.gaml
- [x] Toy Models/Boids/models/Boids With Flocks.gaml
- [x] Toy Models/Boids/models/Boids 3D Motion.gaml
- [x] Toy Models/Segregation (Schelling)/models/Segregation (GIS).gaml
- [x] Toy Models/Segregation (Schelling)/models/Segregation (Google Map).gaml
- [x] Toy Models/Segregation (Schelling)/models/Segregation (Cellular Automata).gaml
- [x] Toy Models/Segregation (Schelling)/models/Segregation (Agents).gaml
- [x] Toy Models/Segregation (Schelling)/include/Common Schelling Segregation.gaml
- [x] Toy Models/Urban Growth/models/Raster Urban Growth.gaml
- [x] Toy Models/Life/Life.gaml
- [x] Toy Models/Bubble Sort/models/Bubble Sort 3D.gaml
- [x] Toy Models/Ants (Foraging and Sorting)/models/Ant Sorting.gaml
- [x] Toy Models/Ants (Foraging and Sorting)/models/Ant Foraging.gaml
- [x] Toy Models/Epidemiology/models/Susceptible Infected (SI).gaml
- [x] Toy Models/Epidemiology/models/SIR (Split in Agents).gaml
- [x] Toy Models/Epidemiology/models/Susceptible Infected Recovered (SIR).gaml
- [x] Toy Models/Epidemiology/models/SIR (Switch).gaml
- [x] Toy Models/Circle/Circle.gaml
- [x] Toy Models/Flood Simulation/models/Hydrological Model.gaml
- [x] Toy Models/Waterflow/models/Waterflow Watershed.gaml
- [x] Toy Models/Waterflow/models/Waterflow River Graph.gaml
- [x] Toy Models/Waterflow/models/Waterflow Field Elevation.gaml
- [x] Toy Models/Waterflow/models/Waterflow Grid Elevation.gaml
- [x] Toy Models/Waterflow/models/Waterflow Grid Neighborhood.gaml
- [x] Toy Models/Waterflow/models/Waterflow River Water Unit.gaml
- [x] Toy Models/Comodels/Prey Sugarscaptor/Adapters/Predator Prey Adapter.gaml
- [x] Toy Models/Comodels/Prey Sugarscaptor/Adapters/Sugarscape Adapter.gaml
- [x] Toy Models/Comodels/Prey Sugarscaptor/Prey Sugarscaptor Comodel.gaml
- [x] Toy Models/Comodels/Plant Growth and Weather/Plant Growth.gaml
- [x] Toy Models/Comodels/Plant Growth and Weather/Comodel 0.gaml
- [x] Toy Models/Comodels/Plant Growth and Weather/Weather.gaml
- [x] Toy Models/Comodels/Plant Growth and Weather/Comodel 1.gaml
- [x] Toy Models/Comodels/Plant Growth and Weather/Plant Growth Adapter.gaml
- [x] Toy Models/Comodels/Plant Growth and Weather/Comodel 2.gaml
- [x] Toy Models/Comodels/City Boids/City Boids Comodel.gaml
- [x] Toy Models/Comodels/City Boids/Adapters/Procedural City Adapter.gaml
- [x] Toy Models/Comodels/City Boids/Adapters/Boids Adapter.gaml
- [x] Toy Models/Comodels/Flood and Evacuation/Flood Evacuation Comodel.gaml
- [x] Toy Models/Comodels/Flood and Evacuation/Adapters/Flood Adapter.gaml
- [x] Toy Models/Comodels/Flood and Evacuation/Adapters/Evacuation Adapter.gaml
- [x] Toy Models/Comodels/SIR Switch/Legacy_models/SIR_EBM.gaml
- [x] Toy Models/Comodels/SIR Switch/Legacy_models/ABM Adapter.gaml
- [x] Toy Models/Comodels/SIR Switch/Legacy_models/SIR_ABM.gaml
- [x] Toy Models/Comodels/SIR Switch/Legacy_models/EBM Adapter.gaml
- [x] Toy Models/Comodels/SIR Switch/SIR Comodel.gaml
- [x] Toy Models/Comodels/Urban and Traffic/Adapters/Urban Adapter.gaml
- [x] Toy Models/Comodels/Urban and Traffic/Adapters/Traffic Adapter.gaml
- [x] Toy Models/Comodels/Urban and Traffic/Urbanization And Traffic Comodel.gaml
- [x] Toy Models/Comodels/Boids and Voronoi/Voroboids (Boids and Voronoi Comodel).gaml
- [x] Toy Models/Comodels/Boids and Voronoi/Adapters/Boids Adapter.gaml
- [x] Toy Models/Comodels/Boids and Voronoi/Adapters/Voronoi Adapter.gaml
- [x] Toy Models/Traffic/models/LWR Traffic Flow Model.gaml
- [x] Toy Models/Traffic/models/Simple Traffic Model.gaml
- [x] Toy Models/Traffic/models/Netlogo - Traffic model - 1 road.gaml
- [x] Toy Models/Traffic/models/Netlogo - Traffic model - 2 roads.gaml
- [x] Toy Models/Clock/models/Clock.gaml
- [x] Toy Models/Sugarscape/models/Sugarscape.gaml
- [x] Tutorials/Predator Prey/models/Model 05.gaml
- [x] Tutorials/Predator Prey/models/Model 07.gaml
- [x] Tutorials/Predator Prey/models/Model 11.gaml
- [x] Tutorials/Predator Prey/models/Model 09.gaml
- [x] Tutorials/Predator Prey/models/Model 03.gaml
- [x] Tutorials/Predator Prey/models/Model 13.gaml
- [x] Tutorials/Predator Prey/models/Model 04.gaml
- [x] Tutorials/Predator Prey/models/Model 08.gaml
- [x] Tutorials/Predator Prey/models/Model 10.gaml
- [x] Tutorials/Predator Prey/models/Model 02.gaml
- [x] Tutorials/Predator Prey/models/Model 01.gaml
- [x] Tutorials/Predator Prey/models/Model 06.gaml
- [x] Tutorials/Predator Prey/models/Model 12.gaml
- [x] Tutorials/Incremental Model/models/Incremental Model 1.gaml
- [x] Tutorials/Incremental Model/models/Incremental Model 5.gaml
- [x] Tutorials/Incremental Model/models/Incremental Model 2.gaml
- [x] Tutorials/Incremental Model/models/Incremental Model 3.gaml
- [x] Tutorials/Incremental Model/models/Incremental Model 6.gaml
- [x] Tutorials/Incremental Model/models/Incremental Model 7.gaml
- [x] Tutorials/Incremental Model/models/Incremental Model 4.gaml
- [x] Tutorials/Road Traffic/models/Model 05.gaml
- [x] Tutorials/Road Traffic/models/Model 07.gaml
- [x] Tutorials/Road Traffic/models/Model 03.gaml
- [x] Tutorials/Road Traffic/models/Model 04.gaml
- [x] Tutorials/Road Traffic/models/Model 02.gaml
- [x] Tutorials/Road Traffic/models/Model 01.gaml
- [x] Tutorials/Road Traffic/models/Model 06.gaml
- [x] Tutorials/Luneray flu/models/model4.gaml
- [x] Tutorials/Luneray flu/models/model1.gaml
- [x] Tutorials/Luneray flu/models/model2.gaml
- [x] Tutorials/Luneray flu/models/model3.gaml
- [x] Tutorials/Luneray flu/models/model5.gaml
- [x] Tutorials/Luneray flu/models/model6.gaml
- [x] Tutorials/3D/models/Model 03.gaml
- [x] Tutorials/3D/models/Model 02.gaml
- [x] Tutorials/3D/models/Model 01.gaml
- [x] GAML Syntax/Architectures/Rule Based Behaviors.gaml
- [x] GAML Syntax/Conditional Structures/If Then Else.gaml
- [x] GAML Syntax/Conditional Structures/State Transitions.gaml
- [x] GAML Syntax/Conditional Structures/When.gaml
- [x] GAML Syntax/Conditional Structures/Switch And Match.gaml
- [x] GAML Syntax/Unit Test/Basic Example.gaml
- [x] GAML Syntax/Unit Test/Experiment Example.experiment
- [x] GAML Syntax/Unit Test/Two Species (Example).gaml
- [x] GAML Syntax/System/System.gaml
- [x] GAML Syntax/System/Errors.gaml
- [x] GAML Syntax/System/Syntax (1.6).gaml
- [x] GAML Syntax/System/Preferences.gaml
- [x] GAML Syntax/System/Benchmarking.gaml
- [x] GAML Syntax/Loop And Iterations/Ask Agents.gaml
- [x] GAML Syntax/Loop And Iterations/Loop Statement.gaml
- [x] GAML Syntax/Loop And Iterations/Iterators.gaml
- [x] GAML Syntax/Loop And Iterations/Loop Over.gaml
- [x] GAML Syntax/Species Definition/Mirror species - creation and death of agents.gaml
- [x] GAML Syntax/Species Definition/Mirror species.gaml
- [x] GAML Syntax/Species Definition/Inheritance.gaml
- [x] GAML Syntax/Species Definition/Attribute access.gaml
- [x] GAML Syntax/Simulation Initialization/Init Action.gaml
- [x] GAML Syntax/Scheduler/No Scheduler.gaml
- [x] GAML Syntax/Scheduler/Not Executed Random Manager Scheduler.gaml
- [x] GAML Syntax/Scheduler/Random Scheduler.gaml
- [x] GAML Syntax/Scheduler/Default Scheduler.gaml
- [x] GAML Syntax/Scheduler/Species Manager.gaml
- [x] GAML Syntax/Data Types And Structures/Casting.gaml
- [x] GAML Syntax/Data Types And Structures/Graph.gaml
- [x] GAML Syntax/Data Types And Structures/Fields.gaml
- [x] GAML Syntax/Data Types And Structures/Lists.gaml
- [x] GAML Syntax/Data Types And Structures/Maps.gaml
- [x] GAML Syntax/Data Types And Structures/Units And Constants.gaml
- [x] GAML Syntax/Data Types And Structures/Date and Time/Date Type And Real Dates.gaml
- [x] GAML Syntax/Data Types And Structures/Date and Time/Simple Time Definition.gaml
- [x] GAML Syntax/Data Types And Structures/Matrices.gaml
- [x] GAML Syntax/Variables/Notifying Variables.gaml
- [x] GAML Syntax/Variables/Declaration of Parameters.gaml
- [x] Data/Spatial Projection/models/from GAMA CRS.gaml
- [x] Data/Spatial Projection/models/to GAMA CRS.gaml
- [x] Data/Utils/models/ZipUnzip.gaml
- [x] Data/Utils/models/FileUtils.gaml
- [x] Data/Data Cleaning/models/Clean Line Network.gaml
- [x] Data/Download Spatial Data/models/Download Data (OSM-images).gaml
- [x] Data/Data Exportation/models/Save to SHP.gaml
- [x] Data/Data Exportation/models/Save to GeoJson.gaml
- [x] Data/Data Exportation/models/Save to Text.gaml
- [x] Data/Data Exportation/models/Save to ASC.gaml
- [x] Data/Data Exportation/models/Save to Geotiff.gaml
- [x] Data/Data Exportation/models/Save Graphs.gaml
- [x] Data/Data Exportation/models/Save to PNG.gaml
- [x] Data/Data Exportation/models/Save to KML.gaml
- [x] Data/Data Exportation/models/Save to CSV.gaml
- [x] Data/Data Importation/models/JSON File Import.gaml
- [x] Data/Data Importation/models/ASC File Import.gaml
- [x] Data/Data Importation/models/MapQuest Image Import.gaml
- [x] Data/Data Importation/models/CSV Agents.gaml
- [x] Data/Data Importation/models/GMLFILE Import.gaml
- [x] Data/Data Importation/models/OBJ file loading.gaml
- [x] Data/Data Importation/models/Image vectorization.gaml
- [x] Data/Data Importation/models/URL Image Import.gaml
- [x] Data/Data Importation/models/Grid DEM.gaml
- [x] Data/Data Importation/models/CSV File Import.gaml
- [x] Data/Data Importation/models/GIF File Loading.gaml
- [x] Data/Data Importation/models/Multiple Raster Files Import.gaml
- [x] Data/Data Importation/models/OBJ file drawing.gaml
- [x] Data/Data Importation/models/GEOJSON File Import.gaml
- [x] Data/Data Importation/models/GEOTIFF File Import.gaml
- [x] Data/Data Importation/models/Graph Importation.gaml
- [x] Data/Data Importation/models/DXF File Import.gaml
- [x] Data/Data Importation/models/Raster Image Import.gaml
- [x] Data/Data Importation/models/3D shapefile Loading.gaml
- [x] Data/Data Importation/models/PNG Icons.gaml
- [x] Data/Data Importation/models/SHP Import.gaml
- [x] Data/Data Importation/models/BingMap Image Import.gaml
- [x] Data/Data Importation/models/OSM File Import.gaml
- [x] Data/Data Importation/models/Contour Lines.gaml
- [x] Visualization and User Interaction/User Interaction/models/Moving Agents.gaml
- [x] Visualization and User Interaction/User Interaction/models/User input.gaml
- [x] Visualization and User Interaction/User Interaction/models/User Control Architecture.gaml
- [x] Visualization and User Interaction/User Interaction/models/Mouse Exit and Enter.gaml
- [x] Visualization and User Interaction/User Interaction/models/Event Layer.gaml
- [x] Visualization and User Interaction/User Interaction/models/Confirm Dialog.gaml
- [x] Visualization and User Interaction/User Interaction/models/User Pause and Resume.gaml
- [x] Visualization and User Interaction/User Interaction/models/Wizard.gaml
- [x] Visualization and User Interaction/User Interaction/models/User Command.gaml
- [x] Visualization and User Interaction/User Interaction/models/Tools Panel.gaml
- [x] Visualization and User Interaction/Visualization/Legend - Overlay.gaml
- [x] Visualization and User Interaction/Visualization/Text Display.gaml
- [x] Visualization and User Interaction/Visualization/Worm Heatmap.gaml
- [x] Visualization and User Interaction/Visualization/3D Visualization/models/Built-In Shapes.gaml
- [x] Visualization and User Interaction/Visualization/3D Visualization/models/GIS Visualization.gaml
- [x] Visualization and User Interaction/Visualization/3D Visualization/models/Lighting.gaml
- [x] Visualization and User Interaction/Visualization/3D Visualization/models/Building Elevation.gaml
- [x] Visualization and User Interaction/Visualization/3D Visualization/models/Specular Effects.gaml
- [x] Visualization and User Interaction/Visualization/3D Visualization/models/Moving 3D Object.gaml
- [x] Visualization and User Interaction/Visualization/3D Visualization/models/Procedural City.gaml
- [x] Visualization and User Interaction/Visualization/3D Visualization/models/Camera Definitions.gaml
- [x] Visualization and User Interaction/Visualization/Color Brewer.gaml
- [x] Visualization and User Interaction/Visualization/Palettes and Gradients.gaml
- [x] Visualization and User Interaction/Visualization/Charts/models/Pie.gaml
- [x] Visualization and User Interaction/Visualization/Charts/models/Long Series.gaml
- [x] Visualization and User Interaction/Visualization/Charts/models/Series.gaml
- [x] Visualization and User Interaction/Visualization/Charts/models/XY.gaml
- [x] Visualization and User Interaction/Visualization/Charts/models/Radar.gaml
- [x] Visualization and User Interaction/Visualization/Charts/models/Ant Foraging (Charts examples).gaml
- [x] Visualization and User Interaction/Visualization/Charts/models/Heatmap.gaml
- [x] Visualization and User Interaction/Visualization/Charts/models/Bar.gaml
- [x] Visualization and User Interaction/Visualization/Charts/models/Distribution.gaml
- [x] Visualization and User Interaction/Visualization/DEM Generator.gaml
- [x] Visualization and User Interaction/Visualization/Aspects.gaml
- [x] Visualization and User Interaction/Visualization/Building Heatmap.gaml
- [x] Visualization and User Interaction/GUI Design/Parameters and Commands.gaml
- [x] Modeling/Model Coupling/Co-PreyPredator/Prey Predator.gaml
- [x] Modeling/Model Coupling/Co-PreyPredator/Comodel Example (Populations Mutated).gaml
- [x] Modeling/Model Coupling/Co-PreyPredator/Prey Predator Adapter.gaml
- [x] Modeling/Model Coupling/Co-AntPreyPredator/Comodel Example (Mixed Behaviors).gaml
- [x] Modeling/Model Coupling/Co-AntPreyPredator/Ants Adapter.gaml
- [x] Modeling/Model Coupling/Flies and Mosquitos/Adapters/Mosquitos Adapter.gaml
- [x] Modeling/Model Coupling/Flies and Mosquitos/Adapters/Flies Adapter.gaml
- [x] Modeling/Model Coupling/Flies and Mosquitos/Models/Flies.gaml
- [x] Modeling/Model Coupling/Flies and Mosquitos/Models/Mosquitos.gaml
- [x] Modeling/Model Coupling/Flies and Mosquitos/Simple GUI comodel.gaml
- [x] Modeling/Model Coupling/Flies and Mosquitos/Create and kill models.gaml
- [x] Modeling/Multi-thread simulation/Multi-thread.gaml
- [x] Modeling/Multi-Level Usage/Corridor.gaml
- [x] Modeling/Multi-Level Usage/Predators, Preys and Shelters.gaml
- [x] Modeling/Multi-Level Usage/Corridor (Hybrid vs ABM).gaml
- [x] Modeling/Multi-Level Usage/Balls, Groups and Clouds.gaml
- [x] Modeling/Spatial Topology/Agent movement/models/Follow Weighted Network (Agents).gaml
- [x] Modeling/Spatial Topology/Agent movement/models/Wander on Graph.gaml
- [x] Modeling/Spatial Topology/Agent movement/models/Moving3D.gaml
- [x] Modeling/Spatial Topology/Agent movement/models/Goto Grid.gaml
- [x] Modeling/Spatial Topology/Agent movement/models/Goto Directed Graph.gaml
- [x] Modeling/Spatial Topology/Agent movement/models/Goto Network.gaml
- [x] Modeling/Spatial Topology/Agent movement/models/Follow Path.gaml
- [x] Modeling/Spatial Topology/Agent movement/models/Goto Polygon.gaml
- [x] Modeling/Spatial Topology/Agent movement/models/Goto Grid Weights.gaml
- [x] Modeling/Spatial Topology/Agent movement/models/Continuous Field of Vision.gaml
- [x] Modeling/Spatial Topology/Spatial Operators/models/Spatial Operators (Examples).gaml
- [x] Modeling/Spatial Topology/Spatial Operators/models/Simplification and Buffer.gaml
- [x] Modeling/Spatial Topology/Spatial Operators/models/Moran Index.gaml
- [x] Modeling/Spatial Topology/Spatial Operators/models/Geometry Discretization.gaml
- [x] Modeling/Spatial Topology/Spatial Operators/models/Topologies.gaml
- [x] Modeling/Spatial Topology/Spatial Operators/models/Spatial Queries.gaml
- [x] Modeling/Spatial Topology/Spatial Operators/models/Spatial Interpolation.gaml
- [x] Modeling/Spatial Topology/Grids/models/Shortest Path on Grid.gaml
- [x] Modeling/Spatial Topology/Grids/models/Weighted Shortest Path on Grid.gaml
- [x] Modeling/Spatial Topology/Grids/models/Hexagonal Grid.gaml
- [x] Modeling/Spatial Topology/Fields/Accessing Fields.gaml
- [x] Modeling/Spatial Topology/Graphs/models/Shortest paths.gaml
- [x] Modeling/Spatial Topology/Graphs/models/3D Graph.gaml
- [x] Modeling/Spatial Topology/Graphs/models/Graph Operators.gaml
- [x] Modeling/Spatial Topology/Graphs/models/Hand Made Graph.gaml
- [x] Modeling/Spatial Topology/Graphs/models/Multigraph.gaml
- [x] Modeling/Spatial Topology/Graphs/models/Clustering.gaml
- [x] Modeling/Spatial Topology/Graphs/models/Classic Graph Generation.gaml
- [x] Modeling/Spatial Topology/Graphs/models/Graph Loading Layout.gaml
- [x] Modeling/Spatial Topology/Graphs/models/Strahler.gaml
- [x] Modeling/Spatial Topology/Graphs/models/Graph Building From Agents.gaml
- [x] Modeling/Specific Operators/Multicriteria Decision.gaml
- [x] BDI Architecture/models/HelloWorld_BDI.gaml
- [x] BDI Architecture/models/Tutorial/BDI tutorial 2.gaml
- [x] BDI Architecture/models/Tutorial/BDI tutorial 4.gaml
- [x] BDI Architecture/models/Tutorial/BDI tutorial 5.gaml
- [x] BDI Architecture/models/Tutorial/BDI tutorial 1.gaml
- [x] BDI Architecture/models/Tutorial/BDI tutorial 3.gaml
- [x] BDI Architecture/models/Firefighters_BDI.gaml
- [x] BDI Architecture/models/CityEscape_BDI_Emotions.gaml
- [x] BDI Architecture/models/GoldMiner_BDI.gaml
- [x] Pedestrian Skill/models/Simple environment - walk_to.gaml
- [x] Pedestrian Skill/models/Complex environment - walk.gaml
- [x] Pedestrian Skill/models/Generate pedestrian paths.gaml
- [x] FIPA Skill/models/FIPA CFP (1).gaml
- [x] FIPA Skill/models/FIPA Propose (2).gaml
- [x] FIPA Skill/models/FIPA Request (1).gaml
- [x] FIPA Skill/models/FIPA Propose (1).gaml
- [x] FIPA Skill/models/FIPA Query (1).gaml
- [x] FIPA Skill/models/FIPA Request (3).gaml
- [x] FIPA Skill/models/FIPA No Protocol.gaml
- [x] FIPA Skill/models/FIPA Query (2).gaml
- [x] FIPA Skill/models/FIPA CFP (2).gaml
- [x] FIPA Skill/models/FIPA Request (2).gaml
- [x] FIPA Skill/models/FIPA Request (4).gaml
- [x] Genstar Synthesis/models/minimal gosp - matrix.gaml
- [x] Genstar Synthesis/models/minimal gosp - rouen.gaml
- [x] Ordinary Differential Equations/models/Technical Details/Influence of the integration step (LV).gaml
- [x] Ordinary Differential Equations/models/Technical Details/Solve statement options.gaml
- [x] Ordinary Differential Equations/models/Technical Details/Influence of the simulation step (SIR).gaml
- [x] Ordinary Differential Equations/models/Technical Details/Influence of the integration method (LV).gaml
- [x] Ordinary Differential Equations/models/Examples/GeneralizedLotkaVolterra.gaml
- [x] Ordinary Differential Equations/models/For Advanced Users/SIR (Split in Agents, Multiple Strains).gaml
- [x] Ordinary Differential Equations/models/For Advanced Users/ContinuousCurves.gaml
- [x] Ordinary Differential Equations/models/For Advanced Users/SIR (Simple with advanced charts).gaml
- [x] Ordinary Differential Equations/models/SIR (Simple).gaml
- [x] Diffusion Statement/models/Blend color in a cuve (Multiple Signals).gaml
- [x] Diffusion Statement/models/Anisotropic Diffusion (Toroidal).gaml
- [x] Diffusion Statement/models/Kernel matrix generation.gaml
- [x] Diffusion Statement/models/Anisotropic Diffusion (Simple, Grid).gaml
- [x] Diffusion Statement/models/Uniform Diffusion.gaml
- [x] Diffusion Statement/models/Uniform diffusion with mask (Avoid mask).gaml
- [x] Diffusion Statement/models/Diffusion in a cuve (Cycle length).gaml
- [x] Diffusion Statement/models/Anisotropic Diffusion (Various Methods).gaml
- [x] Diffusion Statement/models/Anisotropic Diffusion (Simple, Field).gaml
- [x] Diffusion Statement/models/Uniform Diffusion (Field).gaml
- [x] ODE Tests/models/ODE Solver Test.gaml
- [x] ODE Tests/models/ConsistencyTest.gaml
- [x] ODE Tests/models/Split SystemTest.gaml
 - [x] Network Tests/models/network_test_connection.experiment
 - [x] Network Tests/models/network_test_interaction.experiment
 - [x] Network Tests/models/network_test_interaction_local.experiment
 - [x] Visualization and User Interaction/Visualization/3D Visualization/models/Camera Shared Zoom.experiment
 - [x] BDI Architecture/models/TestBDI.experiment
 - [x] Generated From Simplebdi/models/Simplebdi Tests.experiment
 - [x] Generated From Stats/models/Stats Tests.experiment
 - [x] Generated From Maths/models/Maths Tests.experiment
 - [x] Spatial Tests/models/Creation.experiment
 - [x] Spatial Tests/models/Topology.experiment
 - [x] Spatial Tests/models/Overlapping.experiment
 - [x] Spatial Tests/models/Query.experiment
 - [x] Spatial Tests/models/Relation.experiment
 - [x] Spatial Tests/models/Property.experiment
 - [x] Spatial Tests/models/Operators.experiment
 - [x] Basic Tests/models/MathTest.experiment
 - [x] Basic Tests/models/Int.experiment
 - [x] Basic Tests/models/Boolean.experiment
 - [x] Basic Tests/models/GraphTest.experiment
 - [x] Basic Tests/models/Length.experiment
 - [x] Basic Tests/models/StringTest.experiment
 - [x] Basic Tests/models/ComparisonTest.experiment
 - [x] Generated From Core/models/Core Tests.experiment
 - [x] Multi-criteria Tests/models/multi-criteria.experiment

**Comment by hqnghi88** [comment]
@DAVIEPHAM Quyen have tested some using headless mode, do we consider as it works normally in GUI?

**Comment by lesquoyb** [comment]
@hqnghi88 unfortunatly no, some bugs only happen in the gui, for example the bugs related to opengl

**Comment by hqnghi88** [comment]
OK, thanks, he tested them in both mode.

**Comment by lesquoyb** [comment]
we can't test the last 3 extensively, but it's good enough for the release
