### ISSUE TITLE
gama-headless.bat work only with release "with_JDK"

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama.old#3393]
using the gama-headless.bat in  gama 1.8.2 alpha, i think it works only with the release "with_jdk" as in this important sentence:
call **..\jdk\bin\java** -cp !result! -Xms512m -Xmx%memory% -Djava.awt.headless=true org.eclipse.core.launcher.Main  -application msi.gama.headless.id4 -data "%workDir%" !param! 
we dont have ..\jdk\bin\java for all the cases??

**Comment by hqnghi88** [comment]
<img width="883" alt="image" src="https://user-images.githubusercontent.com/6105384/167290796-8b00b499-2848-4ba9-8646-4991217a3091.png">
Sorry it still not work.

**Comment by hqnghi88** [comment]
Sorry, still a typo, missing "bin"
it must be in bin directory
"%JAVA_HOME%\bin\java.exe"

**Comment by LucasGrjs** [comment]
I pushed a fix @hqnghi88, can you test it on your computer ?

**Comment by hqnghi88** [comment]
Thank you , it works well
