### ISSUE TITLE
"Reveal in OS" sometimes not working

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama.old#3395]
The contextual action "Reveal in OS" sometimes does not find the directory where the file is stored.

- Go to Library models>Modeling>Multi-level Usage
- try to do  "Reveal in OS" on the first file  "Balls, Groups and Clouds.gaml". The explorer opens on the root of the hard drive instead of the current directory.
- if you try the same with other files it works as intended.

**Desktop (please complete the following information):**
 - OS: [Win 10 and Win 11]
 - GAMA version: [1.8.2]

**Comment by AlexisDrogoul** [comment]
It works for me on macOS Monterey. Is it always the first file that fails, when you open GAMA ? There is nothing we can do unfortunately as it is entirely implemented by Eclipse.

**Comment by tnguyenh** [comment]
Yes, but it only happens in a few directories.
