### ISSUE TITLE
event mouse_move is not working when hovering in some places of the display

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama.old#3396]
**Describe the bug**
the event 'mouse_move' is not triggered while hover when it is too high or too low (on the y axis). Maybe it happens also for the x axis. It happens in opengl (but it works fine in java2d).

**To Reproduce**
- In Multi-level usage, open the model 'corridor.gaml'
- add a write inside the event mouse_move (write 'hello'; or 'write button_location distance_to #user_location');
- the event is triggered in the center (the write is executed), but not when hovering on places like the 'capture' button.

**Desktop (please complete the following information):**
 - OS: [win 10]
 - GAMA version: [1.8.2.]
 - opengl

**Comment by tnguyenh** [comment]
Actually the problem only occur in opengl and not java2d. When in opengl, the problem occurs also on macOS.

**Comment by AlexisDrogoul** [comment]
Works for me on Java2D, but there are some glitches on OpenGL (wrong position of the mouse, mainly). I guess we need to open a more specific issue on this matter (differences between java2D and OpenGL in terms of mouse tracking). So I will close it now, putting java2D as the specific type of the display in the model. 

OS : macOS Monterey
