### ISSUE TITLE
Balls, Groups and Clouds.gaml model doesn't work

### ISSUE THREAD

**Issue by DAVIEPHAM** [gama-platform/gama.old#3397]
**Describe the bug**
I try to run experiments with Balls, Groups and Clouds.gaml model in Multi-Level Usage but it doesn't work in both of UI & Headless Mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/83625165/167283840-bd100c76-ed49-4551-91c9-9f84d3a754b3.png)

**Comment by hqnghi88** [comment]
Thanks, it reported by Tri in #3394.
