### ISSUE TITLE
Ants Adaptator texture mtl not loaded

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama.old#3402]
**Describe the bug**
- Open Ants adaptator
- run 3D view (which is an imported)

The MTL is not loaded so the ant are yellow (an error is thwron in Eclipse)
```
Could not open file: /Users/arno/git/gama/msi.gama.models/models/Modeling/Model Coupling/images/fire-ant.mtl
````

**Comment by hqnghi88** [comment]
Which model exactly? anyway, adapter is not supposed to launch separately
