### ISSUE TITLE
Synchronize problem on display

### ISSUE THREAD

**Issue by DAVIEPHAM** [gama-platform/gama.old#3406]
**Describe the bug**
The experiment cannot run when synchronize is selected on display.
See model  : Palette  and  Gradients.gaml

**Screenshots**
![image](https://user-images.githubusercontent.com/83625165/167289276-1130e872-070e-46c6-8736-7ba6345dda24.png)

**Comment by AlexisDrogoul** [comment]
Seems to be a graphic card problem -- solved with some settings in Windows. Closing it.
