### ISSUE TITLE
Scaling radar plots (some library models need to be fixed)

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama.old#3408]
I'm currently testing library models that use radar charts. I'm wondering if it is possible to scale or change the value range, since some radar plots don't fit in the display, but I cannot figure out how to do this. Facets such as 'y_range' don't have any effect.

As an example, the model 'Ordinary Differential Equations/models/For Advanced Users/SIR (Simple with advanced charts).gaml'
 give the following radar chart and need fixing.

![image](https://user-images.githubusercontent.com/18676913/167289922-f37879b4-348e-46d9-869d-1e209d325f57.png)

**Comment by ptaillandier** [comment]
You can define it using the facet y_range: max_value
