### ISSUE TITLE
Simple Traffic Model JTS bug

### ISSUE THREAD

**Issue by LucasGrjs** [gama-platform/gama.old#3409]
model path : Toy Models\Comodels\Urban and Traffic\Urbanization And Traffic Comodel.gaml

3 occurrences in 3 agents at cycle 0: Java error: exception in JTS library
in location <- any_location_in(one_of(building));
TopologyException: side location conflict [ (-4866639.4697694145, -1.0714574630416477E7, 0.0) ]
org.locationtech.jts.geomgraph.EdgeEndStar.propagateSideLabels(EdgeEndStar.java:287)
org.locationtech.jts.geomgraph.EdgeEndStar.computeLabelling(EdgeEndStar.java:123)
org.locationtech.jts.operation.relate.RelateComputer.labelNodeEdges(RelateComputer.java:328)
org.locationtech.jts.operation.relate.RelateComputer.computeIM(RelateComputer.java:128)
org.locationtech.jts.operation.relate.RelateOp.getIntersectionMatrix(RelateOp.java:112)
org.locationtech.jts.operation.relate.RelateOp.relate(RelateOp.java:57)
org.locationtech.jts.geom.Geometry.relate(Geometry.java:1033)
when applying the any_location_in operator on building731
in location <- any_location_in(one_of(building));
in create people number: 1000  {
	location <- any_location_in(one_of(building));
}

in create people number: 1000  {
	location <- any_location_in(one_of(building));
}

in init  {
	create building from: building_shapefile ;
	create road from: road_shapefile ;
	create people number: 1000  {
		location <- any_location_in(one_of(building));
	}

	road_weights <- road as_map (each :: each.shape.perimeter);
	road_network <- as_edge_graph(road);
}

in create Adapter of Traffice  {
	do transform ;
}

in init  {
	create Adapter of Traffice  {
		do transform ;
	}

	create Adapter ;
}

in agents people221, Simulation 0, main0

**Comment by ptaillandier** [comment]
I clean the building data.... I hope it is working better now.

**Comment by hqnghi88** [comment]
It works very well! Thanks a lot.
