### ISSUE TITLE
Reduce repository size

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama.old#3415]
**Is your request related to a problem? Please describe.**
Today's GAMA's github repository (after a fresh `clone` dated on commit 3422b50da) size 1.4 GiB, but most of it (1.1GiB) is only dedicated to git history !!
![image](https://user-images.githubusercontent.com/16764085/167544268-b64bdb77-c903-42f1-93a2-a44087c3af1f.png)

**Describe the improvement you'd like**
Maybe we could reduce size of this history in different ways : 
- Remove detailed history after XXX commits
    - `git repack -a -d --depth=250 --window=250` keep last 250 commits, remove 1,254 files, but history doesn't change size
- Remove detailed history after XXX commits + Lose track of deleted commits
    - `git gc --aggressive --prune=now`  (didn't tried it)
- Squash legacy commits with a project rebase
- Else ? 🤷

**Comment by AlexisDrogoul** [comment]
Just to mention that we are also running out of LFS space...

**Comment by RoiArthurB** [comment]
Git LFS and Git history files are two things totally unrelated, first in practice, and second because `gama-platform/gama` repository doesn't use LFS :) 

And the LFS GH's space should be resolved soon, it's a problem from one contributor on the experimental repository :)

**Comment by AlexisDrogoul** [comment]
Has the LFS problem on `gama-platform/experimental` been solved ?

**Comment by AlexisDrogoul** [comment]
I think we should move to a solution like the one exposed here (using a `history` repository): https://andrewlock.net/reducing-the-size-of-a-git-repository-with-git-replace/

**Comment by AlexisDrogoul** [comment]
I think that we can close this proposal, as GAMA 2.0 will have its own repository --
