### ISSUE TITLE
Gama Control (web socket) : stop of the simulation 

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama.old#3416]
**Is your request related to a problem? Please describe.**

in order to remotely control GAMA through web socket, it could be interesting to add the possibility to add a stop condition when we launch the simulation.

The second point is that we need a way for the client to know that a simulation / an experiment is finished

**Comment by hqnghi88** [comment]
the stop condition is somehow in the model? as if we consider websocket as normal gui gama control , there is no textfield to enter the condition when we click play button? 
The second point can be request by exp dead(simulation) or paused.
<img width="522" alt="image" src="https://user-images.githubusercontent.com/6105384/167561877-a36bfa6a-3767-4ae4-b890-b675ea5c98a5.png">

**Comment by benoitgaudou** [comment]
I had in mind an usage similar to the one that was aimed by gamar : 
to be able to  run simulations from  R  or a  Jupyter Notebook,   get results and analyse them.
To  this purpose  (and  that  is  why it was added to the headless XML files),  we need to be  able to run simulations until a given  point (cycle or condition) ...  

Otherwise in  the R/Pythonn/JS controller we will  need to  implement this be doing  step after step call  to the simulation.
I think it would  be more convenient to have  this step by step loop done  in GAMA ?

**Comment by hqnghi88** [comment]
currently, we have capability to control with these messages (i wrote the messages, must be in json):
first: launch with param
then: in a loop: 
         call step (send json)
         call expression computation of the condition (send json and get the values from gama)
         break or stop if true

something like we programming gaml, but in js and json .
 of course, if you found that convenient for r-user, as it was in xml, we can add condition expression when launch.

**Comment by benoitgaudou** [comment]
If  possible in a short time  and  without breaking  everything, I  think  it  could be  a great feature.

**Comment by hqnghi88** [comment]
I at last finish the implementation. You can check with the code in gama.client repository. here is an example result. Stop condition and finish callback from server.

```
request {"type":"launch","model":"C:\\git\\gama/msi.gama.models/models/Tutorials/Road Traffic/models/Model 05.gaml","experiment":"road_traffic","parameters":[{"name":"Number of people agents","value":"111","type":"int"},{"name":"Value of destruction when a people agent takes a road","value":"0.2","type":"float"}],"until":"cycle>=15","exp_id":0,"socket_id":0}
------------------------------
{ "type": "exp", "socket_id": "1364195547", "exp_id": "1" }
------------------------------
request {"type":"play","socket_id":"1364195547","exp_id":"1"}
------------------------------
finish
------------------------------
request {"type":"expression","socket_id":"1364195547","exp_id":"1","expr":"length(people)"}
------------------------------
{"result":"111"}
------------------------------
request {"type":"expression","socket_id":"1364195547","exp_id":"1","expr":"cycle"}
------------------------------
{"result":"15"}
------------------------------
request {"type":"reload","socket_id":"1364195547","exp_id":"1","parameters":[{"name":"Number of people agents","value":"333","type":"int"},{"name":"Value of destruction when a people agent takes a road","value":"0.2","type":"float"}],"until":"cycle>=10000"}
------------------------------
reload
------------------------------
request {"type":"expression","socket_id":"1364195547","exp_id":"1","expr":"cycle"}
------------------------------
{"result":"1"}
------------------------------
request {"type":"play","socket_id":"1364195547","exp_id":"1"}
------------------------------
finish
------------------------------
request {"type":"expression","socket_id":"1364195547","exp_id":"1","expr":"length(people)"}
------------------------------
{"result":"333"}
------------------------------
request {"type":"expression","socket_id":"1364195547","exp_id":"1","expr":"cycle"}
------------------------------
{"result":"10000"}
------------------------------
```
