### ISSUE TITLE
Path with space aren't well encoded in Headless mode

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama.old#3417]
**Describe the bug**
When launching gama-headless pointing to a sub-folder with a path in it, this path is re-encoded under http protocol which isn't compatible with unix one.

**To Reproduce**
1. Go `Gama/headless` folder
2. Launch a command like this:
```
$ bash ./gama-headless.sh -batch experimentName ./samples/predator\ prey/predatorPrey.gaml
$ bash ./gama-headless.sh -batch experimentName "./samples/predator prey/predatorPrey.gaml"
```
3. See in both commands error saying `./samples/predator%20prey/predatorPrey.gaml file does not exist`

**Expected behavior**
Not automatically encoding headless paths as URI

**Desktop (please complete the following information):**
 - OS: Linux server (Debian)
 - PC Model: Server
 - GAMA version: 1.8.2-RC1
 - Java version: 17 Embedded

**Comment by AlexisDrogoul** [comment]
Can someone test this on Linux ? It works on macOS.
