### ISSUE TITLE
The connection using tcp protocol that doesn't work

### ISSUE THREAD

**Issue by hu1909** [gama-platform/gama.old#3418]
**My bug**
I use the Android app to connect to GAMA model. I use GAMA model as a server and android app as a client. After successfully connecting via TCP protocol but I couldn't send out my data

**Some Screenshots**

<img src="https://user-images.githubusercontent.com/91870751/168041591-3aa93d33-27a2-4a60-b92e-3b9667bb4f4b.png" width="600" height="300">

As you can see in this picture, my function SendMessageTask it take it own data which mean it work fine 

<img src="https://user-images.githubusercontent.com/91870751/168042565-4c075b57-1d2c-4146-b349-9ce702548e67.png" width="600" height="300">

Here is my code to create a server . the " do connect ... " statement is inside the init block and the reflex receive is in global block. I When I run both GAMA and Android app, my GAMA model waited for connection of client which was Android app. And I connected from my Android app to Gama successfully but when I try to send some message from Android, It is not things happen. And also I create a client by python and try to connect with GAMA it also didn't work.

<img src="https://user-images.githubusercontent.com/91870751/168044617-c745afe3-cd6d-4be2-a368-e250fcb9b792.png" width="600" height="300">

Here is my client in python, as you can see it work well but in GAMA it had nothing.

**Note**
I  disabled a firewall so that the connection worked

**Comment by hu1909** [comment]
@hqnghi88 thank you for helping to solve the issue. My Android app and GAMA model work well now

**Comment by hqnghi88** [comment]
Hi, It was the problem of messagebox in network skill, where a raw message without specific wrapping of gamamessage cannot be received. 
But did you solve the problem of laggy communication we had, can you specify the solution if possible?
Thanks.

**Comment by hu1909** [comment]
Yes, I did .  Turn out, I did not put "\n\r\n" at the end of my message to close it so GAMA was waiting. That was the reason why my GAMA model could not print in console.
