### ISSUE TITLE
Windowing layout: Problem when moving displays position

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama.old#3420]
**Describe the bug**
Sorry for this sunday afternoon issue (which might be a replicate of another one but I couldn't find it)...

While working on the Bac Hung Hai Model to try to find a suitable layout for the position window I started to see some weird behavior in the positioning windowing.

I have tested it on a more simple model (Tutorial/Road Traffic/Model7) where it seems to happen pretty easily as soon as you have two displays defined and you want to switch their position (no matter if there are both in opengl or one in opengl and one in java2D)=> try to place the left display at the right of the right display as shown here
![Untitled mov](https://user-images.githubusercontent.com/3928502/168456635-ffcb5480-11ad-434c-9ef1-8be91294a439.gif)

It doesn't seems to happen when you switch the display from top to bottom

**Desktop (please complete the following information):**
- OS:GAMA_1.8.2-RC1_MacOS_with_JDK

**Comment by AlexisDrogoul** [comment]
This one is specific to macOS. The horizontal (and even vertical) moves when you have two windows do not generate any event on the SWT side. It's a bug. And it is not something we are going to fix ... Resizing the views after the move, however, works ...
