### ISSUE TITLE
Gama package not found by Ubuntu software

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3424]
**Describe the bug**
After installing Gama-1.8.2-RC1 for ubuntu with the .deb, I am unable to find it in `Ubuntu software`
![image](https://user-images.githubusercontent.com/6374469/168518132-026f028a-21df-4b23-a61b-f320740ec293.png)
It is however found by the system and can be removed with apt-get
![image](https://user-images.githubusercontent.com/6374469/168518334-20105e54-2fd1-4060-a09b-f118096675e1.png)

**Comment by RoiArthurB** [comment]
Hi,

As you did install the installer (`.deb` file) directly downloaded from Github Release and not from a package server (like PPA for Debian-based), the `Ubuntu Software` doesn't have any track of GAMA (as US rely on PPA/Snap repo).

In the same idea, if you did install Github Desktop from the `.deb`, you do not have it displayed in US :)

---

An idea could be to check if it's possible to do/propose to add Gama's PPA repo after installing Gama from the deb file (if we do have a PPA) :)
