### ISSUE TITLE
Move GamaBDIPlanConverter out of serialize plugin

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama.old#3428]
**Describe the bug**
I am trying to produce the minimal version of gama headless, here are the core plugin loaded.
> GAMA: msi.gama.core                         loaded in_____ 920ms
> GAMA: msi.gama.lang.gaml                    loaded in_____ 2ms
> GAMA: msi.gama.headless                     loaded in_____ 2ms
> GAMA: ummisco.gama.serialize                loaded in_____ 6ms
> GAMA: msi.gaml.architecture.simplebdi       loaded in_____ 44ms
> GAMA: ummisco.gama.network                  loaded in_____ 6ms
> GAMA: all plugins                           loaded in_____ 1056ms

Beside the core (core, gaml), the 2 plugins: network and serialize are somehow logically to be loaded for gama server. But i find a bit strange if simplebdi is. mandatory in this case (and it took the 44ms to be ready).
The cause come from the dependency in serialize , in  GamaBDIPlanConverter, which will serialize the BDIPlan. Knowing that the converter is requires to serialize the gama model , not only with bdi skill, but also with other skill, operators.... So i wonder if we can do 2 things:
Firstly, move GamaBDIPlanConverter, may be to simplebdi.
Secondly, propose a structure to all skill, operators,... to be serialize with the method in plugin serialize. It means the dependent in reverse with the current, serialize will be import in other plugins.

**Comment by benoitgaudou** [comment]
Hi Nghi,

I wondering if it is necessary to lighten GAMA so much...
In  fact  it makes that many models working with the GAMA release will not  work anymore  with  the GAMA server...

benoit

**Comment by hqnghi88** [comment]
dear Benoit. 
yes of course the library will broken. but at least i found that the current serializer is a bit manual hard coded. it time to restructure and furthur, the light gama for LSP and also with a hoping new feature of installation of requires plugins on the fly.

**Comment by AlexisDrogoul** [comment]
Hi, 

I agree with @hqnghi88 : serialisation should be distributed over the different plugins. One possible way to do this is to declare an annotation for GamaTypes, that would indicate the class responsible for serialising their instances. Or declare a new method in IType / GamaType to return the class. Both could be called by the serialiser.

**Comment by AlexisDrogoul** [comment]
The addition of the `@converter` annotation (in the `serialize` plugin), allows to declare the converter as an annotation to the `IType`. The converters are then discovered and instantiated, based on the class wrapped by the `IType`, by the `Converters` class in the `serialize` plugin. This allows to solve the problem reported here and to easily add future converters for new types.
