### ISSUE TITLE
Get sender information when using Network skill with other application

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3430]
**Is your request related to a problem? Please describe.**
In the network skill, when we receive a message from another application than gama, the `sender` attribute's value is `undefined`. It could be usefull to get some basic information like the IP address to send a message back.

example with this simple server:
```
model NetworkManager

global {
	init {
		create NetworkManager number:1;
	}
}

species NetworkManager skills:[network]{

	int port <- 8989;
	
	init {
		do connect protocol:"tcp_server" port:port raw:true;
	}
	
	reflex read_messages when:state=st_wait_players_connect{
		loop while:has_more_message(){
			message mess <- fetch_message();
			write "message received: " + mess.contents;
                        write "sender: " + mess.sender; // Right now it prints: "sender: undefined"
		}
	}

	
}

experiment test {
	output {
	}
}
```
Right now the best way for me to send a message back to the client is to have the client send its IP in the content of the message and process it in the gama model, which adds complexity for nothing in both programs

It would be nice for example to be able to write this:
```
	reflex read_messages when:state=st_wait_players_connect{
		loop while:has_more_message(){
			message mess <- fetch_message();
			write "message received: " + mess.contents;
                        do send:"OK, message received" to:mess.sender;
		}
	}
```

**Comment by hqnghi88** [comment]
The generic structure used in network plugin for all protocol, is channel broadcast-likely. Even server or client, subscribe to a mailbox (by default, servers are in "server_group", clients are in "client_group", but you can mix them as "TV5", "CCTV"... with mixed of any servers, clients) by join_group statement. Any message then broadcast in the mailboxes, and the agents looking for has_more_message in their channel. That 's a bit different with end-to-end as you describe, but i agree that with raw facet we should know sender, and i found that sending a ip message is enough otherwise the external message must be well-formed as a right gamaMessage (with metadata of sender, ip, etc), no way to avoid these data if you want a short solution in gama as mess.sender or mess.ip.

**Comment by hqnghi88** [comment]
In your case, any external connection will register in client_group so if you want to send back:
		do send to: "client_group" contents: ("I am Server Leader " + name + ", I give order to client_group at " + cycle);
and the external parse the result.

**Comment by hqnghi88** [comment]
I push the implementation that return the sender in received message from external application (raw:true). It return getInetAddress of current socket. Please test and report back.

**Comment by hqnghi88** [comment]
I also reactivate the multi-threaded tcp server in network plugin (dont remember why it was disabled).  It means you can have multiple connection from 1 or more external application. To reply to the different client, use the sender 
do send to: mess.sender contents: "hi"
<img width="816" alt="image" src="https://user-images.githubusercontent.com/6105384/170888303-e6ba3afa-654a-44b1-b93f-1b90edc86b7c.png">

**Comment by lesquoyb** [comment]
I tested the sender fix and it works like a charm, same for multiple clients at the same time ! 
But now is it still possible to send a message to a simple ip/port without having it connected first ?

**Comment by hqnghi88** [comment]
Sorry, i dont really understand the question, or i dont know it is possible before. TCP must have handshake so it must connected first.

**Comment by lesquoyb** [comment]
Yes your are right, I wanted to still be able to use the raw IP and port to send messages, but as you said we need a connection to the server first, which means we will always have the `sender` object available as long as the client sends at least one message.
So issue closed, thanks again

**Comment by hqnghi88** [comment]
Just to complete, the raw IP can use in "connect" statement, then there is a generated port when server accept client handshake (you see in the sender object).
