### ISSUE TITLE
Send and Receive message in GAMA through TCP protocol 

### ISSUE THREAD

**Issue by hu1909** [gama-platform/gama.old#3431]
**Describe the bug**
I try to send message from my GAMA model to my Android App and I use this block of code to send a basic message 

```
reflex send{
	do send to: "client_group" contents: ("I am Server Leader " + name + ", I give order to client_group at " + cycle);
}
```

but when I receive from my Android App, I receive not exactly message that I want to receive 

<img src="https://user-images.githubusercontent.com/91870751/170180841-765570c2-3bba-47ce-b6e6-7cd6255a2e69.png" />

This image is the message that I receive from GAMA model. After that, I try to add raw:true  when I create a server in GAMA like this 

```
do connect protocol: "tcp_server" port: port with_name:name raw:true;
```

But it also pops out a issue that I can not send any message from Android App to GAMA model like before but the message that I receive from GAMA in Android App  is not contain strange string anymore like this 

![okkk](https://user-images.githubusercontent.com/91870751/170181455-907b618d-3311-4cb2-ad5f-e8a2a3755ade.png)

**Comment by hqnghi88** [comment]
You can use raw:true now to get pure message, please report back if its still occurs

**Comment by hu1909** [comment]
Thank you @hqnghi88 , My GAMA and Android App work well now.
