### ISSUE TITLE
Displaying a warning when overriding a reflex/action

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3434]
**Is your request related to a problem? Please describe.**
To override a reflex or an action in gaml you simply have to create a new one with the same name.
I understand how it's useful for polymorphism but it is also a source of potential bugs: for example let's say you work on someone else's big model that you don't really master, you could be overriding important functions without knowing it just by adding yours. 
So I think overriding shouldn't be silent, so the modeler is aware of it. We could for example print a warning or having to explicitly say you are overriding (maybe in a next version as it will break a lot of models)

**Comment by ptaillandier** [comment]
It seems to be already the case, you have a warning for some built-in
action and a "information tag" when overwriting an existing action (see the
image).
[image: exemple.PNG]

Le ven. 27 mai 2022 à 10:49, Baptiste Lesquoy ***@***.***> a
écrit :

**Comment by lesquoyb** [comment]
Oh true, I didn't see the info !
![image](https://user-images.githubusercontent.com/6374469/170627633-793004de-1d0c-42fb-a993-b024a7d616c5.png)
It is not as visible in dark mode as in light mode, maybe we can do something to make it clearer ? Maybe juste make the info/warning/error icon column a little bit bigger ? Or just picking a bright colour for the dark mode ?

**Comment by hqnghi88** [comment]
Well, it is the last thing that make me switch back to light mode, sometime, not only eclipse/gama but also vs code, sublime or vs studio. I dont think it possible to adjust that colors as theorically in any language: "error is red". The problem views/error view is where we should check beside the  editors marks.

**Comment by AlexisDrogoul** [comment]
I've implemented a small fix for this, by using more vivid colours in dark mode for error and info markers, and enlarging a bit the annotation column. 

Like this : 

<img width="137" alt="Experiment and simulation gaml - Gama (runtime) 2022-05-27 22-55-53" src="https://user-images.githubusercontent.com/579256/170735739-786cbd9d-3e21-462e-9259-691bd3fccc91.png">
<img width="120" alt="Experiment and simulation gaml - Gama (runtime) 2022-05-27 22-55-30" src="https://user-images.githubusercontent.com/579256/170735756-84082756-3e8a-4040-b566-b1652ceee76b.png">
