### ISSUE TITLE
"Colorize code sections" offset and size are completely off

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama.old#3435]
**Describe the bug**
When choosing "Colorise code sections" in the "Model" menu, the sections appear misaligned and wrongly sized.

**Screenshots**

<img width="506" alt="Experiment and simulation gaml - Gama (runtime) 2022-05-30 21-54-00" src="https://user-images.githubusercontent.com/579256/171018494-a2124909-ecd7-4129-8ec0-f46b0a284cc0.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - GAMA version: 1.8.2 git

**Comment by lesquoyb** [comment]
As a complement of information: I tested on Windows with multiple scaling values and on Linux and couldn't reproduce it, so it's probably specific to macOS

**Comment by AlexisDrogoul** [comment]
Tested on macOS, Windows and Linux -- seems to work well with the latest commits
