### ISSUE TITLE
min_value facet in diffuse in not identified

### ISSUE THREAD

**Issue by hana-gharred** [gama-platform/gama.old#3439]
**Description**
diffuse var: phero  on: cells matrix:mat_diff min_value:0.8;

min_value is not accepted and not recognized as facet.

 - OS: [Windows 11]
 - GAMA version: [1.8.2RC1]
 - Java version: [1.8]

**Comment by lesquoyb** [comment]
Hello, the facet you are looking for is `min` though it should be mentioned in the documentation instead of `min_value`

**Comment by lesquoyb** [comment]
It seems like the facet changed from 1.8.1 to 1.8.2 and some bit of code was still using the `min_value` facet. I commited a fix but I need some of the plugin's experts (for example: @AlexisDrogoul , @benoitgaudou and @hqnghi88 ) to check if it's working as expected

**Comment by AlexisDrogoul** [comment]
Yes it is fixed and you were right: some internal was still using the old facet name.
