### ISSUE TITLE
Java2D graph chart crashes if model runs too fast

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama.old#3442]
**Describe the bug**
Not sure of the source of this bug, but some charts crash after some time (not fixed) while the simulation goes too fast. It didn't been reproduced (yet?) with a Mac M1 laptop, but does on some lower-grade ones.

**To Reproduce**
1. Open the step latest step (step 5) of the BDI tutorial
2. Start the simulation
3. See error as on screenshot below

**Expected behavior**
No crash 🤷🤷🤷

**Screenshots**
![image](https://user-images.githubusercontent.com/16764085/174242878-b762fc57-cd94-4140-865d-d3f859108534.png)

**Desktop (please complete the following information):**
 - OS: Windows / Linux
 - GAMA version: git
 - Java version: 17.0.3 LTS
 - Graphics cards / Display system: nVidia GeForce 970 / Intel Chipset

**Additional context**
1. If displays are synchronized, this bug seems to never occured (which lead me to think that the problem comes from the too fast model running and charts aren't able to follow).
2. Build version doesn't display any errors from running logs when charts crash.

**Comment by hqnghi88** [comment]
Hi,
Not only lower-grade (asus rog g14), i can have it with 3 simulations on that model
<img width="903" alt="image" src="https://user-images.githubusercontent.com/6105384/174266673-02ffd547-69a3-4bf9-8d11-58579f8d28ce.png">

**Comment by AlexisDrogoul** [comment]
I dont get it on MBP 16" M1. It's running fast, but w/o freezing. W/o errors, though, it is difficult to know what's happening.

**Comment by AlexisDrogoul** [comment]
Additional information : the problem doesn't occur with OpenGL displays.

**Comment by AlexisDrogoul** [comment]
Tested on macOS, Windows and Linux. The charts are much more stable, or so it seems. Case closed in my opinion.
