### ISSUE TITLE
Missing check icons in Model menu on Windows

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3443]
**Describe the bug**
On windows, in the menu `Model` there is no check icon next to the options that are activated, while there are present on Linux
![image](https://user-images.githubusercontent.com/6374469/174538110-a15a3331-dde4-43d9-a0b1-8380af73c487.png)

**Comment by AlexisDrogoul** [comment]
Very strange. Does it mean you can't have icons + check mark at the same time on Windows ? Like this on macOS : 
![image](https://user-images.githubusercontent.com/579256/175439686-0f426874-d037-45a1-a01e-1eb8396105cf.png)

**Comment by hqnghi88** [comment]
No, i dont have that check mark, images are good but no checkmark.

**Comment by AlexisDrogoul** [comment]
That's it. You can't have both at the same time. At least in SWT. Really strange. I havent seen it mentioned anywhere. Here is the snapshot taken after removing the icons: 

![image](https://user-images.githubusercontent.com/579256/175457613-5c61bc22-6f84-469b-aac1-86f3b7de5588.png)


So should we remove the icon or the check mark on Windows ? It's up to you to decide !

**Comment by hqnghi88** [comment]
I prefer to have checked or non-checked as it is more informative than the static icons, but how about changing icons depends on state?
