### ISSUE TITLE
Strange resizing/artifacts in opengl display when rotating

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3446]
**Describe the bug**
When I try to manipulate (mostly rotating, translation seems to work fine) an opengl display I sometimes get strange resizings or artifacts.
It comes back to normal once I stop moving.

Here is an example with the `Ripples and Fishes` from the library models

![opengl_bug](https://user-images.githubusercontent.com/6374469/174721902-2d7d5feb-bb28-4c81-9ced-10820ba07131.gif)

**Comment by AlexisDrogoul** [comment]
The issue can be safely closed as far as I know.
