### ISSUE TITLE
The new synchronize is drastically slower

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3450]
**Describe the bug**
Since the changes with the synchronize facet (now being a facet of the output instead of the display) I noticed that models using it are dramatically slower. Almost unusable for most of them.

Here is an example model which, on my computer (and tried with same behavior on another one) won't even run the first cycle in 5/10 minutes with gama git and the new synchronize, but if I use the release 1.8.2-RC1 (without the changes in display) or if I disable the synchronize it will run smoothly: [CoursUSTH-Day5-ModelTrafficWeek1.zip](https://github.com/gama-platform/gama/files/8954476/CoursUSTH-Day5-ModelTrafficWeek1.zip)

**Comment by AlexisDrogoul** [comment]
Seems to be the monitors, no ?
