### ISSUE TITLE
It is possible to create a user_command with the name of a species

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3453]
**Describe the bug**
In gaml it is possible to create a user_command with the same name as a species. This can lead to a lot of confusion, and some unexpected behavior in the gama editor.
For example:
```
model editor

global {

  init {
    create test_species;
  }

  user_command test_species {
    write "hello";
  }

}

species test_species {
  int a;
}
```

In this model, if you try to go to the definition of `test_species` referenced in the create statement, the editor will bring you to the user_command.

I don't know if it can (or should) be completely forbidden by the language, but at least a warning should be displayed

**Comment by hqnghi88** [comment]
Hi,
For me, it is wrong linked somewhere, it is not only for user_command, but aspects or actions have the same issue if you declare same identifier in a model.

**Comment by lesquoyb** [comment]
Digging a little bit more the "go to definition" problem mentioned seem to be a different one (see #3454 ), but I still feel that a warning should be displayed to incentivize good coding practice even though their shouldn't be in practice any overlap between user_command, aspect, actions and species (for now)

**Comment by AlexisDrogoul** [comment]
I have decided to adopt the same rules as actions (which prohibit using species names).
