### ISSUE TITLE
The "Open Declaration" feature of the gama IDE is broken

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3454]
**Describe the bug**
When you try to go to the declaration of a variable in the gama ide, it seems that the feature leads to the first declaration of an object with the same name, which is not always the good one.
For example in this model:
```
model declaration

global {
	
	init {
		int a <- 3;
	}
	
}

species b {
	
	int a;
	action test {
		a <- 4;
	}
	
}
```
If you try to go to the declaration of `a`, in the `test` action, the editor will bring you to the declaration of `a` in the global species, which does not exist in this scope.

**Comment by AlexisDrogoul** [comment]
Closed as duplicate to gama-platform/gama2#46 : the scoping of variables / symbols cannot be done properly in the current state of the grammar.
