### ISSUE TITLE
Charts do not plot data when in editor mode

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3455]
**Describe the bug**
If you run a model that plots data, and for some reason you still want to work on the code while it's running, you can click on the `open modelling perspective` button 
![image](https://user-images.githubusercontent.com/6374469/175863265-8612c947-4699-4391-865c-aa4633ae1abc.png)
to go back to code, but then every update on the plot will be "lost".
For example with this model:
```
/**
* Name: NewModel
* Based on the internal empty template. 
* Author: lesqu
* Tags: 
*/


model NewModel

global {
	int np <- 0;
	
	init {
		create a;
	}
	
}

species a {
	float val;
	
	reflex g {
		val <- rnd(0.0, 1000.0);
	}
	
}

experiment b type:batch repeat:1 until:cycle=10000{
	
	parameter "no point param" var:np min:0 max:100 step:1;
	
	permanent {
		display disp type:java2D{
			chart "a" type:xy {
				data "value" value:{np, simulations mean_of (each.a mean_of (each.val))};
			}			
		}
	}
	
}
```
I switched to the modelling perspective from step 11 to 76 and all those data points are lost:
![image](https://user-images.githubusercontent.com/6374469/175863533-39108fe7-1193-424c-bc6f-cc1a50d370df.png)

This is the case in batch as much as in gui experiment and with java2D as much as with opengl

**Comment by benoitgaudou** [comment]
Hi Baptiste,

There is the  following preference, to choose whether you want to draw displays in Modeling perspective.

<img width="539" alt="Screenshot 2022-06-27 at 07 15 19" src="https://user-images.githubusercontent.com/1555274/175864917-6cdc925d-27e7-430d-9d2b-1e81660c5164.png">
 
Could you check it, and if it has the  expected behavior.

**Comment by lesquoyb** [comment]
Yes, it fixed the issue, is there a particular reason this setting is set to false by default ?

**Comment by RoiArthurB** [comment]
Can you please add this information on the [Troubleshooting](https://github.com/gama-platform/gama/wiki/Troubleshooting) page? :)

**Comment by benoitgaudou** [comment]
I gues it is set to true for performance sake.
Benoit

Le lun. 27 juin 2022 à 08:33, Baptiste Lesquoy ***@***.***> a
écrit :
