### ISSUE TITLE
Online documentation using the internal browser crashes

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama.old#3457]
**Describe the bug**
When using the quick search box on the top right-end of GAMA and double-clicking on a result, the webpage invoked crashes with the following message : 

**Screenshots**
<img width="544" alt="dddddd -  - Gama (runtime) 2022-07-02 09-08-42" src="https://user-images.githubusercontent.com/579256/176982861-079eac6e-1894-47ae-8ad1-da0fcaf077df.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey 
 - PC Model: MBP M1 16"
 - GAMA version: git

**Comment by RoiArthurB** [comment]
Works for me 🤷🤷🤷

![image](https://user-images.githubusercontent.com/16764085/177022664-ebf71e87-6f81-4769-8518-5aa06c558408.png)

It may had been a short bug from the website hosting, or (if you still have that problem) comes from Eclipse M1's embedded browser :/

**Comment by AlexisDrogoul** [comment]
Could be that Eclipse is using the legacy WebKit on macOS, where the IntersectionObserver API is turned off by default. https://stackoverflow.com/questions/59074487/reference-error-cant-find-variable-intersectionobserver . Some of the sites suggest a workaround (using `polyfill`), could it be possible to implement it ?

**Comment by RoiArthurB** [comment]
Fixed by https://github.com/gama-platform/gama-platform.github.io/commit/ce1122d746b1ec8043617c49c44986c13042fa5b - Have to wait for website rebuilding and publish :)

**Comment by RoiArthurB** [comment]
The issue seems to be linked to the embedded WebKit in Eclipse M1 and not the website (which confuses me even more as I did successfully make it run with my website's update...)

Reopening...

**Comment by benoitgaudou** [comment]
I just tested on my MACOS Intel, and I do not have  the issue anymore.
(I had it a few weeks ago)

**Comment by lesquoyb** [comment]
@AlexisDrogoul You still had the problem if I remember correctly, I just tested on a macOS M1 and everything works fine, could you confirm that it is fixed for you too ?
There may be a cache issue in your case, as the bug fix comes from changes in the website code, so if you still have it maybe try to reload the page without the cache, or test with a fresh gama installation

**Comment by AlexisDrogoul** [comment]
It's working just great now ! Thanks guys !
