### ISSUE TITLE
Wrong distributions of simulations on cores

### ISSUE THREAD

**Issue by LeKumquat** [gama-platform/gama.old#3461]
**Describe the bug**
Wrong distribution of the simulations on my cores. I'm using 4 cores at the beginning, the 4 first simulations run well, but after, they are all launched at the same time, and they run all at the same time.

**To Reproduce**
1. Go to Help -> Preferences -> Parallelism
2. Toggle "gama.pref_parallel_simulations_all" to true
3. Set the Max. number of threads to use at 4
4. Go to 'Library models/Model Exploration/Batch Simulation'
5. Click on 'Batch.gaml'
6. Scroll down to 'Explicit'
7. Add some values to method explicit like:
        ["infection_rate"::1.0, "dying_proba":: 0.05],
        ["infection_rate"::1.0, "dying_proba":: 0.01],
        ["infection_rate"::1.0, "dying_proba":: 0.02],
        ["infection_rate"::1.0, "dying_proba":: 0.03],
        ["infection_rate"::0.5, "dying_proba":: 0.05],
        ["infection_rate"::0.4, "dying_proba":: 0.05],
        ["infection_rate"::0.3, "dying_proba":: 0.05],
        ["infection_rate"::0.2, "dying_proba":: 0.05],
8. Run the Explicit experiment
9. See error.

**Expected behavior**
We expect that only the right number of simulation (depending on the number of cores) are running at the same time. An optimal use of the resources is required (to not load all the simulation in memory, that can lead to crash).

**Screenshots**
![first_screen](https://user-images.githubusercontent.com/72857645/178466445-18c266dd-8072-479a-89b1-cfa93e252b95.png)
![second_screen](https://user-images.githubusercontent.com/72857645/178466466-a16a2f95-61e1-4aa5-8a4b-ba45cd994db3.png)
![thrid_screen](https://user-images.githubusercontent.com/72857645/178466570-a1d2435d-e271-4ced-a70a-3306b55172d2.png)

**Desktop (please complete the following information):**
 - OS: ubuntu debian
 - PC Model: predator helios 300
 - GAMA version: GIT 1.8.2
 - Java version: jdk-17.0.2
 - Graphics cards / Display system: RTX 2060

**Additional context**
Tested with 1.8.2 RC1 on MAC(intel) OS: Monteray, same behavior.

**Comment by ptaillandier** [comment]
I tried to fix this issue with my last commit. Could you test the fix?

**Comment by LeKumquat** [comment]
It works for me ! Thank you

![screen](https://user-images.githubusercontent.com/72857645/178676063-a9c1fbf5-af3d-434d-89b4-7fc0457c5e6c.png)
.
