### ISSUE TITLE
Monitor view: either include it in the layout or in/near the parameters view

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama.old#3465]
The view containing the monitors described in experiments behaves quite badly with the layout of display views and, even if it is moved, its position is not remembered from one session to another. 

<img width="1028" alt="New Model gaml 2022-07-15 13-15-50" src="https://user-images.githubusercontent.com/579256/179163427-742919a6-cc85-4e3e-843c-a3af964a11da.png">

Its behaviour should be more in line with the other views. There are 3 possible solutions:

1. Make it appear by default below the parameters view: 

<img width="1028" alt="New Model gaml 2022-07-15 13-22-33" src="https://user-images.githubusercontent.com/579256/179163749-2a12a9ad-4773-4f97-ab9f-db5080e8801e.png">

2. Make it participate to the layout definition (for instance, with a #split layout):

<img width="1028" alt="New Model gaml 2022-07-15 13-23-36" src="https://user-images.githubusercontent.com/579256/179163901-92427d45-5603-4e84-9694-7c1b6e42d32a.png">

3. Suppress it and move the monitors to the parameters view (which contain already more or less similar possibilities). Something like this: 

![image](https://user-images.githubusercontent.com/579256/179164503-1052919c-f1e3-49a3-9c06-5789ec994010.png)

What's your favorite choice ?

**Comment by hqnghi88** [comment]
Dear Alexis
I prefer to suppress it. And give more dynamic to the definition of “parameter view”, may be just a “View” in which modeler can decide it will be some combinations of inputs/outputs

**Comment by lesquoyb** [comment]
I prefer choice 3, choice 1 would be acceptable too, but I feel like monitors are deeply linked to simulation parameters so there really is no need to separate them. Maybe we can add a foldable section for monitors in the parameter view
