### ISSUE TITLE
Accessing the circuit attribute of graphs throws NullPointerException

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3467]
**Describe the bug**
Using the `circuit` attribute of a graph raises a NullPointerException when running a model from Linux or macOS, the problem also happens in Windows but doesn't stop the model from running for some reason.

**To Reproduce**
Try to run this model:
```
/**
* Name: CircuitAttribute
* Based on the internal empty template. 
* Author: antonia
* Tags: 
*/
model CircuitAttribute

global {
	geometry shape <- rectangle(100, 100);

	init {
		create TestSpecies number: 1;
	}

}

species TestSpecies {
	graph dummy_graph <- spatial_graph([]);
	bool do_once <- true;

	reflex create_graph when: do_once = true {
		list<point> nodes <- [];
		add ({10, 50}) to: nodes;
		add ({75, 30}) to: nodes;
		add ({23, 71}) to: nodes;
		loop n over: nodes {
			dummy_graph <- dummy_graph add_node (n);
		}

		loop i from: 0 to: length(nodes) - 2 {
			loop j from: i + 1 to: length(nodes) - 1 {
				dummy_graph <- dummy_graph add_edge (dummy_graph.vertices[i]::dummy_graph.vertices[j]);
			}

		}

		write "Graph: " + dummy_graph;
		write "Graph Circuit: " + dummy_graph.circuit;
		do_once <- false;
	}

	aspect base {
		loop v over: dummy_graph.vertices {
			draw circle(2) at: v color: #green;
		}

		loop edges over: dummy_graph.edges {
			draw geometry(edges) color: #black;
		}

	}

}

experiment main type: gui {
	output {
		display display1 background: #grey {
			species TestSpecies aspect: base;
		}

	}

}
```

**Comment by lesquoyb** [comment]
I commited some changes in the `getCircuit` method, it seems to fix the problem but I'm not well versed in the graph module so I'd like someone else to double check it to make sure it didn't break anything else.
Also that piece of code, as it was previously written, should have never worked, so there are maybe more bugs to dig in the graphs code

**Comment by AlexisDrogoul** [comment]
I tested it and it seems to be correct. Maybe we should include it in the tests on graphs ?

**Comment by lesquoyb** [comment]
I'm not sure, what do you want to include and in which tests ?
