### ISSUE TITLE
Die in global species doesn't end simulation

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3470]
**Describe the bug**
When trying to stop (not pause) a simulation with a `do die;` in the global species it doesn't kill everything anymore, and the simulation somehow continue running. Also, if I try to call the global species' die action from another species, I'll get the same behaviour + in eclipse's console some java errors raised: `reportAndThrowIfNeeded : Agents stack is empty`

**To Reproduce**
```
model dietest

global {
	
	reflex dying when:cycle>10 {
		write "dying";
		do die;
	}
	
}

experiment a {}
```

The case where it's call from another species:
```
model dietest

global {
	
	init {
		create dummy number:1;
	}	
}

species dummy {
	
	reflex dying when:cycle>10 {
		write "dying";
		ask world {
			do die;			
		}
	}
}

experiment a {}
```

**Expected behavior**
`do die;` in the global species should end the simulation properly as described in the [documentation](https://gama-platform.org/wiki/next/GlobalSpecies#die)

**Comment by hqnghi88** [comment]
The simulation is dead, you can check in interactive console:
 
<img width="204" alt="image" src="https://user-images.githubusercontent.com/6105384/183612522-eb427395-74a8-46f0-a69b-d83c8eb52a05.png">

If you want it to stop (same as click on Red button), you should kill the experiment 
<img width="322" alt="image" src="https://user-images.githubusercontent.com/6105384/183612948-5094337f-9d3c-4dc3-b876-3042611326eb.png">

**Comment by lesquoyb** [comment]
Ho I see, I'll update the documentation to make it clearer then.
But what about the errors in java when die is called from another species ? It doesn't seem like normal behaviour to me (I actually stumbled upon those errors while using the "stop" command of gama-server btw)

**Comment by hqnghi88** [comment]
I agree that the error message is something not good. It come from the ask statement that insde you kill the simulation then everything will lost after that. But i cant figure out how to solve, may be a condition or restrucutre of ExecutionScope 
<img width="349" alt="image" src="https://user-images.githubusercontent.com/6105384/183639512-76f29ad7-b57c-4246-826e-f96c03e48d57.png">
@AlexisDrogoul any idea?

**Comment by AlexisDrogoul** [comment]
Well. Actually there should be nothing to worry about really. Just a scope ending up in a weird state while its top-level agent is begin killed. It is normally harmless.
