### ISSUE TITLE
Add a `continue` statement

### ISSUE THREAD

**Issue by minhduc0711** [gama-platform/gama.old#3472]
**Describe the improvement you'd like**
Many programming languages support the keyword `continue`, which is used in a loop to skip the rest of the code and move to the next iteration immediately. I personally find this keyword very useful when the branching logic inside the looped code gets a bit complicated.

**Describe alternatives you've considered**
I don't think that such a statement exists in GAMA yet.

**Additional context**
I'm happy to open a pull request for this, and I'd appreciate it if anyone can give me some pointers on where to start.

**Comment by AlexisDrogoul** [comment]
I implemented it. I use this occasion to refresh a bit the `break` statement too. I need to make a bit more tests, but it should be committed soon

**Comment by AlexisDrogoul** [comment]
We can safely consider this issue as "solved". Reopen if it is not the case.
