### ISSUE TITLE
Features tab in "Installation details..." is empty

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama.old#3473]
**Describe the bug**
When invoking "Installation details..." in the dialog that pops up when choosing the "About Gama" menu, the tab that should list the features is empty. 

![Gama (runtime) Installation Details 2022-08-12 00-34-33](https://user-images.githubusercontent.com/579256/184197457-f09c35c5-7f31-4654-9171-f3144d13ad9d.png)

When clicking on "Plugins", however, everything is there

![Gama (runtime) Installation Details 2022-08-12 00-36-27](https://user-images.githubusercontent.com/579256/184197614-2fe0cbb6-08ab-489f-b849-7ee71d2f153d.png)

**Expected behavior**
The features that compose the installation of GAMA should be displayed. This absence can also be verified when trying (like in #3468 ) to access the features present in GAMA in a programmatic way: the returned list is empty. 

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - PC Model: MBP 16" M1
 - GAMA version: git (with the support software installation checked : 

![Image 2022-08-12 00-39-26](https://user-images.githubusercontent.com/579256/184198127-0989da86-416a-4c38-9b92-c3f6fa35349e.png)

**Comment by AlexisDrogoul** [comment]
OK. By following https://www.java-forum.org/thema/installation-details-feature-tab-empty.94919/, and installing the "configurator" plugin mentioned in it, I was able to have some of the features listed (but not all):

![Gama (runtime) Installation Details 2022-08-12 00-51-27](https://user-images.githubusercontent.com/579256/184201789-760d23e3-d192-4dad-a31c-d33393c07068.png)

Especially, all the GAMA features are missing... !

**Comment by AlexisDrogoul** [comment]
The question is why only the Xtext-related features show up ? @RoiArthurB @hqnghi88 any idea ?

**Comment by RoiArthurB** [comment]
I'll give it a deeper look next week if not solved, but at first, I thought that while compiling we're overriding features by modules (then the feature are somewhat lost from the feature category).

But your last screenshot seems to come from Eclipse's runtime where some features are explicitly called... (`ummisco.gama.product/gama.runtime.product`, l.273-281)
```
   <features>
      <feature id="ummisco.gama.feature.dependencies" installMode="root"/>
      <feature id="ummisco.gama.feature.core.extensions" version="1.8.2.qualifier" installMode="root"/>
      <feature id="ummisco.gama.feature.core.ui" version="1.8.2.qualifier" installMode="root"/>
      <feature id="ummisco.gama.feature.core" version="1.8.2.qualifier" installMode="root"/>
      <feature id="ummisco.gama.feature.models" version="1.8.2.qualifier" installMode="root"/>
      <feature id="ummisco.gama.feature.experiment.ui" version="1.8.2.qualifier" installMode="root"/>
      <feature id="ummisco.gama.feature.modeling.ui" installMode="root"/>
   </features>
```

So I don't really know... Did you take a look on the compiled version? Maybe it's something that Eclipse doesn't generate only? 🤷

**Comment by hqnghi88** [comment]
https://www.eclipse.org/forums/index.php/t/94265/ 
It seems to be the naming convention problem. By adding update.configurator and change the name (ie ummisco.gama.feature.dependencies to msi.gama.ext , because the feature must contains a plugin with the same name)
i can get the feature "msi.gama.ext" (which was in fact ummisco.gama.feature.dependencies )
<img width="860" alt="image" src="https://user-images.githubusercontent.com/6105384/184429325-9598ac61-d44a-4129-8592-9f7e451bdaa4.png">

**Comment by AlexisDrogoul** [comment]
Ah right... It's probably that. A bit of a hassle, but it seems to be the only way to have features show up in the "Features" tab but also to gather the features in order to identify which one contains a given plug-in (see #3468).

My concern is also that its contradicts the purpose of designating the "branding plug-in" in a feature -- which is supposed to represent the plugin that contains `about.ini`, etc. 

![Image 2022-08-13 08-32-49](https://user-images.githubusercontent.com/579256/184463540-cdf961d9-88ba-4dd6-83c2-ac708b657454.png)

**Comment by hqnghi88** [comment]
Yes, you are right, branding plugin is the linkage can be use instead of naming convention
<img width="369" alt="image" src="https://user-images.githubusercontent.com/6105384/184478398-e5c2181c-be98-423a-b23d-0ef3a5ad9b5d.png">

<img width="653" alt="image" src="https://user-images.githubusercontent.com/6105384/184478357-a75ea92b-3e3f-4516-8adb-95712558c22b.png">

**Comment by AlexisDrogoul** [comment]
This doesn't work for me. I have a branding plugin but the about.ini and other information are not read... Wonder why ?

**Comment by hqnghi88** [comment]
I commit the change in all main feature in the product, the release show them in Feature Tab. I did not try about.ini, but have you the branding in Feature Tab yet?

**Comment by AlexisDrogoul** [comment]
Well. Doesn't work for me. Wirth `org.eclipse.update.configurator` installed, I can see (some?) Eclipse features, but none of the GAMA ones. Strange.

**Comment by AlexisDrogoul** [comment]
When I launch GAMA, I make sure the features are installed by using `p2` (a rather complicated way, but I havent found better): 

```java
	static Set<IInstallableUnit> findFeatures() throws ProvisionException {

		// 1. initialize necessary p2 services
		BundleContext ctx = FrameworkUtil.getBundle(GamaBundleLoader.class).getBundleContext();
		ServiceReference<IProvisioningAgentProvider> ref = ctx.getServiceReference(IProvisioningAgentProvider.class);

		IProvisioningAgentProvider agentProvider = ctx.getService(ref);

		String profileId = IProfileRegistry.SELF; // the profile id for the currently running system
		URI location = null; // the location for the currently running system is null

		IProvisioningAgent provisioningAgent = agentProvider.createAgent(location);
		IProfileRegistry profileRegistry =
				(IProfileRegistry) provisioningAgent.getService(IProfileRegistry.SERVICE_NAME);
		IProfile orofile = profileRegistry.getProfile(profileId);

		// 2. create a query (check QueryUtil for options)
		IQuery<IInstallableUnit> query = QueryUtil.createMatchQuery(ExpressionUtil.TRUE_EXPRESSION); // QueryUtil.createIUGroupQuery();

		// 3. perform query
		IQueryResult<IInstallableUnit> queryResult = orofile.query(query, null);
		for (IInstallableUnit feature : queryResult) {
			final String version = feature.getVersion().toString();
			final String featureId = feature.getId();
			if (featureId.contains("gama") || featureId.contains("gaml")) {
				DEBUG.LOG(DEBUG.PAD("> GAMA: Feature " + featureId, 45) + DEBUG.PAD("version", 15) + version);
			}
		}

		return queryResult.toSet();
	}
```

This gives me: 

```
> GAMA: Feature msi.gama.ext                 version        1.8.2.qualifier
> GAMA: Feature ummisco.gama.annotations     version        1.8.2.qualifier
> GAMA: Feature ummisco.gama.ui.experiment   version        1.8.2.qualifier
> GAMA: Feature ummisco.gama.java2d          version        1.8.2.qualifier
> GAMA: Feature ummisco.gama.ui.modeling     version        1.8.2.qualifier
> GAMA: Feature ummisco.gama.opengl          version        1.8.2.qualifier
> GAMA: Feature msi.gama.processor           version        1.8.2.qualifier
> GAMA: Feature ummisco.gaml.extensions.mathsversion        1.8.2.qualifier
> GAMA: Feature msi.gama.lang.gaml           version        1.8.2.qualifier
> GAMA: Feature ummisco.gaml.extensions.statsversion        1.8.2.qualifier
> GAMA: Feature ummisco.gama.ui.shared       version        1.8.2.qualifier
> GAMA: Feature msi.gama.models              version        1.8.2.qualifier
> GAMA: Feature msi.gaml.extensions.fipa     version        1.8.2.qualifier
> GAMA: Feature miat.gaml.extension.pedestrianversion        1.0.0.qualifier
> GAMA: Feature ummisco.gama.serialize       version        1.8.2.qualifier
> GAMA: Feature ummisco.gama.network         version        1.8.2.qualifier
> GAMA: Feature irit.gaml.extensions.databaseversion        1.8.2.qualifier
> GAMA: Feature simtools.gaml.extensions.physicsversion        1.8.2.qualifier
> GAMA: Feature ummisco.gama.ui.viewers      version        1.8.2.qualifier
> GAMA: Feature msi.gaml.architecture.simplebdiversion        1.8.2.qualifier
> GAMA: Feature ummisco.gama.ui.navigator    version        1.8.2.qualifier
> GAMA: Feature simtools.gaml.extensions.trafficversion        1.8.2.qualifier
> GAMA: Feature msi.gama.application         version        1.8.2.qualifier
> GAMA: Feature msi.gama.core                version        1.8.2.qualifier
> GAMA: Feature msi.gama.headless            version        1.8.2.qualifier
> GAMA: Feature espacedev.gaml.extensions.genstarversion        1.0.0.qualifier
```

But when I invoke "About GAMA" and "Installation details", the list I obtain is : 

<img width="382" alt="Gama (runtime) Installation Details 2022-08-19 16-43-51" src="https://user-images.githubusercontent.com/579256/185592223-98b861db-a6fa-46af-89f9-d6fd2f374e09.png">

**Comment by hqnghi88** [comment]
I will try soon on M1. But you are always in eclipse launch? The same for the release?

**Comment by AlexisDrogoul** [comment]
Funny. The latest release shows this : 

<img width="382" alt="Gama Installation Details 2022-08-19 18-59-05" src="https://user-images.githubusercontent.com/579256/185613908-01d1c8fb-cf34-410f-9945-4efc884e15e5.png">

So now I see some of the GAMA features (probably the ones you changed ?), but none of Eclipse :)
I'm curious to see if adding the about.ini with an icon works

**Comment by hqnghi88** [comment]
Yes same here. No eclipse’s ones. But it is relate with product? All these shown are explicitly in gama product. It is not all thing in plugin folder

**Comment by AlexisDrogoul** [comment]
I am in the process of adding "branding plugins" to the features, so that (1) we do not have to denaturate regular plugins to serve this role; (2) we can add icons + small explanation text to the features. 

Besides adding them to the features, is there anything else I should do @hqnghi88 @RoiArthurB ? 

<img width="187" alt="Eclipse Workspace for GAMA 1 8 2022-09-09 17-40-38" src="https://user-images.githubusercontent.com/579256/189332374-6322868b-39b6-49f9-a1ae-b0763092f2d2.png">


<img width="272" alt="About Gama 2022-09-09 17-38-34" src="https://user-images.githubusercontent.com/579256/189331902-e4c17fe0-9820-4328-8efa-daf0c3ec40f5.png">

**Comment by AlexisDrogoul** [comment]
OK. Following the commits (and some other changes), it seems to be working. The features are correctly listed in the latest release. Tested on macOS M1, does it work on Windows / Linux as well so that we can close this issue ? 

<img width="382" alt="Gama Installation Details 2022-09-13 18-08-44" src="https://user-images.githubusercontent.com/579256/189886343-5d5d250d-e9d0-4b34-86d9-bfaea9b8f509.png">

**Comment by hqnghi88** [comment]
It works on windows 11.
<img width="700" alt="image" src="https://user-images.githubusercontent.com/6105384/189940227-4e6287ef-b07b-4df6-aa1e-f4236ad0fc03.png">

**Comment by AlexisDrogoul** [comment]
Unless it wouldn't work (for mysterious reasons) on Linux, I consider this to be fixed.
