### ISSUE TITLE
Continuous integration breaking: presence of illegal characters in commit name ? 

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama.old#3477]
**Describe the bug**
One of the latest commit (https://github.com/gama-platform/gama/commit/fdacafd3e3cb45bf6c9bc893f05a4e008535a80b)  has made the continuous integration break (https://github.com/gama-platform/gama/runs/7937699639?check_suite_focus=true) but it doesn't seem to be because of Java / compilation / test problems, as the action breaks on : 

![Image 2022-08-21 16-23-00](https://user-images.githubusercontent.com/579256/185784476-7e95f3e5-88f6-4955-abd2-e1b708c60ae5.png)

Could it be due to illegal characters entered into the documentation of the commit ? Notice the `[` and `]` around `compilation`.

**Comment by AlexisDrogoul** [comment]
To be sure, I've added three new files to a new commit (https://github.com/gama-platform/gama/commit/9627a6d96358b86aa206485de3a45211683ed78d), where I did not use the `[` nor `]` characters. Everything went fine.

**Comment by RoiArthurB** [comment]
Hi, the problem comes from the double quote `"` not the brackets, I'll push a fix for it quickly :)

**Comment by RoiArthurB** [comment]
Fixed with b97bfcd2afe2c1446e274867b4d02788944e325d :)

Feel free to reopen if bug re-occurs

> Source : https://github.com/orgs/community/discussions/26736
