### ISSUE TITLE
Headless hpc memory leaks

### ISSUE THREAD

**Issue by Quittqick** [gama-platform/gama.old#3482]
**Describe the bug**
I'm trying to run COMOKIT model headless using xml files to run several experiments on a server. I need to use -hpc options to decrease the computing time. However when i use -hpc options the memory used increases much more than intended
I could reproduce the bug using the evacuation model of Gama.

**To Reproduce**
1. Download the Memory_test folder from this [drive](https://drive.google.com/file/d/1T35QvBpJurPZtBZDbvq21cN6q_B7wN4y/view?usp=sharing)
2. Unzip Memory_test
3. Run the following command : 
bash path_to/GAMA_1.8.2-RC2/headless/gama-headless.sh -m 10240m -hpc 1 Inputs/input-0.xml ./Outputs
5. Monitor memory usage (my maximum value is about 6Go - screenshot  1)
6. run  the following command : 
bash path_to/GAMA_1.8.2-RC2/headless/gama-headless.sh -m 102400m -hpc 5 Inputs/input-0.xml ./Outputs
7. Monitor memory usage (screenshot 2)
8. You should witness that the memory usage explodes

**Expected behavior**
Admitting that each experiment uses more or less the same amount of memory the memory used should stabilize around a maximum value. For example if one experiment uses about 6Go, 5 experiments shouldn't use much more than 30Go but it uses about 100Go.

**Screenshots**
Memory usage with -hpc 1 (first line pid 11523)
![HPC-1](https://user-images.githubusercontent.com/72378617/187630456-15a835d7-e8cf-4b60-b60b-d8f97c8f38cc.png)

Memory usage with -hpc 5 (first line pid 10981)
![HPC-5](https://user-images.githubusercontent.com/72378617/187630781-bb04b58a-3b7a-4e2f-8fc2-92ec5b80634d.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - PC Model: Dell precision tower 5810
 - GAMA version: 1.8.2-RC2
 - Java version: 17.0.1
 - Graphics cards / Display system: NVIDIA Corporation GK107GL [Quadro K420]

**Comment by Quittqick** [comment]
### Update:

I'm sorry, I noticed i made a mistake in my previous post. I mistyped the allocated memory with the -m conducing to give more memory than available that's why it wasn't working for the Evacuation model. Knowing that, I didn't manage to reproduce the bug using the Evacuation model. The actual result for the Evacuation model are in screenshots 1 and 2. 

Then I'll update my post to reproduce the bug with COMOKIT

**Describe the bug**
So I'm still trying to run COMOKIT headless with -hpc option to increase computing efficiency. However as the simulation runs the memory usage never stops increasing.

**To Reproduce**
Steps to reproduce the behavior:
Retrieve files:
1. Download COMOKIT.zip from this [drive](https://drive.google.com/file/d/1qn9Sw34S7kSfdhW9RKhs_Uppp5_yk1yI/view?usp=sharing)
2. Unzip the folder
3. Clone COMOKIT into the folder using
``` git clone https://github.com/COMOKIT/COMOKIT-Model.git ```
4. Generate xml file for the experiment using 
``` python3 GenerateXML_Sensitivity.py -s 1 -sample 32 -f 2232 -xml headless COMOKIT-Model/COMOKIT/Macro/Sensitivity_analysis/Sensitivity_experiments.gaml ./Inputs_COMOKIT/input.xml ```

With 1 core and 10Go RAM:
1. Run the command
``` bash path_to/GAMA_1.8.2-RC2/headless/gama-headless.sh -m 10240m -hpc 1 Inputs_COMOKIT/input-0.xml ./Outputs ```
2. Monitor memory usage (screenshot 3)

With 15 cores and 100Go RAM
1. Run the command
``` bash path_to/GAMA_1.8.2-RC2/headless/gama-headless.sh -m 102400m -hpc 15 Inputs_COMOKIT/input-0.xml ./Outputs ```
6. Monitor memory usage (screenshot 4)
7. You should witness that the memory usage goes over 100Go (it could be a bit slow as COMOKIT spends several minutes to run a single experiment)

In both case don't wait until the end of every experiment it would spend days.

**Expected behavior**
Admitting that each COMOKIT experiment uses more or less the same amount of memory the memory used should stabilize around a maximum value. For example if one experiment uses about 5Go, 15 experiments shouldn't use much more than 75Go but it uses more than 100Go.

**Screenshots**
Screenshot 1 : Evacuation model memory usage for hpc 1
![Evacuation_hpc1](https://user-images.githubusercontent.com/72378617/187704726-6f6168b2-6ba8-4c71-92ea-c8ad8289a5d2.png)
Screenshot 2 : Evacuation model memory usage for hpc 5
![Evacuation_hpc5](https://user-images.githubusercontent.com/72378617/187704721-465a7006-934f-415a-a04d-b9b334aeef76.png)
Screenshot 4 : COMOKIT model memory usage for hpc 1
![COMOKIT_hpc1](https://user-images.githubusercontent.com/72378617/187706469-a6fd2534-7144-417b-8760-6f7fdc1b10e6.png)
Screenshot 3 : COMOKIT model memory usage for hpc 15
![COMOKIT_hpc15](https://user-images.githubusercontent.com/72378617/187705012-2f4c68e5-1fc8-4663-84db-e2a776390a7d.png)

Desktop (please complete the following information):

-  OS: Ubuntu 21.10
- PC Model: Dell precision tower 5810
- GAMA version: 1.8.2-RC2
- Java version: 17.0.1
- Graphics cards / Display system: NVIDIA Corporation GK107GL [Quadro K420]

**Comment by AlexisDrogoul** [comment]
Hi,

I am not completely sure that I understand what the real issue is here. Is it the fact that headless COMOKIT experiments take too much memory compared to their counterparts in UI GAMA ? Or the fact that headless operations do not release the memory between two runs of experiments ? 

Alexis

**Comment by Quittqick** [comment]
Hello,

It seems like headless operation do not release the memory. I found a way to reproduce the issue with prey predator model of gama library.

## To reproduce:
1. Download : [Memory_issue.zip](https://github.com/gama-platform/gama/files/9597950/Memory_issue.zip)
2. Unzip **Memory_issue.zip**
3. Clone corresponding gama version inside **Memory_issue** : `git clone https://github.com/gama-platform/gama/`
4. Get the corresponding gama release version : [Alpha Version 1.8.2 (972c449b)](https://github.com/gama-platform/gama/releases/tag/1.8.2) and put it inside **Memory_issue**
5. Run `bash ./GAMA_1.8.2_Linux_with_JDK_09.16.22_972c449b/headless/gama-headless.sh -m 20480m -hpc 20 ./Inputs/input-0.xml ./Outputs` (change -m and -hpc options depending on your ressources)
6. Monitor the memory

To monitor the memory i'm using [YourKit](https://www.yourkit.com/java/profiler/download/). To start monitoring with YourKit you should add the option `-agentpath:/PATHTO/YourKit-JavaProfiler-2022.3/bin/linux-x86-64/libyjpagent.so=exceptions=disable,listen=all`to the **gama-headless.sh** script at line 47 when launching java application.

## Behavior
See in the section below that the memory is not completely released.

## Screenshots
You can find the results i get inside Memory_issue/profiling or below but you'll need to zoom in to see the evolution of the curve:
![Chart--Heap-memory](https://user-images.githubusercontent.com/72378617/190997555-a967d944-d89d-4022-852a-28633f35676e.png)
![legend](https://user-images.githubusercontent.com/72378617/190997567-a467dad7-2dfa-494a-945a-684995d2ea5f.png)


## Desktop (please complete the following information):
- OS: Ubuntu 21.10
- PC Model: Dell precision tower 5810
- GAMA version: Alpha Version 1.8.2 (972c449b)
- Java version: 17.0.1
- Graphics cards / Display system: NVIDIA Corporation GK107GL [Quadro K420]

**Comment by AlexisDrogoul** [comment]
@Quittqick since you used YourKit, have you been able to take a snapshot, so as to have a complete map of the instances present in memory ?

**Comment by Quittqick** [comment]
@AlexisDrogoul You can find the snapshot inside Memory_issue > tmp > profiling of the previous post.

**Comment by AlexisDrogoul** [comment]
@Quittqick the snapshot is only a simple one. It does not contain any information about the object allocations, for instance.

**Comment by AlexisDrogoul** [comment]
@Quittqick did you have a chance to test the new alpha releases ?

**Comment by RoiArthurB** [comment]
I spoke with @chapuisk who was managing @Quittqick working on this for an internship. There's no follow-up to expect for this issue so far...

If anyone is founding / digging this issue any further; feel free to reopen it :)
