### ISSUE TITLE
[Batch] batch experiment from tutorial Predator Prey runs silently into errors

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama.old#3486]
**Describe the bug**
When dealing with batch experiment on a model of the library, i.e. predator prey ``model 13.gaml``, the execution slow drastically at some random number of replicates (optimization method). But there is no error message, but simulations get very slow and experiment never ends. I tried with git version and got an error from eclipse (which is not a Gama error) but I cannot find any good explanation to it.

**To Reproduce**
1. Go to Tutorials > Predator Prey > models > Model 13.gaml
2. Click on ``Optimization``
4. See (no) error but experiment plan stuck 

**Expected behavior**
The simulation plan should run to the end or at least throw an explicit exception

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - GAMA version: 1.8.2RC2 and 1.8.2 git version
 - Java version: 17

**Additional context**
I tried with several other methods involving batch experiment and runs into the same error, not being able to identify why it is happening

**Comment by AlexisDrogoul** [comment]
I cannot reproduce it in the git version (between 110 and 144 simulations in ~30s each time). What error do you get ?

**Comment by chapuisk** [comment]
Here is the stack trace of the error launch in eclipse (not in Gama). 

![Screen Shot 2022-09-14 at 14 22 41 (2)](https://user-images.githubusercontent.com/13599506/190153155-1250192a-5564-4b06-bdec-d5353d1108fb.png)

By the way, I have been able to reproduce it in 1.8.2 RC1 and RC2, and with the git version (from which I took the capture of eclipse )

**Comment by chapuisk** [comment]
Ok @AlexisDrogoul, I may have misunderstood what's going on. It seems that simulations are running, but Gama is glitching (parameter windows blinks and the display of simulations running update every n simulations or show nothing). It may not impair the experiments and simulation but outputs are broken, and eclipse have an error.

**Comment by AlexisDrogoul** [comment]
I do not get this error. Can you show me your preferences related to `Execution` ?

**Comment by chapuisk** [comment]
Here is the ``execution`` parameters of Gama for the git version; while for the RC2 version there are at default values (nothing has been changed, I even rebuild and redownload everything to do the tests)

<img width="1048" alt="Screen Shot 2022-09-15 at 12 14 31" src="https://user-images.githubusercontent.com/13599506/190378577-8dc5655b-d2a7-4ff5-933d-4026dc588e56.png">

**Comment by AlexisDrogoul** [comment]
Hum. I can't reproduce the error event after adopting your preferences (not too different from mine btw). Anything else you might have changed in your own installation of GAMA ? Do all the batch models produce the same errors ?

**Comment by AlexisDrogoul** [comment]
@ptaillandier do you observe the same behaviour ?

**Comment by AlexisDrogoul** [comment]
Any hint on how to reproduce this bug ? I can't do it and I really dont see where it comes from...

**Comment by chapuisk** [comment]
@AlexisDrogoul I'll try few things today to reproduce more consistently, but the fact that it happened using batch makes it quite hard to fix all conditions... if I fail, I'll close the issue

**Comment by ptaillandier** [comment]
I tested once and I had no errors.

Le lun. 19 sept. 2022 à 15:28, Alexis Drogoul ***@***.***> a
écrit :
