### ISSUE TITLE
GAMA Git Version under Eclipse 2022-09 (4.25) on macOS cannot read existing workspaces

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama.old#3489]
**Describe the bug**
When compiling and launching GAMA git version (i.e. developer version) using Eclipse 2022-09 (aka 4.25), opening an existing GAMA workspace generates lots of errors (esp. "Operation not permitted" errors on metadata Eclipse files) and ends up in a non-functional GAMA instance. 

**To Reproduce**
1. Download Eclipse 2022-09 (https://www.eclipse.org/downloads/packages/release/2022-09/r/eclipse-ide-java-and-dsl-developers)
2. Run it on the same workspace than Eclipse 2022-03 or 2022-06 
3. Run `gama.runtime.product`
4. See errors appearing in the console 

**Expected behavior**
The same behaviour than the two previous versions of Eclipse, i.e. no error. 

**Workaround**
There are two workarounds. 
This behaviour does not manifest when creating a new workspace with this version. So the first is to create a new workspace and import the projects from the old one.
The behaviour can also be avoided by giving Eclipse 2022-09 a full disk access from within System Preferences. When done, this version of Eclipse (and the instance of GAMA) behaves normally with old workspaces.

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.5.1
 - PC Model: MBP 16" M1
 - GAMA version: 1.8.2 git
 - Java version: Temurin-17.0.2+8

**Comment by hqnghi88** [comment]
Hi, It occurs also on Macos Ventura 13 beta 11 (m1).
