### ISSUE TITLE
Trouble with a "break" statement in the last "match" of a "switch"

### ISSUE THREAD

**Issue by hu1909** [gama-platform/gama.old#3499]
**Describe the bug**
Hi, everyone. Last time, I opened an issue about the bug related to the GAMA display but my boss figured out that the problem did not come from the display. He reviewed my code and found that the "break" statement that I used in some blocks of my code not only escaped my code but also broke my model. So that is why my model froze after I changed into the Pollution mode. 

**To Reproduce**
To have a clear understanding, You can clone HoanKiem Air Android with the "main" branch in this [link](https://github.com/WARMTeam/HoanKiemAir_Android)

**Comment by AlexisDrogoul** [comment]
This bug report is not understandable.

Fortunately, I could reproduce it with a small model. 

```gaml
model NewModel2


global {
	reflex {	
		switch (flip(0.5) ? 10:11) {	
			match (10) {
				write "matching 10";
				break;
			}
			match (11) {
				write "matching 11";
				break;
			}
		}
	}
}

experiment "a";
```

Running it makes the models stop working after the first time it matches `11`.
