### ISSUE TITLE
Cannot install Plugin in GAMA

### ISSUE THREAD

**Issue by ttrungtin2910** [gama-platform/gama.old#3505]
### Steps to reproduce
Following the documentation of GAMA version 1.8.1, I cannot install plugin:

1/ Quickimage: http://manu26.manufrog.com/~psnetnu/eclipse/updates/

2/ RSS/Atom Feed View:
http://www.junginger.biz/eclipse/

3/CKEditor
https://kosz.bitbucket.io/eclipse-ckeditor/update-site

4/Startexplorer
http://basti1302.github.com/startexplorer/update/

5/Pathtools
http://cdn.rawgit.com/sandipchitale/pathtools/1.0.64/PathToolsUpdateSite/site.xml

Please help me

### Expected behavior
Tell us what should happen (include all relevant expectations)

### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)

**Comment by RoiArthurB** [comment]
Hello @tintranrynan ,

Unfortunately, most of those plugins are abandoned by their developers (most of them are not updated for at least 5 years), and this part of the documentation was not updated for a while neither. I changed it for next versions documentation, thanks for pointing it out.

However, if you want to install plugins in the GAMA Platform, this procedure of using `updates` URL is still valid (as long as you're using not-abandoned projects) and most of Eclipse's plugins _should be_ compatible (we can't test them all however).

**Comment by ttrungtin2910** [comment]
Thank you for your help
