### ISSUE TITLE
The step back function is not working on some models from the library

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3509]
**Describe the bug**
The step back function is failing silently on the models from `Library Models` using the `Memorize Experiment.gaml`. Nothing happens when clicking the button, we can continue with a next step or play, and no exception is written in eclipse console. The button is working correctly on other experiments like `Test - Memorize Experiment - keep_seed.gaml`

**To Reproduce**
1. run `Memorize Experiment.gaml`
2. click play or step a few times
3. click on step back
4. nothing happens

**Expected behavior**
the experiment steps back.

**Comment by benoitgaudou** [comment]
Hi,
Could check again. I am not able to reproduce the issue on the model `Memorize Experiment.gaml`.
After several steps, the step button makes the simulation steps bakc...

**Comment by lesquoyb** [comment]
Tried again on windows and linux and unable to reproduce it too, maybe a side effect of some other fix
