### ISSUE TITLE
In memorize experiments, charts start at the wrong x coordinate when going back to init step

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3510]
**Describe the bug**
If you run an experiment of type memorize with one of the display being a chart where the x axis represents the time (cycle) and y any data, going back to the initial step breaks the chart: a first data point is inserted at a time (cycle) of 1, then the data point that is supposed to represent the initial state will be appended  at time 2 while it should be at time 0. this results in an offset of 2 on the chart.

**To Reproduce**
1. Run the model `Test - Memorize experiment - keep seed.gaml`
2. execute a few steps
3. click on `step back` until you go back to the initial step
4. the chart should already be broken but you can run a few steps to check that the two lines are identical apart from the initialization

**Expected behavior**
The initial data point is at time 0

**Screenshots**
For example here I ran the model on 10 cycles, back to cycle 0 then ran 10 steps and we can see clearly the offset:
![image](https://user-images.githubusercontent.com/6374469/196138413-086072fa-e79f-436b-ba5c-3f7083709960.png)
Just to be sure I wrote in the console the cycle and the random values used to generate the line, and we can see that they are the same for every cycle so it's just a display problem:
![image](https://user-images.githubusercontent.com/6374469/196139096-3235a0bb-1178-4bfa-8b25-2e6625c285e7.png)

**Comment by benoitgaudou** [comment]
The issue came mainly from the canStepBack() method of the ExperimentBackward.
Given the fact that I am not able to properly synchronize the disablement of the stepBack button with the actual state of the simulation (whether it can be step back or not), I choose to let the stepBack button always enable.
