### ISSUE TITLE
Cycles in status are confusing in memorize experiments

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3511]
**Is your request related to a problem? Please describe.**
When running an experiment, the status bar on the top left side of the screen prints "Experiment: X cycles elapsed". While in the general case it's fine, with experiments of type memorize it would be more helpful to give the current cycle instead of the total of cycles elapsed.

**Comment by AlexisDrogoul** [comment]
Hi @lesquoyb, I'm not sure I understand this issue. As a matter of fact, the number of cycles done in an experiment does not need to be the same as the number of cycles done in each of the simulations it hosts. In the case you mention, the "memorisation" applies to the current simulation (and you can observe its "elapsed cycles" evolve according to the commands), but it does not apply to the experiment itself : each time you ask the simulation to move backward is considered as a cycle forward for the experiment (ie. if you step forward 12 times and step backward 12 times, your experiment will have done 24 cycles, while your simulation will have done 0 cycle).

**Comment by lesquoyb** [comment]
Yes, I think I got confused between simulation and experiment cycles for some reason.
Just to be clear though: backward steps are not counted as elapsed cycles anywhere, but the "same" cycle can be counted multiple times if you go back to it and run it again.
