### ISSUE TITLE
Creating agents from shapefiles with invalid geometries does not raise any error

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama.old#3514]
**Describe the bug**
When I want to create agents from a shapefile with invalid geometries, no agents are created. But the main issue that GAMA remains silent: no warning or error message appears.

**To Reproduce**
1. As an example of model:
```
global {
	shape_file testValidesZF0_shape_file <- shape_file("../external/SECTEUR_EMD2013.shp");
	geometry shape <- envelope(testValidesZF0_shape_file);
	
	init {
		create zf from: testValidesZF0_shape_file;
	}
}

species zf { }

experiment name type: gui {
	output {
		display "My display" { 
			species zf;
		}
	}
}
```
3. As an example of dataset:
[ZF.zip](https://github.com/gama-platform/gama/files/9824401/ZF.zip)

5. Scroll down to '....'
6. See error

**Expected behavior**
Raising an error is expected.

**Desktop (please complete the following information):**
 - OS:macOS Monterey
 - GAMA version:git
 - Java version:17 Temurin

**Comment by AlexisDrogoul** [comment]
Hum... I can't reproduce it with the dataset you are providing. 

<img width="717" alt="Newt Window 2022-10-20 08-28-12" src="https://user-images.githubusercontent.com/579256/196834701-253c0378-05d8-4d3f-8467-8ba43cafbade.png">


All the agents seem to be created without problems. Are you sure it is the correct dataset (the filenames do not match with your example model).

**Comment by benoitgaudou** [comment]
Thanks for testing it... and I admit that I am not able to reproduce it either after a good night ...
The only thing I was able to get my issue is when (i) the file extension is .SHP (and not .shp) and that (ii) I drag and drop the file in my model, I get this line:
```
	file IRIS_GE0_file <- file("../external/IRIS_GE.SHP");
```
in this case no zf agent is created.

If I change manually the type of file reading operator, agents are correctly created:
```
	file IRIS_GE0_file <- shape_file("../external/IRIS_GE.SHP");
```
