### ISSUE TITLE
[GRAPH] generating a complete graph with 1000 nodes crushes default memory usage in Gama

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama.old#3516]
**Describe the bug**
Generating even small graph in Gama takes a tremendous amount of computational power. Tested with Library model that features graph, default setup and 1000 nodes makes Gama crash after having used more than 4Go of RAM

**To Reproduce**
1. Go to Library Model > Data Type and Structure > Graph.gaml 
2. increase number of node (line 12) to 1000 for instance
3. Run the model with 4Go of RAM allowed

**Expected behavior**
At least be able to build a graph of 1000 nodes with 4Go of RAM. More generally, **Graphs in Gama are bad**. _I suggest to build a group of issue in order to collect all needs and issues related to them_. For instance, there is no example on how to use ``as_edge_graph`` operator (which also has poor documentation). Another thing is that there is to many ways to build graphs, without any clear guidance. Furthermore, there is no simple way to build a network of agents, other than spatial (which are broken as shown by this issue).

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - GAMA version: git 1.8.2

**Comment by AlexisDrogoul** [comment]
You are generating a complete graph: actually, in addition to the 1000 `builtin_node` agents you are creating, you actually generate 1 000 000 (1000 x 1000) more `builtin_edge` agents, since the action `related_to` in `builtin_node` always returns true. This probably explains the memory usage.

**Comment by benoitgaudou** [comment]
Just tested an aspatial (without any species for edge and nodes) complete graph with 1000 nodes:
Nodes = 1000
Edges = 999000
Time to generate it = 1378.0

Nevertheless when I moved to complete graph of 10 000 nodes, it gets above the 4BG of memory.

In addition, I have the feeling that the graph objects are still in memory even after I close the simulation... To be tested...

**Comment by AlexisDrogoul** [comment]
I will close this issue, as I think it could be interesting to open a new one based on actual measures of the memory used (and retained ?) by graphs -- there are actually a number of places where potential memory leaks can occur in the current implementation. @chapuisk @benoitgaudou do not hesitate to open a new issue on this !
