### ISSUE TITLE
[GRAPH] shortest path operators raise error with non spatial graph

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama.old#3518]
**Describe the bug**
``load_shortest_paths`` and ``path_between`` operators cannot be fed with non spatial graph; the first one rais a NPE, while the other one try to access to a nul agent (non spatial graph have null node and edge,  which explains the error)

**To Reproduce**
1. Go to Library models > Data Types And Structures > Graph.gaml
2. Remove the as_spatial_graph on any generator
3. Launch model and generate a graph with the previously modified generator
4. Click on "Path with graph"
5. See error

**A clear and concise description of what you expected to happen.**
Be able to compute shortest path with spatial and non-spatial graphs 

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git 1.8.2

**Comment by benoitgaudou** [comment]
@chapuisk I attempt to solve this issue. Please test and and confirm it works as you expected, and whether it covers all the cases.

**Comment by chapuisk** [comment]
hey @benoitgaudou, Thx having a look (I'll try too sometime soon). I tried with the model library Graph.gaml, choose Random generator, with ``bool no_species <- true``, 1000 nodes and removing the ``as_spatial_graph`` operator (line 60).   I have an error when launching "Path with graph":

<img width="757" alt="Screen Shot 2022-10-24 at 10 13 44" src="https://user-images.githubusercontent.com/13599506/197479346-a39dcff5-f978-4ae7-8cad-b9c2e650d6a9.png">

I'll try with a model of mine and I'll give other feedbacks. 

Ps: I forgot to mention that the original model start by building a graph from built_in species, which crash the RAM (8Go), if you change directly the parameter in the model before launching it, or when you select options with built_in species and graph of more or less 1000 agents.

**Comment by chapuisk** [comment]
I tried to sum up what I want to do in a very synthetic model:

```
global {
	
	int nb <- 100;
	
	matrix distmatrix <- {nb,nb} matrix_with 0.0;
	
	init {
		
		create dumm number:nb; 
		
		graph g <- generate_watts_strogatz(nb,0.03,4,false);
		
		ask dumm {
			loop nei over: g neighbors_of g.vertices[int(self)] { 
				neighbours <+ dumm[int(nei)];
			}
		}
		
		dumm d <- any(dumm);
		write d.neighbours;
		
		ask any(dumm) {
			loop i over:dumm-self {
				unknown anyi <- g.vertices[int(self)];
				unknown iv <-  g.vertices[int(i)];
				distmatrix[int(i),int(self)] <- (g path_between (iv,anyi)).distance;
			}
		}
		
		write distmatrix;
	
}

species dumm {
	list<dumm> neighbours;
}

experiment xp {}
```

Basically, I want to use the generator to have the network and transfer everything I need as agent attributes (simpler to manipulate, no need to use operators to query the network): i.e. the neighbors at degree 1 and the matrix of shortest path distance between all agent.

[EDIT] => the path_between operator works with non spatial graph, as seen in the example !

Ps: the ``load_shortest_path`` operator is really meant to be used in traffic modeling, to actually follow a path from node to node; the resulting matrix only give the next predecessor in the shortest path.

**Comment by benoitgaudou** [comment]
Hi @chapuisk ,
Sorry but I am a little bit lost in your issue (as you seemed to edit it :-) ).
Is there still an issue and what is it ?

**Comment by chapuisk** [comment]
Hey @benoitgaudou,
I close the issue, as non spatial graph now can be input in shortest path operator. However, there is still question on the usability of such operator. Here is some benchmark on distance matrix (the length of the shortest path between all pairs of nodes):

On average tooks 0.1993s to build a distance matrix from graph
Nodes = 100 | Edges = 200 | Degree = 4.0 | Connected component(s) = 1

On average tooks 1.24255s to build a distance matrix from graph
Nodes = 200 | Edges = 400 | Degree = 4.0 | Connected component(s) = 1

On average tooks 14.3006s to build a distance matrix from graph
Nodes = 500 | Edges = 1000 | Degree = 4.0 | Connected component(s) = 1

On average tooks 100.35105000000001s to build a distance matrix from graph
Nodes = 1000 | Edges = 2000 | Degree = 4.0 | Connected component(s) = 1

We can see that computing all shortest path is really time consuming for small network (1000 nodes).

**Comment by benoitgaudou** [comment]
Perhaps you can add an enhancement on this point, so we can keep track on
it.

cheers

Benoit

Le ven. 4 nov. 2022 à 17:45, Kevin Chapuis ***@***.***> a
écrit :
