### ISSUE TITLE
Would like to better specify graphical outputs layout

### ISSUE THREAD

**Issue by fredmcelwee** [gama-platform/gama.old#3520]
I would like to have more flexibility in the layout of my graphical outputs to be able to have an option in between #split and #stack. For example, suppose I want to display 6 outputs (numbered 0,1,2,3,4,5) such that, by default, displays 0 and 1 appear on the left half of the screen, display 2 appears on the top-tight corner, and displays 3-5 appear as (stacked) tabs on the bottom-right side of the screen (with display 3 as the default, but allowing you to switch tabs to displays 4/5 in that bottom-right corner).  I have not figured out a way to 'combine' the layout options to achieve this.

The closest I have found is the example at the bottom of the [layout statement documentation](https://gama-platform.org/wiki/Statements#layout): 

`layout horizontal([vertical([0::5000,1::5000])::5000,vertical([2::5000,3::5000])::5000]) tabs: false;`

However, playing around with this, it is possible to achieve combination of #split and #stack, but I cannot figure out how to specify exactly which displays you want to be located where and which are stacked in a certain region. For example, using: `layout horizontal([vertical([0::5000,1::5000])::5000,vertical([2::5000, 3::5000])::5000]) tabs: true;`, 4 and 5 (i.e. those not specified) show as stacked on the lefthand side of the screen, with the others which are specified split into four on the right side of the screen. It would be nice to be able to say: `layout horizontal([vertical([0::5000,1::5000])::5000,vertical([2::5000, [3,4,5]::5000])::5000]) tabs: true;` and have [3,4,5] show as stacked in the bottom-right corner with 3 as the default, but that does not work.

**Comment by AlexisDrogoul** [comment]
Interesting enhancement. I'll try to have a look ! 

[EDIT] So interesting that it already exists, but with a different syntax, using the `stack` operator. In your example, it would be:

`horizontal([vertical([0::5000,1::5000])::5000,vertical([2::5000, stack([3,4,5])::5000])::5000]) tabs: true;`

**Comment by AlexisDrogoul** [comment]
The best way to create these combinations if by using the `Copy layout to clipboard` menu item

![Image 2022-12-03 14-34-14](https://user-images.githubusercontent.com/579256/205430276-09ffcce1-8b4d-428a-a3da-73e51689cde5.png)


There was however an error in the way stacks were computed (they were incorrectly passed a map as an argument, while `stack` is expecting a list of indices). I've fixed this in the latest commit. Otherwise, you can correct it manually after it has been pasted in your model.
