### ISSUE TITLE
Do action in Interaction

### ISSUE THREAD

**Issue by ttrungtin2910** [gama-platform/gama.old#3521]
I'm a newbie in GAMA
I write some examples with GAMA
I can do action in species self, but I can't do that in species myself. please help me. Some code right here

```

model NewModel

global{
	init{
		create speciesA;
		create speciesB;
		
		ask speciesA{
			ask speciesB{
				do doSomethingSpeciesB;
				do doSomethingSpeciesA;
			}
		}
	}
}

species speciesA{
	action doSomethingSpeciesA{
	}
}


species speciesB{
	action doSomethingSpeciesB{
		
	}
}

```

Please help me, thanks

**Comment by benoitgaudou** [comment]
Dear

Basically, if your are not in the execution context of a species, but you
want that the agents of this species execute one of their actions, you need
to ask them to do it : ask species { do an_action;}

So in you example, you will need to right another ask speciesA in your ask
speciesB.

Note that in your case, the ask speciesA could be reviewed : perhaps you do
not need it.

Cheers

Benoît

Le lun. 31 oct. 2022 à 03:41, tintranrynan ***@***.***> a
écrit :

**Comment by ttrungtin2910** [comment]
Thanks your answer
