### ISSUE TITLE
IndexOutOfBoundsException when creating agents from a shapefile

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama.old#3525]
**Describe the bug**
I get a shapefile and simply want to create agents from it: `create ecole from: ecoles;`

I get the following error:
```
1 occurence in Simulation 0 at cycle 0: Java error: index out of bounds
in create ecole from: ecoles ;
IndexOutOfBoundsException: Index 448 out of bounds for length 448
java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
java.base/java.util.Objects.checkIndex(Objects.java:359)
java.base/java.util.ArrayList.get(ArrayList.java:427)
msi.gama.util.IList.get(IList.java:370)
msi.gama.util.GamaList.get(GamaList.java:1)
in agent Simulation 0
```

Basically my shapefiles contains 449 objects, but GAMA seems to be able to load only 448 (seems that one of them has a null geometry).

**To Reproduce**
1. Import the following project: [TestShapefiles.zip](https://github.com/gama-platform/gama/files/9919925/TestShapefiles.zip)
2. run the model.

Note that, I check the validity of the shapefile using QGIS, and do not get any invalid geometries.

**Desktop (please complete the following information):**
 - OS: macOS Mondeley
 - GAMA version: git
 - Java version: 17

**Comment by AlexisDrogoul** [comment]
One of your geometries is indeed considered as invalid by GAMA (actually not invalid but `nil` -- this is geometry 359). The error comes from the fact that the computation of the length of the shape file (ie number of geometries contained in it, but not tested for validity in GAMA) is separated from the loading of these geometries into shapes (where they are tested for validity in GAMA). By deactivating this "feature", everything works normally. I think it is safe to fix the issue that way, as the only drawback would be a little bit more time spent when computing the length of a shape file as we have to create the shapes (but it is rare to compute the length without loading the shapes afterwards anyway).
