### ISSUE TITLE
On windows in the latest release gama opens along a console

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3528]
**Describe the bug**
After installing the latest gama release, when I run the program from the shortcut, a console is visible (with the DEBUG.OUT printed).
If I close the console gama closes too.

**To Reproduce**
1. Download the latest (alpha) release's installer for windows
2. install it
3. run gama from the created shortcut

**Expected behavior**
Gama starts without the console, as usual

**Screenshots**
![image](https://user-images.githubusercontent.com/6374469/199933282-071d5da6-d0cf-4b8a-a66a-973325ae4c9e.png)
![image](https://user-images.githubusercontent.com/6374469/199933615-225fae07-03f3-4e91-b691-1d8eb26b2e7b.png)

**Additional context**
If we find a way, it can be a helpful tool to have that console showing only when asked (set in the preferences) to help debug certain users.

**Comment by hqnghi88** [comment]
See #2499

**Comment by AlexisDrogoul** [comment]
Do we have a fix for this (like in #2499) ? Is it related ?

**Comment by lesquoyb** [comment]
The same fix provided by @hqnghi88 in #2499 works locally.
I'm just wondering how it appeared in the first place because I don't see any changes directly related to this in the commits before the last alpha release. Maybe @RoiArthurB has an idea

**Comment by hqnghi88** [comment]
It should be in gama.ini where the building installer 's script was wrong in import/replace
