### ISSUE TITLE
depth facet for lines does not work as intended

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama.old#3537]
**Describe the bug**
draw a line, add a depth facet. It draws a cylinder instead of a plan (as indicated in the help).

**To Reproduce**

![image](https://user-images.githubusercontent.com/18676913/204255215-fde4308b-136d-43af-9b24-0f8f3c475a0b.png)

````
model debug

global{
	init{		
		create lines;
	}
}


species lines{
	aspect base{		
			draw  line([{30,30,0},{70,30,0}]) color: #green;	
			draw  line([{30,70,0},{70,70,0}]) color: #red depth: 10;
	}
}


experiment "Show error" type:gui{
	
	output {
		display Lines type: opengl{
			species lines aspect: base;
		}
	}
}
````

**Expected behavior**
the red objet should be a vertical plan.

 - OS: Windows 10
 - GAMA version: 1.8.2

**Comment by AlexisDrogoul** [comment]
Should we draw a plan or a cylinder ? 🤔

**Comment by AlexisDrogoul** [comment]
I would be willing to close this issue and -- instead -- correct the documentation.

**Comment by tnguyenh** [comment]
I guess a plan should be better, as depth is more like a vertical extrusion... I think it would be more consistent with other geometries. Anyway I'm fine with your solution.

**Comment by tnguyenh** [comment]
After discussing with @ptaillandier, we think that it is better to have a vertical rectangle than a cylinder.

**Comment by AlexisDrogoul** [comment]
So I let you implement it 🙂 -- and also verify that the example models in the library are still ok. It is not a big deal but I have other priorities right now.

**Comment by agrignard** [comment]
Maybe this can be added in the model library ```Built-In Shapes.gaml``` which is now not showing the ```depth``` feature but juts how the geometry are drawn

This is what we have so far
<img width="1118" alt="Screenshot 2022-12-09 at 07 58 02" src="https://user-images.githubusercontent.com/3928502/206643753-abcaab23-ca99-402f-aa3c-cdba46b46f48.png">

**Comment by ptaillandier** [comment]
I changed the default behavior of depth for lines and added a simple example model
