### ISSUE TITLE
lines and rectangle height is not consistent with grid and 3D objects height

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama.old#3538]
**Describe the bug**

When specifying height for a line (or a rectangle), the height is not consistent with other objects. For example, when drawing a grid (which I assume is at height 0), a line or a rectangle at height 0 seems to be hovering over the grid. When drawing a box with height z, a line at height z is hovering over the box.

However the box position seems to be consistent with the grid (not hovering).

![image](https://user-images.githubusercontent.com/18676913/204262266-832ee9e3-10f5-4903-9085-109caa334446.png)

![image](https://user-images.githubusercontent.com/18676913/204262507-4e328619-25a0-4720-a0b9-db1f4b49be9a.png)

**To Reproduce**
````
model debugPosition

global{
	float z_shift <- -0.0;//-0.05 to align green lines, - 0.02 to align red lines, -0.035 to align orange rectangle.
	int z_box <- 50;

	init{		
		create objects;
	}
}

species objects{
	aspect base{
			draw box(10,10,10) at: {45,45,0} border: #blue wireframe:true;
			draw line([{30,50,0+z_shift},{60,50,0+z_shift}]) color: #red;
			draw line([{30,50,10+z_shift},{60,50,10+z_shift}]) color: #orange;
			draw line([{50,40,10+z_shift},{60,40,10+z_shift}]) color: #orange;
			
			draw rectangle(10,10) color: #green at: {25,25,z_shift};
			draw box(10,10,10) at: {45,25} color: #green;
			
			draw box(10,10,10) at: {45,45, z_box} border: #blue wireframe:true;
			draw line([{30,50,0+z_box+10+z_shift},{60,50,0+z_box+10+z_shift}]) color: #orange;
	}
}

grid Grid cell_width:10 cell_height:10{
}

experiment "Show error" type:gui{
	
	output {
		display Positions type: opengl{
			grid Grid border:#black;
			species objects aspect: base;
		}
	}
}
````
In this model, the green rectangle is hovering over the grid, as well as the red line. The orange lines are hovering over the wireframe cube.

 - OS: win 10
 - GAMA version: 1.8.2

**Additional context**
I thought that might be related to opengl not being able to draw to objects at the same position. However if we add a vertical offset z_shift in the previous model, we can get the lines and rectangle at the right position. The offset values for the objets at height 0 or height >0 are not the same, and shown as comment in the model.

**Comment by AlexisDrogoul** [comment]
This is an effect of the z-fighting algorithm used in the OpenGL pipeline of GAMA. The best I can do, I guess, is to add a preference to use (or not) this algorithm...

**Comment by AlexisDrogoul** [comment]
I have added a preference to enable or disable the automated z-fighting mechanism : 

<img width="428" alt="Monosnap 2022-12-17 19-00-08" src="https://user-images.githubusercontent.com/579256/208255194-08b92288-2354-4265-8667-6b0791c95345.png">

The results are not so great when drawing things at the same altitude, but at least the shift doesn't appear anymore.
