### ISSUE TITLE
Optimization batches experiment stop after only 3 runs

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama.old#3543]
Use batch to compute an optimal set of parameters (eg hill climbing). It tests only three sets of parameters then stop, far from the optimal solution.

Use the following code:

````

model batch_example

global {
    float x <- 0.0;
	float objective <- 0.0;
	
	init {
		objective <- abs(x^2 - 2);
    }

	
	reflex write_info   {
		write "x: "+x+" objective: "+objective;
	}
}



experiment Simple type:gui {
	parameter 'x:' var: x;
}


experiment Hill_Climbing type: batch  until: ( time > 0 ) {
	parameter 'x' var: x min: 0.0 max:10.0 step:0.01;
	method hill_climbing minimize: objective iter_max: 100;
}

experiment Simulated_annealing type: batch  until: ( time > 0 ) {
	parameter 'x' var: x min: 0.0 max:10.0 step:0.01;
	method annealing  minimize: objective temp_decrease: 0.5 temp_end: 10.0 temp_init: 50;
}
````

The optimal solution is sqrt(2)= 1.44..., for objective=0.

![image](https://user-images.githubusercontent.com/18676913/205602471-c7eb1135-ec81-4e81-843b-e557578f38e0.png)

The problem seems to hold with other methods, but not the same number of iteration (eg it's 5 for simulated annealing)

gama 1.8.2
windows 10

**Comment by tnguyenh** [comment]
Maybe something related to step ? If I remove the method line 

````
experiment Hill_Climbing type: batch repeat: 1  until: ( time > 0 ) {
	parameter 'x' var: x min: 0.0 max: 7.0 step: 1;
	//method hill_climbing minimize: objective iter_max: 100;
}
````

the step used is 0.7 and not 1...

**Comment by AlexisDrogoul** [comment]
@chapuisk, it is (at least partially) the consequence of commit https://github.com/gama-platform/gama/commit/06dd02ec6f759c599a47e2ba639f0d1743ecbc52 . It works before, but not after... Can you check ?

**Comment by chapuisk** [comment]
@tnguyenh There is no issue related to simulated annealing algorithm: the temp_decrease facet is a multiplicative factor of the temperature of the system, meaning that for each iteration temperature will be multiplied by this factor. With a value of .5 the temperature is divided by 2 each iteration; meaning that in 4 iteration it does 50 > 25 > 12.5 > 6.25 and then stop (first round + 4 iteration). I'll have a look to the hill climbing for which there is an issue !

**Comment by chapuisk** [comment]
@tnguyenh or @AlexisDrogoul I let you test and close the issue

**Comment by tnguyenh** [comment]
Is the fix in the last alpha version ? I'm testing it with it and it's still not working (I didn't try with the Eclipse version).

**Comment by lesquoyb** [comment]
I tried with the git version and the example model still stops after 3 steps for hill_climbing and 4 for Simulated_annealing
