### ISSUE TITLE
Number of runs in batch optimization and number of max iterations

### ISSUE THREAD

**Issue by leenr01** [gama-platform/gama.old#3549]
In Prey-Predator model 13, when running the optimization experiment, the number of runs is not the same as the number of max iterations specified in the tabu search method. Why is that? What exactly determines the number of runs? And what does the value of iter_max represent?

**Comment by AlexisDrogoul** [comment]
I would suggest to ask this question in the discussions (https://github.com/gama-platform/gama/discussions) or the mailing list (https://groups.google.com/g/gama-platform) as it is not exactly an issue.
