### ISSUE TITLE
Restructure SaveStatement to be able to save as buffer

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama.old#3552]
I dont know if it shoud be here or in discussion. I am wondering how to remove some duplicate when export geojson in gamaserver and normal savestatement. I think that we can restructure the SaveStatement, to have a facet asBuffer, or something like that, to provide the capability to export all the saveable object (image, asc, csv, text, json, geojson) as object in memory or buffer to be transfer on network, or later, can save to file on hard disk.

**Comment by AlexisDrogoul** [comment]
Best would probably be to externalise the different functions in separate utility classes linked to the `save` statement and then make them work only with `OutputStream`s and/or `Writer`s. I can work on it and propose a solution.

**Comment by AlexisDrogoul** [comment]
Please review the changes I have made. Only JSON output is available as a stream / writer right now, but it should already allow to suppress the redundant code.

**Comment by hqnghi88** [comment]
Dear Alexis, 
Thank you for the implementation, I suppressed the redundant in gama server. We will tackle the others if needs later.
