### ISSUE TITLE
OpenGL doesn't work with new SWT 2022-12 on Linux displays

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama.old#3553]
**Describe the bug**
Following issue #3540 and similar as #3199 GAMA OpenGL doesn't work anymore on Linux while built with Maven with the updated SWT version (Eclipse 2022-12)... 

**To Reproduce**
1. Build GAMA with Maven on the branch `swt22-12` (currently on PR #3544 )
2. Start newly built GAMA
3. Start an experiment with opengl display

**Expected behavior**
Having OpenGL display working :upside_down_face: 

**Screenshots**
![image](https://user-images.githubusercontent.com/16764085/207499523-f3e3a2c1-3a41-46c7-97ae-c72430e8da7e.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - PC Model: Dell XPS 13
 - GAMA version: 1.9.0
 - Java version: 17 LTS
 - Graphics cards / Display system: Intel Chipset / X11 or Wayland

**Additional context**
This issue should be related to JOGL and is currently discussed on there forum : https://forum.jogamp.org/JOGL-incompatible-with-SWT-4-21-td4041643.html

**Comment by AlexisDrogoul** [comment]
Now that a fix exists (https://forum.jogamp.org/JOGL-incompatible-with-SWT-4-21-td4041643.html), what do we decide about the generation of GAMA 1.9 ? Do we try Eclipse 2022-12 ?

**Comment by RoiArthurB** [comment]
Since branch `swt22-12` has been merged, **only with x11 Backend** (as jogl doesn't support Wayland), this issue is fixed :)

**Comment by lesquoyb** [comment]
Yes, we just merged it and did a new release including those changes so we can try on all platforms
