### ISSUE TITLE
Status bar not updated on macOS when closing an experiment

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama.old#3554]
**Describe the bug**
When an experiment is closed (and GAMA goes back to the modelling perspective), the status bar should normally indicate that no experiment is running. Instead, it continues to show the last status of the experiment. 

<img width="435" alt="Save to CSV gaml - Gama (runtime) 2022-12-15 12-12-19" src="https://user-images.githubusercontent.com/579256/207778038-14e9b145-0c72-430e-8f80-20fa3ab6656d.png">

Does it happen on other OSes ? 

**Expected behavior**
That the status is correctly updated after the end of an experiment. 

**Desktop (please complete the following information):**
 - OS: masOS Ventura
 - GAMA version: 1.9.0 Git

**Comment by hqnghi88** [comment]
Dear Alexis, it appears on macos 13 beta 3.

**Comment by lesquoyb** [comment]
Also appears on Windows 11
