### ISSUE TITLE
Pedestrian: NPE in path_between in a pedestrian graph

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama.old#3556]
**Describe the bug**
A step in the model `Complex environment - walk.gaml` triggers a nil value exception.

**To Reproduce**
1. Launch the model: `Complex environment - walk.gaml`
2. Do one step
3. The following exception appears:
```
1 occurence in people0 at cycle 0: Java error: nil value detected
in Simulation 0
in 
NullPointerException: Cannot invoke "msi.gama.metamodel.shape.IShape.getEnvelope()" because "source" is null
msi.gama.metamodel.topology.GamaQuadTree.firstAtDistance(GamaQuadTree.java:186)
msi.gama.metamodel.topology.CompoundSpatialIndex.firstAtDistance(CompoundSpatialIndex.java:112)
msi.gama.metamodel.topology.AbstractTopology.getAgentClosestTo(AbstractTopology.java:443)
msi.gama.metamodel.topology.graph.GraphTopology.pathBetween(GraphTopology.java:216)
miat.gaml.extensions.skills.PedestrianSkill.primComputeVirtualPath(PedestrianSkill.java:1435)
gaml.additions.pedestrian.GamlAdditions.lambda$74(GamlAdditions.java:107)
msi.gaml.compilation.GamaHelper.run(GamaHelper.java:73)
in agent people0
```

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git, 1.9
 - Java version: 17

**Comment by AlexisDrogoul** [comment]
I cannot reproduce it. Are there specific parameters' values or preferences you are using ?

**Comment by benoitgaudou** [comment]
After pulling the last version on the git, I cannot reproduce it anymore... So I guess it has been fixed indirectly
