### ISSUE TITLE
Tests are not run

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama.old#3558]
**Describe the bug**
It seems that the tests are not run (or at least I was not able to run them).

**To Reproduce**
1. In the Validation view, I clicked on the button "Run all tests", the result I get is that the workspace contain 358 tests and that 358 are not run.
2. I open a test model fil (e.g. `Boolean.experiment`), launch and run it. Similarly, I get 6 tests and 6 not run.

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: 1.9 alpha (very last nightly built) with JDK for M1

**Comment by AlexisDrogoul** [comment]
It seems that the issue dates back from September, with the multiple commits made by @chapuisk on the restructuration of the batch experiments. Since TestAgent is a direct subclass of BatchAgent, it might has impacted it in some ways.

**Comment by chapuisk** [comment]
On my side the behavior is quite different, as I have tests running with errors.

First, I do have an error on Gama that said TestAgent cannot be cast to SimulationAgent

<img width="1728" alt="Screen Shot 2022-12-20 at 10 04 39" src="https://user-images.githubusercontent.com/13599506/208627160-b9b0d9fc-c800-4515-b08a-a656eca1715b.png">

Second, I have a different picture on Eclipse side, with many error (I cannot get back to the starting error)

* Their is a NPE on a call to SimulationAgent.getCurrentDate()
* Then tests are running well until the 14th one (see Gama prompt below) ``Test test Action connect to the MQTT server`` which raised a new NPE in the network skill ethat stop tests that time.
* Looking at the full stack trace there is multiple error through the tests, but only the server one is terminal. See file attached
[EclipseConsole.txt](https://github.com/gama-platform/gama/files/10267027/EclipseConsole.txt)

**Comment by AlexisDrogoul** [comment]
@chapuisk More precisely, it is this commit: https://github.com/gama-platform/gama/commit/06dd02ec6f759c599a47e2ba639f0d1743ecbc52 that breaks the tests. Before it, they work, after they do not run. 

Regarding your results, I dont know exactly how to reproduce them... And it is strange that it works in your environment.

**Comment by AlexisDrogoul** [comment]
Adding `	if (sets.isEmpty()) { sets.add(new ParametersSet()); }` in `Exploration.explore(IScope)`, just before launching the simulations, seems to solve the problem by preventing the ParametersSet to be empty. Please test if this has undesirable side effects...
