### ISSUE TITLE
"Install new plugins..." : none of the provided available sites works

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama.old#3559]
**Describe the bug**
In the last nightly built of GAMA 1.9, I opened the "Install new plugins..." menu.
Non of the available sites works:
- `https://github.com/anb0s/EasyShell/releases/tag/v2.2.1`
```
Unable to read repository at https://github.com/anb0s/EasyShell/releases/tag/v2.2.1.
Unable to read repository at https://github.com/anb0s/EasyShell/releases/tag/v2.2.1.
https://github.com/anb0s/EasyShell/releases/tag/v2.2.1 is not a valid repository location.
```
- `https://updates.gama-platform.org/experimental/1.9.0`and `https://updates.gama-platform.org/1.9.0` cannot be found.

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: 1.9 last nightly built

**Comment by RoiArthurB** [comment]
Hi  Benoit,

I fixed the EasyShell link with the previous commit. About GAMA's repository, they will be fully filled once gama-platform/gama.experimental Github Actions would be fixed (we're currently working on it with @hqnghi88 ) :)

**Comment by RoiArthurB** [comment]
This issue should be fixed by now :)
