### ISSUE TITLE
The type of the result of the "last" operator is wrong when given a static list of int

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3564]
**Describe the bug**
when using the operator `last` with a static list of int as follows:
```
let l2 <- last([4]) * 3;
```
gama will wrongly think that l2 is of type `file` and show a warning because of the multiplication. 
If you print the l2, it will be `nil`.
It only happens when the operand of last is given as a static list, using a proxy variable would fix it.
The type infered depends on the value of the result, here 4 corresponds to a file, 5 to a graph, 2 to rgb etc.

**To Reproduce**
Run the following model:
```
model last

global {
	init {
		let l2 <- last([4]) * 3;
		write l2;
	}
}

experiment a {}
```

**Comment by AlexisDrogoul** [comment]
The error is strange, as GAMA infers the type of the right side correctly (int). Something related to the use of `let`, I presume, which I rarely use. I will check immediately.
