### ISSUE TITLE
In simulation perspective the container for displays doesn't take the whole space when no display is defined

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3565]
**Describe the bug**
When defining experiments without display, the container for display tabs doesn't fill the whole space horizontally.
Here without display defined:
![image](https://user-images.githubusercontent.com/6374469/209634591-2350a622-c8a6-4191-9dcc-66a374dd89be.png)
And the same with an empty display defined:
![image](https://user-images.githubusercontent.com/6374469/209634777-52193d99-ca63-4a1e-8648-954405efa7f1.png)

not filling the space is really unaesthetic and it looks like the software is buggy in my opinion

**Comment by AlexisDrogoul** [comment]
I have implemented a very simple fix: is it ok in your opinion ? To be honest, I do not really know what to display if nothing is defined...

**Comment by lesquoyb** [comment]
I think a white screen like what you provided is good enough. Maybe we could make use of that space for something else but currently I have no idea about it
