### ISSUE TITLE
Problems in tests with Topology

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama.old#3567]
**Describe the bug**
Since issue #3558 has been solved, tests on topologies, in `Spatial Tests>models>Typology.experiment', are failing. 

![Image 2022-12-27 17-17-41](https://user-images.githubusercontent.com/579256/209693044-8bdd0f4f-9d9c-4363-81c6-5940b1ea6af8.png)

**To Reproduce**
1. Go to 'Test Models>Spatial Tests>models>Typology.experiment'
2. Run the experiment named 'Topology'
3. See the errors being displayed, and especially the report that some distance between 2 cells return 0.0. 

Unfortunately, it is difficult to know when this behaviour began because of #3558 ...

**Comment by ptaillandier** [comment]
I committed a fix - problem with the type of edges when creating the path.
