### ISSUE TITLE
Enhancement: open the parameter sections when starting an experiment

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3568]
**Is your request related to a problem? Please describe.**
Currently, when starting an experiment, the simulation perspective shows up and open the "Experiment/simulation" tab on the left part of the IDE, where we can set the different parameters before launching the experiment. The problem is that the parameters are grouped into sections that are toggled off by default. It is especially annoying when you try to find the correct parameter for something and have to reload the experiment every time you change a parameter and then reopen the correct section. I think having them open by default would make more sense and be less annoying/confusing for the user.

Currently:
![image](https://user-images.githubusercontent.com/6374469/209804030-e6594cb2-ef2a-418e-a4ac-b7772b8bac5b.png)
What I'm asking for:
![image](https://user-images.githubusercontent.com/6374469/209804121-e0cf72ee-cff9-4673-b745-05092b8e5e27.png)

**Describe alternatives you've considered**
We could also keep saved the sections that are open when we reload, it would lead to the same result apart from the initial opening that would still need to be done manually. But it has the advantage to keep the layout as picked by the user, which can be useful when a lot of sections are present but only one or two relevant to the user.

**Comment by hqnghi88** [comment]
You have such a preference to collapse or extends all the section i remember. But yes im pros about the idea of UI detailed config by gaml or by saving in regs

**Comment by AlexisDrogoul** [comment]
As @hqnghi88 mentions, there is a preference that allows to specify whether the tabs are closed or open when starting the experiment. Its implementation followed an issue that complained about the contrary 😀 (i.e. that all the parameters' categories were always opened by default). 

It is a good idea to propose, in addition, a `category` statement that could be defined in `experiment` and maybe allow to write things like : 

`category "My Category" expanded: true color: #blue;`

We could even propose to simplify the definition of categories in parameters by allowing to write:

`category c1 title: "My Category" expanded: true color: #blue;
parameter "Parameter 1" var: xx category: c1;`

But let's not push things too far too fast :)
`category` would remain an optional statement of course (i.e. the categories will still be possible to define in `parameter`.

**Comment by AlexisDrogoul** [comment]
I"ve pushed a first implementation of the `category` statement. So far so good, categories can be expanded or not, and their header can be coloured too. Please test !
