### ISSUE TITLE
GamaMap wrongly initialized when given a complex list of pairs

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3569]
**Describe the bug**
When initializing a map with a simple list of pairs (string keys and int values for example), it is composed as expected. But if it's done with a more complex list especially with unknown keys (let's say a mix of strings and agents) then you get a map strangely composed.
For example:
```
write  map('int_value'::1, 'tab'::[1, 2, 3]);
```
This code will print `map(['int_value'::1,'tab'::[1,2,3]])` which is correct, but if we add a new pair with an rgb key for example:
```
write  map('int_value'::1, 'tab'::[1, 2, 3], rgb(1,2,3)::'some words');
```
We get this: `map(['int_value'::'int_value'::1::1,'tab'::'tab'::[1,2,3]::[1,2,3],rgb (1, 2, 3, 255)::rgb (1, 2, 3, 255)::'some words'::'some words'])`
which is clearly wrong.

**Comment by lesquoyb** [comment]
I already fixed the issue, but the [commit ](https://github.com/gama-platform/gama/commit/4bcff73536dcdcc87af6171e3cc72260975aa57d) that fixes it touches some code I'm not fully aware of the scope of. 
From what I understood the code I fixed should never have worked in the first place, so please check that everything still works, specifically regarding serialization of lists and lists of pairs

**Comment by AlexisDrogoul** [comment]
Seems to be ok on my side.
