### ISSUE TITLE
Cannot define cell_width and width at the same time in grids

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3571]
**Is your request related to a problem? Please describe.**
When declaring a grid, we cannot use at the same time the `cell_width` facet and the `width`. To me it makes no sense as they are not related: `cell_width` defines the rendering width of each cell, while `width` defines the number of cells per line of the grid.
The problem is the same with `cell_height` and `height`.

**Describe the improvement you'd like**
Being able to use both facets at the same time

**Comment by lesquoyb** [comment]
I just removed the restriction in the validation of the species. So far so good on my side but please test

**Comment by AlexisDrogoul** [comment]
It is not possible to use both at the same time, as grids cover the whole environment. So either you define `width`, and the width of each cell is computed from the width of the environment, or you define `cell_width` and the number of columns is computed from the width of the environment. But you cant do both obviously (as it would need the redefinition of the width of the environment, which is not possible).

**Comment by lesquoyb** [comment]
Ok, I'm going to revert the commit then
