### ISSUE TITLE
In batch exploration experiments, an initial parameter value is required but ignored when a min facet is present

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3574]
**Describe the bug**
In a batch exploration experiment, you cannot define a parameter without initializing it:
![image](https://user-images.githubusercontent.com/6374469/210701916-307f3d86-713a-435b-82e1-336b14cb561f.png)
But if you set a value, it will actually not be used in that case as the `min` value will be the first value of the exploration.
For example this model:
```
model exploration

/* Insert your model definition here */

global {
	
	float dummy;
	init {
		write dummy;
	}
	
}

experiment bug type:batch until:cycle > 1{
	
		parameter "Dummy" var:dummy <- 23.8 step:1.0  min:0.0 max:100.0;
	
}
```
will have for first output in the console `0` and not `23.8`.

**Expected behavior**
Either don't force to set a value when the `min` value is going to be used, show a warning, or start the exploration at the init value.

**Comment by RoiArthurB** [comment]
Should be fixed now, and new behavior checks if there's either an init value or a min one : 

![image](https://user-images.githubusercontent.com/16764085/211276768-a61398ed-72e6-4162-8278-d13d3ac215c8.png)

![image](https://user-images.githubusercontent.com/16764085/211276494-05c6edbe-c7a8-425f-9736-5e87b4628081.png)

![image](https://user-images.githubusercontent.com/16764085/211276607-4a51f94a-e511-4996-a8fd-fe897a04a431.png)

**Comment by lesquoyb** [comment]
I don't know if I should open a new issue or not, but if we only have an init value and no min value, the experiment runs only one iteration.
Something that I forgot to take into account is that the steps may be of negative value, and thus the init value should replace the max

**Comment by AlexisDrogoul** [comment]
Should now be fixed from what I tested...
