### ISSUE TITLE
Operator/Function returns the metadata of things

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama.old#3579]
Working with headless Gama server, i would like to have some more operators/functions that can request the metadata of things before the launching of an experiment, especially, the list of experiment name (to build the separated UI from eclipse).
I did not find a solution, or i missed some information.
BTW, in the normal version, the interactive console seems to work only when we launched an experiment.

**Comment by AlexisDrogoul** [comment]
It would help to list precisely what should be available from the outside : list of models, experiments for a model, what else ? 

Regarding the second bug, maybe it would be important to open a separate issue ?

**Comment by lesquoyb** [comment]
working on similar things, what I could find useful is:
 * list of all the imported files
 * list of all the experiments with related data (type, parameters defined inside etc.)
 * is a file syntactically correct ? (I think for now we just have a check on the file extension but maybe I'm wrong) with a list of errors and/or warnings/info if any
But really the most important would be the list of experiments as for the others we can just force and see if an error happen.

**Comment by AlexisDrogoul** [comment]
For me, it is unclear what you are needing here. When @hqnghi88 says " the list of experiment name ", it is the list based on what ? A given model ? A file containing a model ? How do you get access to it ? 

If you can get access to the URI of the file (or can create it), then running `GAML.getInfo(URI uri, long stamp)`, where `stamp` can be the current time stamp or any time stamp you'd like, should return an instance of GamlFileInfo, which gives you access to imports, experiments, uses and whether the file is valid or not.

**Comment by hqnghi88** [comment]
Yes i admit that the need is too vary, but what you are proposing is interesting, so could it be possible to have gaml that wrap the java code GAML.getInfo? 
for the “list of exp name”, it is the ones declared in gaml model

**Comment by AlexisDrogoul** [comment]
Ah ok. I thought you wanted this functionality in Java, not in GAML. So basically, you're looking for something like this : 

```gaml
file ff <- file("xxx.gaml");
write ff.experiments; // list of experiment names (or map<experiment name, list of parameters>) ?
write ff.imports; // list of imported files
write ff.uses: // list of plugins it uses
write ff.valid; // bool (errors or no)
```

Is that right ?

**Comment by hqnghi88** [comment]
(In the first thought, it was an question for java code) but now in gamaserver we use almost of the query with eval_expression so it would be enough to have your last example in gaml
