### ISSUE TITLE
When using parameter facet, the parameter is not display in the UI

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama.old#3583]
**Describe the bug**
When using the ``parameter`` facet with any variable of the model, there is no parameter in the UI of the simulation. However ``parameter`` statement in the experiment works properly 

**To Reproduce**
Either go to ants model (ToyModel library) or create a new dump model, e.g. :

```
global {
	
	int dummparam <- 3 parameter:true;
	int dummexparam <- 1;
	
}

experiment dummexp {
	
	parameter dep var: dummexparam category: dumm; 
	
}
```

**Expected behavior**
To be able to use facet parameter

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - PC Model: MacBook pro M1 Max
 - GAMA version: version 1.9 Alpha with embedded JDK (update: also the case in git version)

**Comment by lesquoyb** [comment]
The facet `parameter` is supposed to be "soon to be deprecated" according to the tooltip, so maybe we should just show a warning that it's not going to work, or directly an error ?

**Comment by lesquoyb** [comment]
Reopening because it still is not working in the case where the parameter is defined in another file than the experiment, for example in the `Segregation (Agents).gaml` model from `Library Models`

**Comment by lesquoyb** [comment]
Another non-working is `Declaration of Parameters.gaml` with the variable `attribute_0`

**Comment by AlexisDrogoul** [comment]
Should be fixed by now.
