### ISSUE TITLE
Shape of world environment always changes to rectangle

### ISSUE THREAD

**Issue by curiosity29** [gama-platform/gama.old#3586]
**Describe the bug**
The shape of the world always changes to the bounding box of the shape defined in the global. It's an example in the documentation to change the world environment to a triangle shape: https://gama-platform.org/wiki/GlobalSpecies#Environment_Size

**To Reproduce**
```
model test
global
{
	geometry shape <- polygon([ {0,0}, {0,2}, {1,1}]);
	init
	{
		write shape;
	}
}
experiment ex
{
	output
	{
		display map 
		{
            graphics "layer1" {
                draw world.shape at: world.location color: #gold;
            }
		}
	}
}
```

**Expected behavior**
The world shape stays as specified.

**Result**
![image](https://user-images.githubusercontent.com/62107278/212870809-eced2484-b977-4018-ba96-b433c1d0c1fb.png)

**GAMA version: 1.9**

**Comment by AlexisDrogoul** [comment]
Yep. The documentation is outdated on this. The shape of the world will always be the envelope of the geometrical shape used to initialize it. I have edited the wiki to reflect this.

**Comment by curiosity29** [comment]
I want to use the torus option on a non-rectangle shape but it's only usable on the global, are there any other option for this?
