### ISSUE TITLE
Trying to run Arduino Model Example in GAMA

### ISSUE THREAD

**Issue by elaineliuwang** [gama-platform/gama.old#3588]
I am trying to connect Arduino to GAMA, but even while trying to run the model example, I am getting the same error.

What I did:
1. Connect an Arduino Uno and slider to port
2. Open GAMA application
3. Go to Plugin models, then Network, then 2 Available protocols
4. Click on Arduino
5. Open .ino file and confirmed readability of slider in Serial Monitor
6. Exit Arduino application
7. Open Arduino_Listener.gaml file back in GAMA
8. Run the test_Arduino experiment
9. Error!

I expected the experiment to run without error and read the Arduino slider I connected to it.
<img width="568" alt="Screen Shot 2023-01-20 at 4 46 11 PM" src="https://user-images.githubusercontent.com/89865258/213811048-39a62550-c066-4e93-be98-f464f04eca34.png">

 - OS: macOS Monterey Version 12.3
 - GAMA version: V1.8.2
 - Java version: 8 Update 361

**Comment by lesquoyb** [comment]
Hello, could you try again with the [latest release](https://github.com/gama-platform/gama/releases/tag/1.9.0) ?

**Comment by elaineliuwang** [comment]
Hi! I just tried the same process in running Arduino in the newest version, and I am still running into the same Java error. However, I also tried it on a Windows laptop and received an "Error Connecting, Try Another Port" pop-up in the experiment.

**Comment by ainhoagenua** [comment]
Hi @lesquoyb!

As @elaineliuwang mentioned in the previous comment, we have tried to fix the error by changing the GAMA version but it is still not working. These last days we have also been debugging it but, unluckily, been unable to fix it.

We would appreciate any help regarding this issue.

Thank you!

**Comment by hqnghi88** [comment]
Firstly, the library is outdated (1.xx vs current 2.xx) so i will update it and we will see. Please try the latest alpha release

**Comment by ainhoagenua** [comment]
Hi @hqnghi88 !

I have just tried the new alpha release and the error remains the same...


![JavaError - NoClassDefFoundError](https://user-images.githubusercontent.com/101112352/217323560-8f86262c-9585-48e9-963e-ffdf4869a0e1.png)

**Comment by hqnghi88** [comment]
Strange, that notfound message must be fixed, i will try to download and recheck

**Comment by hqnghi88** [comment]
https://github.com/CityScope/FoodDeliveries/issues/1#issuecomment-1425982673 any updates?

**Comment by agrignard** [comment]
Thank you @hqnghi88 and @ainhoagenua to spend time to dig on it. Seems that everything is back to normal in the last 1.9 release. It's now time to restart playing with arduino stuff!
