### ISSUE TITLE
Time variables are sometimes evalutated as constants sometimes as expression

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3590]
**Describe the bug**
Take this model:
```
model datetest

global {
	
	date starting_date <- date([2020,1,1]);
	float step <- #year;
	
	reflex plop {
		write current_date;
	}
	
}

experiment a {}
```
It will output:
```
2020-01-01 00:00:00
2020-12-31 00:00:00
2021-12-31 00:00:00
...
```

Now if you change the step with: `1#year` instead of just `#year` it will output:
```
2020-01-01 00:00:00
2021-01-01 00:00:00
2022-01-02 00:00:00
...
```
My guess is that the variable `#year` is not evaluated in the same way if it's in an expression.
The problem is the same with `#month` and probably all the other date variables

**Comment by AlexisDrogoul** [comment]
Only `#month` and `#year` are concerned by this problem -- they are the only date constants that are not ... constant. I changed a bit the way they were compiled and it should be better now.
