### ISSUE TITLE
Save statement saves grid as an image with a vertical flip

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3592]
**Describe the bug**
When running `Save to PNG.gaml` from `Library Models`, the resulting image is flipped vertically compared to the original grid:
![image](https://user-images.githubusercontent.com/6374469/215051095-91f22bd3-55e8-45c1-91f6-123af9a86930.png)
![image](https://user-images.githubusercontent.com/6374469/215051252-ee533183-3b1c-4b54-a1e7-e0694cf4bd73.png)

**Comment by AlexisDrogoul** [comment]
Should be fixed by the latest commit. I also optimised it a lot, using the exact same algorithm used to display grids on displays (direct array copy of raster data) rather than the very slow loop it was using.
