### ISSUE TITLE
Models navigation's height changes depending on the selected model

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3594]
**Is your request related to a problem? Please describe.**
When I'm navigating through the different models using the models navigation view on the left, I often have trouble double clicking on some models, because the first click would trigger a resize of the folder structure, then the second click will fall on a different item.
Here is what happens when I select different models:
![ezgif-3-f0be5bf5ae](https://user-images.githubusercontent.com/6374469/215383355-db943260-1cac-4b2c-947d-a2ebca143cc8.gif)

My guess is it comes from the length of the file name, if it's small enough it will fit next to the search bar, else it goes one level lower, moving the rest of the items with it. It would be nice to have a fixed height allocated to that part of the view so it doesn't happen anymore

**Comment by AlexisDrogoul** [comment]
To be honest, the interest of this infobox is not really clear ... It imposes burden on the file selection and the toolbar for no real benefit (other than clicking to get the properties rather than going to "File > Get Properties"). 

I would be in favour of eliminating it.

**Comment by lesquoyb** [comment]
Ok for removing it too, it would also give more space to the search bar

**Comment by AlexisDrogoul** [comment]
OK. I've removed it and added the "Properties" command to the contextual menu to facilitate its access. 

![Image 2023-02-01 11-27-47](https://user-images.githubusercontent.com/579256/215948102-1498f6a3-1c4f-48b5-9427-1379cb7bd148.png)
