### ISSUE TITLE
Visual artifacts with 2D displays

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3595]
**Describe the bug**
Some models containing multiple java2D displays show visual artifacts. For example in the model `TCP Teleportation.gaml` you can observe this:
![image](https://user-images.githubusercontent.com/6374469/215405913-50d6659d-a980-4b72-8b60-32705278447e.png)
The problem doesn't seem to come from the layout nor the species displayed, if you comment everything you can still observe the grey vertical bars. On the other hand, switching to 3D display solves the problem.
Notes:
 * Maybe that one is a special case because only one display is defined in the experiment but 3 are shown because 3 simulations are running at the same time.
 * Resizing the displays or running the experiment doesn't change anything
 * the artifacts in the right part of the second display corresponds to the first display and the artifacts in the right part of the third display corresponds to the right part of the third display (in the screen half of it is not visible because of the artifacts)

**Additional context**
Windows 11 and Gama 1.9.0 from the release

**Comment by lesquoyb** [comment]
**Update**: it also happens with simple 2d displays, here with `HTTP GET.gaml` model:
![ezgif-3-d6534dfebb](https://user-images.githubusercontent.com/6374469/215415922-bf075d02-94fe-4f0c-af1e-147c88f6ca71.gif)

**Comment by lesquoyb** [comment]
After relaunching gama 1.9.0 (and switching workspace) I'm unable to reproduce the bug, so I guess it was something related with the memory, as it happened multiple times before that I used all the available ram, though the memory usage was fine when I found that bug.

**Comment by AlexisDrogoul** [comment]
Normally, the fix to #3600 should greatly help in those memory-related problems, especially when doing a heavy use of Java2D displays. I close this one anyway.
