### ISSUE TITLE
On Windows the text in the search bars is not completely visible with some scaling ratio

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3596]
**Describe the bug**
As the title states, the text in search bars is sometimes hard to read because the bottom part is hidden.
Here with a 100% scaling ratio everything is fine
![image](https://user-images.githubusercontent.com/6374469/215450697-8dd4be21-fffb-4585-ac70-301f9d3e8ac3.png)
with 150% scaling ratio:
![image](https://user-images.githubusercontent.com/6374469/215450997-4babda0d-22eb-4afa-9401-042cff5f1ae4.png)

the problem is the same with the search bar for gaml references and the one in the experiment bar

**Comment by hqnghi88** [comment]
Did you restart win after scaling changed? Some control on win need restart to take effect

**Comment by lesquoyb** [comment]
Yes I did, I also tried on another computer

**Comment by AlexisDrogoul** [comment]
Same issue with 200% ? And do you have similar problems with Eclipse ? (I think they have similar search bars in the UI)

**Comment by lesquoyb** [comment]
With 200% it works normally too. 
I didn't see any problem in eclipse, though there's no search bar directly in the main window (at least that I know of), it's all in dialogs so that can explain the difference. Search bars in dialogs are fine in gama too, it really is just the three that I mentioned in the first post

**Comment by AlexisDrogoul** [comment]
OK. Can you try setting the following arguments in the run configuration : 

`- Dswt.autoScale=half`

and

`- Dswt.autoScale=quarter`

Verifying that both work (I checked myself and it seems ok) and also that they change something to #3308 ?

If yes, we will include these arguments for Windows configurations.

**Comment by AlexisDrogoul** [comment]
I normally have committed a fix for this. Please test.

**Comment by lesquoyb** [comment]
recent commits did fix that, though they introduced many more problems:

 - with 175% I have those lines everywhere
 ![image](https://user-images.githubusercontent.com/6374469/216869141-31e5976c-edd4-47b0-a00a-c8f73bc67a33.png)
 - the gaml reference popup is displayed on the wrong screen:
 ![image](https://user-images.githubusercontent.com/6374469/216869693-35678c5a-4358-4df0-8928-47e4efaee07f.png)
 - all the small buttons to interact with the simulation look like they were 16x16px and scaled up:
 ![image](https://user-images.githubusercontent.com/6374469/216869617-f6996d03-e0e1-4870-85ff-a40b0119a312.png)
 - at startup, after asking for workspace the splash screen "moves":
 ![image](https://user-images.githubusercontent.com/6374469/216871055-10e9779e-dfd9-431c-8feb-ef1699c6155b.png)
 - 2d display do not fill the whole available space
 ![image](https://user-images.githubusercontent.com/6374469/216871857-a90982e8-709b-43ab-9d1b-8d9e73736c84.png)
 - Some contextual menu images are black/ have strange size:
 ![image](https://user-images.githubusercontent.com/6374469/216879812-8317750e-f81a-49bb-b1da-fa82e1266b4f.png)

**Comment by AlexisDrogoul** [comment]
OK. @lesquoyb Can you please open a new issue per problem above ? And then I close this on in order to remain focused on solving them step by step ... (with the added problem that I can't really reproduce your issues for the moment as it is unclear what your exact configuration is; 2 screens, different resolutions, different zooms ... ?)
