### ISSUE TITLE
Waterflow Field Elevation model doesn't act as expected

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3603]
**Describe the bug**
When running `Waterflow Field Elevation.gaml` with the parameter `fill` set to false, the river doesn't fill correctly:
![image](https://user-images.githubusercontent.com/6374469/217151653-9cb407e2-3d7d-4593-9d13-26106cbe7ef8.png)
Some of the water goes under the terrain:
![image](https://user-images.githubusercontent.com/6374469/217151757-267ec8a5-18a9-452b-8e67-cce43e68ffba.png)
Also some areas of the river never fill

When running with fill set to true everything works properly

**Comment by AlexisDrogoul** [comment]
Because the flow reverses at some point when the water is higher in the riverbed than at the source. And it goes under 🤣 as there is some hole I guess. I can work on tightening the conditions and/or removing this "fill" parameter (which is not super useful...).

**Comment by benoitgaudou** [comment]
Hi,

I admit that, perhaps, the data file for the elevation model is the worst
possible for this model.
It indeed represents the confluence between the Mekong river and the Tonle
Sap river.
It has the specificity that the Tonle Sap flow direction changes depending
on the season (which is very rarer over the world).
So I guess that data should some specificities ...

Cheers

Benoit

Le mar. 7 févr. 2023 à 06:17, Alexis Drogoul ***@***.***> a
écrit :
