### ISSUE TITLE
In 3d displays, grids do not (always) fill the whole screen

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3607]
**Describe the bug**
Running the model `Simple Traffic Model.gaml` I realized that the grid hovering the simulation was not filling the whole available space.
If you change the line:
```
grid cell elevation: pollution * 3.0  triangulation: true transparency: 0.7;
```
with:
```
grid cell elevation: pollution * 3.0 + 1 triangulation: true transparency: 0.7;
```
To show the whole grid, you will realize that the grid (the transparent green layer at init) doesn't reach the right side nor the bottom of the world shape:
![image](https://user-images.githubusercontent.com/6374469/217428911-59befe56-6322-4ef0-8caa-c505303423f4.png)

With a 2d display everything is covered

**Comment by lesquoyb** [comment]
Update: it seems to come from the `elevation` facet, removing it gives a grid that fills the whole available space

**Comment by hqnghi88** [comment]
It is normal for me (the same thing in #3609), the viewport is perspective , and is not orthographic
<img width="566" alt="Screenshot 2023-02-10 at 21 02 23" src="https://user-images.githubusercontent.com/6105384/218110737-cd63de99-71df-4d45-ae6a-8b7fefe366e0.png">
https://bellus3d.zohodesk.com/portal/en/kb/articles/article
So the camera is on top, but you have the depth of objects. it is normal that when the grid's dept/elevation 0, it is on the ground, vs grid's depth/elevation > 0, it's obviously nearer with eyes, and it is bigger than the ground (axes boundary)
If you change to  elevation: pollution * 3.0 + 1000, you will see it cover all
<img width="1120" alt="Screenshot 2023-02-10 at 21 16 59" src="https://user-images.githubusercontent.com/6105384/218113917-b4b09694-2075-4bf6-88f5-02e5997c7854.png">
However, i agree that the camera is a bit false, it is a bit left-translated when depth/elevation is small as in your screenshot (try +200, you will see the left-translated)
