### ISSUE TITLE
The "elevation" facet of grid layer is not working with 2d displays

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3608]
**Describe the bug**
In `Simple Traffic Model.gaml`, when changing the display from 3d to 2d, the `elevation` facet of the grid layer gets ignored and the whole grid is displayed instead of only a few cells.

**Expected behavior**
Either fix it or write in the documentation that it's not supposed to work with 2d displays.

**Comment by AlexisDrogoul** [comment]
`elevation` is supposed to provide some "elevation" to the display of the cell, i.e. a z ordinate. So, it is quite normal that it doesn't show up on 2d displays. What were you expecting ?

**Comment by lesquoyb** [comment]
Just a misunderstanding, we can close it
