### ISSUE TITLE
In 3d displays grid cells are sometimes deformed 

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3609]
**Describe the bug**
Run the model `Simple Traffic Model.gaml` from `Library models`, and after a few steps you can observe some deformations in the appearance of certain cells:
![image](https://user-images.githubusercontent.com/6374469/217433956-c8e4e4b5-f657-4280-a065-6561ae70d00c.png)
It is the most visible on the left side of the simulation, but if you pay attention a lot of red cells are not squares anymore

It works fine in 2d.

**Environment**
Windows 11
tested with gama from git and a release from 1/2 weeks ago
tested with 100% scaling factor and 150%
It also happens with running the experiment step by step instead of just clicking play, though the effect is less impressive (but maybe the impressive effects only happen after a few hundred steps)
It also happens with synchronized output

**Comment by agrignard** [comment]
@lesquoyb the cell is actually deformed by its elevation. If you switch angle (ctrl+drag)  you will get this
<img width="1135" alt="Screenshot 2023-02-08 at 14 19 23" src="https://user-images.githubusercontent.com/3928502/217541325-8613261c-03e6-4718-ac3c-09f41af4a882.png">

**Comment by lesquoyb** [comment]
Yes you are right, I completely missed the point that it's what the `elevation` is supposed to do to the grid.
But now that I'm thinking about it, it looks like the projection of those elevations are wrong, don't you think ?
In my screenshot the camera is supposed to be in front of the grid, thus I shouldn't see any deformation at all, it could be related to the issue #3607

**Comment by lesquoyb** [comment]
Thinking again, the deformation seems normal, I just changed the camera in the model to something similar to what you posted so the elevation is visible

**Comment by agrignard** [comment]
Yes the visual deformation is normal (you are seing from the top a 3D scene so it's normal the grid are "seen as deformed" as soon as there is an elevation. For this issue #3607 (did you try with other simple model using grid?) this is indeed not normal but not related to a problem of vision
