### ISSUE TITLE
Creating a new text file in a folder doesn't have an auto save in that folder

### ISSUE THREAD

**Issue by curiosity29** [gama-platform/gama.old#3612]
**Describe the bug**
Create a new text file by right-clicking on a folder in the workspace and chose to make a text file, the file doesn't auto-save in that folder

**To Reproduce**
![step1](https://user-images.githubusercontent.com/62107278/217734903-754b0627-8968-4056-b681-c7058b097410.png)
![step2](https://user-images.githubusercontent.com/62107278/217734907-238bbda9-dda8-4564-a87b-2ecc1e0fe761.png)
![step3](https://user-images.githubusercontent.com/62107278/217734913-2c3395a7-13a6-4115-952e-1ba0d9c6ac95.png)

**Expected behavior**
The file auto-save in that folder

**Version**
GAMA 1.9.0 - February 7
Window 10

**Comment by AlexisDrogoul** [comment]
This is the default behaviour of Eclipse also. You can specify the path and filename once you save it manually.
