### ISSUE TITLE
Reflexes of my specie do not execute when I add some species in my specie

### ISSUE THREAD

**Issue by rinelfi-git** [gama-platform/gama.old#3616]
I have species named `Lot`, and all the reflexes of this species is not executed so I decided to comment some of my attributes. Here are the attributes:
```
	int _quantite_petite;
	int _quantite_moyenne;
	int _quantite_grosse;
	// Commercant _proprietaire;
	MarcheInternational _destination;
	// Localite _position_actuelle;
	bool _deplacer_commercant;
	bool _embarquer_exportation;
	// Commercant _nouveau_proprietaire;
	// Transporteur _engin_transport;
	int _etape_deplacement;
```
When I uncomment `_position_actuelle` or `_nouveau_proprietaire`. The reflexes of the species `Lot` don't execute.
I tried to find out where does the problem comes from but I can't.
I use Windows 10 and Linux Mint and my Gama version is 1.8.1 all with the JDK (I have some issue when I upgraded to 1.8.2. RC2 to use the `csv_file()` it sets all my value as false so I decided to stay on 1.8.1 version)

**Comment by AlexisDrogoul** [comment]
Hi, without more information (basically the code of your model or a simpler model that exhibits the same problem) it is impossible to help you and decide whether it is an issue with GAMA or with your model. Thanks for sharing more meaningful information !
