### ISSUE TITLE
The new commit in gama-headless.sh stops gama-headless server in GAMA 1.9 for Mac M1

### ISSUE THREAD

**Issue by xiaofanliang** [gama-platform/gama.old#3617]
Hi, I am a Mac M1 user, using the Monterey system. I am on GAMA 1.9. 

I was recently struggling with not being able to start game-headless server in GAMA 1.9 (alpha version). It turns out the solution is for me to revert this commit [gama-platform/gama@240559e](https://github.com/gama-platform/gama/commit/240559e36900b6c58c24b0821f249b49e400872c). A friend commented that the `realpath` is a Linux syntax that is not available in Mac. 

So to solve my problem, in my local version of the gama-headless.sh, I changed 
`if ! "$( dirname $( realpath "${BASH_SOURCE[0]}" ) )"`
back to the previous commit 
`if ! "$( dirname "${BASH_SOURCE[0]}" )"` 

Then I am able to start gama-headless server with GAMA 1.9. 

If you want to see more details of this issue, you can see in [this issue](https://github.com/gama-platform/gama.client/issues/2#issuecomment-1426276139) in gama_client.js Github repo. There are more screenshots and contexts there. 

Note that, the other developer @hqnghi88 did mention that it works on his Mac M1 computer, so I am puzzled.

**Comment by agrignard** [comment]
Just to complete this issue this is the message I have when trying to run GAMA1.9 Headless from Mac M1

And what @xiaofanliang suggests is working. 

@RoiArthurB and @hqnghi88 any chance to commit this change so we can retry with the latest build? 

````
arno@Arnos-MacBook-Pro-2 headless % bash gama-headless.sh -socket 6868
******************************************************************
* GAMA version 1.9.0                                             *
* http://gama-platform.org                                       *
* (c) 2007-2022 UMI 209 UMMISCO IRD/SU & Partners                *
******************************************************************
gama-headless.sh: line 47: realpath: command not found
usage: dirname string [...]
Error: Could not find or load main class org.eclipse.core.launcher.Main
Caused by: java.lang.ClassNotFoundException: org.eclipse.core.launcher.Main
Error in you command, here's the log :
cat: 6868/.workspace: Is a directory
cat: 1/.metadata/.log: No such file or directory
````

**Comment by RoiArthurB** [comment]
I'm installing MacOS Monterey, but I think to remember that it was working fine on Ventura... 👀

**Comment by agrignard** [comment]
@RoiArthurB Is it possible to update the gama.headless for the Mac Os Monterey so we don't have to change it by hand when trying to run headless with the last release 1.9?
