### ISSUE TITLE
Gama raises an exception when using parameter and among facet with explicit duration in month or year

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama.old#3622]
**Describe the bug**
It is a very niche bug, as it implies to use both parameter and among facet for a variable with explicit duration in months or years; exception raised says that 0 value is not included in the list of possible value. Surprisingly, things are running smoothly without parameter facet... I saw this error while working on a model that was working fine 2 weeks ago - I guess it is related to [this issue](https://groups.google.com/g/gama-platform/c/D0eNpDgfbo4) reported in the google group  

**To Reproduce**
execute a model with ``float d <- 1#months parameter:true among:[1#mn,1#h,1#days,1#months,1#years];`` you'll see that everything is ok with minute, hour and days, but raises exception for month and year

**Expected behavior**
be able to use month and years in among facet

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey
 - GAMA version: git 1.9

**Comment by AlexisDrogoul** [comment]
Can you provide the exception ?

**Comment by ptaillandier** [comment]
Another thing:
If we remove the `1` before `#months`, it does not compile anymore:
`float d <- #months parameter:true among:[1#mn,1#h,1#days,1#months,1#years];`
Error: "This expression cannot be used in the context of experiments.
   Please use a constant expression or redeclare this parameter
   in the experiments"

**Comment by AlexisDrogoul** [comment]
As a side note, it is normal, as neither `#month` nor `#year` make sense in an `experiment` (the `starting_date` is defined only in the model). So as soon as `parameter:` is defined, obtaining this exception is not a surprise. What is not normal, however, is the report by @ptaillandier , as this compilation error should be raised also for `1#months` (not only for `#months`).

**Comment by AlexisDrogoul** [comment]
I have changed the way expressions are tested for their "compatibility" with experiment parameters. It is now much more explicit and should be easier to specify for categories of expressions (like for instance things like `#user_location`, etc.). Compilation errors are then correctly raised in the case mentioned in this issue. Please test it and report any problems !

**Comment by chapuisk** [comment]
@AlexisDrogoul,
Now, there is a compilation error; which is fine. However, I cannot cope completely with it: when I turn every possible values to constant, I still get warning on the parameter in the experiment that said, ``The initial value of arretblocage does not belong to the list of possible values. It will be initialized to c6m instead.`` with ``c6m`` the name of the constant the variable ``arretblocage`` is actually init with. To put it simply the warning says it will init the variable with the value it is actually init with.
Best,
Kevin

**Comment by AlexisDrogoul** [comment]
Hi @chapuisk , coming back to this issue: I would love to help, but I do not know what you are talking about and what `arretblocage` or `c6m` are. A bit of context is in order here ! Thanks.

**Comment by AlexisDrogoul** [comment]
@chapuisk : any hint on what is not going well as you would like ? I close the issue as it seems to be anyway different from the original one. Feel free to open a new, more focused, one !
