### ISSUE TITLE
Improve assert statement output readability

### ISSUE THREAD

**Issue by ScriBanana** [gama-platform/gama.old#3624]
Hi,

**Problem :**
The error returned by a failed assert can often times be insufficient to track down the origin of the failure.

**Improvement wished for :**
A way to specify information on the reason the assert failed.

**Alternatives you've considered :**
A facet to add a custom string to the error / warning assert statement output.

**Example** in an agent reflex statement, that provides with the value of the float used to make the bool that was tested false, the instance of the species where the assert failed (this info is already provided) and the cell it is on in the grid :
```java
model assertWithPrompt
global {
	init {
		create spec number: 10 {
			myCell <- one_of(g);
		}
	}
}
species spec {
	g myCell;
	float i <- 1.0 update: gauss(1.0, 0.5);
	reflex {
		assert i > 0.0 print: string("Failed because " + i + " <0 in spec " + self + " in cell " + self.myCell);
	}
}
grid g;
experiment run;
```

**Comment by AlexisDrogoul** [comment]
I'm not completely sure that using `assert` instead of a more conventional test with `if` makes really sense outside tests, but adding a label to the error can be a good addition anyway. I have therefore added a facet called `label:`, which accepts any expression that can cast to `string` in argument.

**Comment by ScriBanana** [comment]
Great, thanks! I'll try it out when I have a connection stable enough to clone the last build.

> a more conventional test with if

What do you mean, exactly? Something like that ?
```C
if checkForError {
   write someInfoOnTheError;
   do pause;
}
```
That's heavier than an `assert` statement, right? The good thing about it is that it allows for one-liners that do not affect code readability much.

Is `assert` only meant to be used in test experiments ?
