### ISSUE TITLE
Writing variables in the console sometimes clears it

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3628]
**Describe the bug**
When writing some variables in the console, it can clear it. I experimented it with big fields, but my guess is that it works with any kind of long text

**To Reproduce**
1. import this model [fields.txt](https://github.com/gama-platform/gama/files/10783094/fields.txt) (and change the extension to gaml)
2. Run the simulation
3. See that only a part of the field is present in the console

**Expected behavior**
The whole historic is present in the console

**Additional context**
changing the write line to `write sample(field_test);` yields better results: the whole field is displayed on one line, but still the first "coucou" is not visible

**Comment by AlexisDrogoul** [comment]
Have you checked if you have a maximum limit of characters in the console in your preferences ? 

![Monosnap 2023-02-21 19-46-53](https://user-images.githubusercontent.com/579256/220348566-69052b3c-4cac-40b1-98a0-d65befb5fbbf.png)

**Comment by AlexisDrogoul** [comment]
I've tested it with and without limits, and it is definitely the limit that ... limits the output (and only displays the last N characters).
