### ISSUE TITLE
Problem with variable/function identification

### ISSUE THREAD

**Issue by curiosity29** [gama-platform/gama.old#3632]
**Describe the bug**
Using 2 variables or 2 actions with the same name in the global and in a species result in unexpected behaviors. With action `act`, the editor recognize does not highlight the correct action but still runs with the correct action in the species and produces an error warning if the action is missing like normal. With variable `x`, the editor highlights the correct variable in the global but still runs with the wrong variable in the species.

**To Reproduce**
model Rename

```
global
{
	int x <- 3;
	action act
	{
		ask sp {do act;}
	}
	init
	{
		create sp;
		do act;
	}
}

species sp {
	int x;
	init{self.x <- x;}
	action act{write self.x;}
}

experiment ex {}
```

**Output**
`0`

**Screenshots**
action `act`
![3](https://user-images.githubusercontent.com/62107278/220584307-36227d5e-a928-415a-b7dd-4844600bcfb3.png)
variable `x`:
![x](https://user-images.githubusercontent.com/62107278/220584334-8a2ee288-c548-4062-a8c8-ab2d63227dfa.png)

**Additional context**
Same identification and output even with more specification:
![4](https://user-images.githubusercontent.com/62107278/220584765-0a115419-798a-4f6a-8956-391626b52cf2.png)

**Comment by AlexisDrogoul** [comment]
The problem of highlight / documentation of vars/actions with the same name in different scopes is already documented in gama-platform/gama2#46 and it will not be addressed anytime soon (at least in this branch of GAMA). 

For the rest, the behaviour is completely normal. `x` in `sp` is treated as a local attribute (although the highlight is again false as it points towards the global attribute) so when you write `self.x <- x` or `int x <- x;` you just do not change its value (which remains at `0`). If you wanted to change its value with the global `x`, you'd have to write something like `self.x <- host.x` or `int x <- host.x;`

**Comment by AlexisDrogoul** [comment]
Closing as it is (at least internally) a direct consequence / dependency of gama-platform/gama2#46
