### ISSUE TITLE
Plugin installation window is almost unreadable with some monitor resolution

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3633]
**Is your request related to a problem? Please describe.**
My main monitor is 1920x1200px with a 150% scaling, which is the recommended resolution/scaling by Windows, and here is what I got when opening the Plugin installation window:
![image](https://user-images.githubusercontent.com/6374469/220811720-a35fabdb-454a-4409-9de4-52734641e5af.png)
Even with the window being fullscreen and the separator between the details and the plugin list pushed toward the bottom at the maximum possible, I can barely see the available plugins, but there's actually a lot of empty space in that window (especially at the bottom), so I think we can arrange it a bit differently to make the plugin list the most important/visible item of the window.

**Describe the improvement you'd like**
Either push the last panel with options to glue it to the bottom, which would leave more room for the plugin list (maybe even make it foldable ?), or set a minimal height for the list that would represent a few lines, and add a scroll bar to the window in case there's not enough height for everything.

**Additional context**
I don't know how the window layout is defined, but it seems to me that the "options" panel has a priority over the list of plugin (and the "details" panel, that in this case is not even visible apart from the title), changing it could drastically improve the end result

**Comment by AlexisDrogoul** [comment]
Do you have the same issue in Eclipse ? Because we do not manage this view at all in GAMA 🤔

**Comment by lesquoyb** [comment]
Somehow I have one more line in the eclipse window, but still far from being optimal:
![image](https://user-images.githubusercontent.com/6374469/220814155-ef311308-af5b-4f9f-92f0-7743cac11a9a.png)

**Comment by lesquoyb** [comment]
Seems like my computer was on a strange state, maybe after plugging/unplugging my second screen or something like this, anyway after rebooting everything is normal now
