### ISSUE TITLE
Issue with the usage of overlapping operator and hexagonal grids

### ISSUE THREAD

**Issue by curiosity29** [gama-platform/gama.old#3635]
**Describe the bug**
The cell overlapping with the user location sometime is unexpectedly nil.

**To Reproduce**

```
model ClickBug

global
{

	action what_cell
	{
		// working properly?
//		list<geometry> gg <- g collect each.shape;
//		geometry cell <-first(gg overlapping (circle(1) at_location #user_location));

		//bug
		g cell <- first(g overlapping (circle(1) at_location #user_location));
		write cell;
	}
}
grid g width: 5 height: 5 neighbors: 6
{
		aspect default {
		draw circle(1) at: #user_location color:#red;
	}
}
experiment ex {
	output 
	{
		display map {
			grid g border: #black;
			species g;
			event mouse_down action: what_cell;
		}
	}
}
```

**Screenshots**
![6](https://user-images.githubusercontent.com/62107278/220858690-07f0c099-3c91-4c80-839f-e23e3358814f.png)

**Additional information**
This way of selecting the grid was taken from line 44 in `Library models/Visualization and User Interaction/User Interaction/models/Tools Panel.gaml`

**Comment by AlexisDrogoul** [comment]
Same for regular (i.e. not hexagonal, which are a bit special) grids ? In 2d or in 3d or both ?

**Comment by curiosity29** [comment]
I haven't encountered any problems with the rectangular grids. And I haven't tried it in 3d yet.

**Comment by ptaillandier** [comment]
I think I solved this issue. Can you test the fix?
