### ISSUE TITLE
Inconsistency in available experiments when importing a model

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3648]
**Describe the bug**
When importing a model containing experiments in another model, those experiments are not available in the "experiment bar" at the top of the editor view, but are still added to the count of experiment in the explorer view.
Here is an example with `Mas KMeans Interactive.gaml` that defines one experiment and imports `Mas KMeans.gaml` that contains two experiments:
![image](https://user-images.githubusercontent.com/6374469/222629181-04ef45bc-effd-467a-9da7-bd9c9d66285b.png)
In the explorer, `Mas KMeans Interactive.gaml` is marked as containing 3 experiments, but in the editor we can only run the one defined in the model file.

**Expected behavior**
Either the explorer shows only the number of experiments defined in a file, or the imported experiments  can be run from the bar at the top of the model editor.

**Comment by AlexisDrogoul** [comment]
There are actually 3 experiments, but it is stated in the model that only 1 should be made available to the user. So there is no inconsistency...  :

```gaml

// To avoid displaying experiments coming from the inherited model MAS_KMEANS
experiment clustering2D type: gui virtual: true;
experiment clustering3D type: gui virtual: true;
```
