### ISSUE TITLE
Use of "Arrow" Keyboard events

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama.old#3653]
**Is your request related to a problem? Please describe.**
It is possible to use Keyboard keys to trigger an event (event layer), but not to use the arrows of the keyboard to trigger them. It could be a nice addition to define simple games.
`
event #arrow_up action:my_action
`

**Comment by agrignard** [comment]
Agree with this, however by default now the arrow are used for camera movement. So we might find a way to specify wether the arrow are used for the camera or for an event

**Comment by AlexisDrogoul** [comment]
I close this one as a "duplicate" of this old issue (#1918) -- although it is not exactly one, but it raises the same questions.
