### ISSUE TITLE
Gama 1.9 headless batch seems broken, at least on MacOS

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama.old#3655]
**Describe the bug**
Trying to run gama-headless automatically failed on latest build whatever option is chosen; even -help does not work. See for instance error below:
```
MacBook-Pro:headless kevinchapuis$ sh gama-headless.sh -help
******************************************************************
* GAMA version 1.9.0                                             *
* http://gama-platform.org                                       *
* (c) 2007-2022 UMI 209 UMMISCO IRD/SU & Partners                *
******************************************************************
gama-headless.sh: line 47: realpath: command not found
usage: dirname string [...]
gama-headless.sh: line 47: realpath: command not found
usage: dirname string [...]
gama-headless.sh: line 47: /../jdk/Contents/Home/bin/java: No such file or directory
Error in you command, here's the log :
cat: .workspace: No such file or directory
cat: 0/.metadata/.log: No such file or directory
```

**To Reproduce**
1. Download latest 1.9 build 
2. Run headless script

**Expected behavior**
Being able to run any headless command 

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - PC Model: MBP arm
 - GAMA version: 1.9 latest build
 - Java version: embedded jdk

**Comment by RoiArthurB** [comment]
Duplicate #3617 the latest release hasn't been rebuilt since the fixing commit ;)
