### ISSUE TITLE
Crash on using R plugin

### ISSUE THREAD

**Issue by curiosity29** [gama-platform/gama.old#3665]
**Describe the bug**
Follow the instruction in the documentation with
![1](https://user-images.githubusercontent.com/62107278/224893591-0d8e0649-50ea-481b-b454-ac6ad0af6914.png)
![2](https://user-images.githubusercontent.com/62107278/224893605-1975fb89-ebe7-4f43-9f33-28516c2425bf.png)
![3](https://user-images.githubusercontent.com/62107278/224893625-6438f532-0c8e-4af1-89b1-0df4a7d1932b.png)
![4](https://user-images.githubusercontent.com/62107278/224893630-a0139ed4-0764-4911-8902-9ee1acea11e4.png)

**To Reproduce**
1. Follow the instruction on: [https://gama-platform.org/wiki/next/CallingR#installing-r-and-rjava](url)
2. Run the model below
3. Crash

```
model test

global skills: [RSkill] {
    
    init{
        do startR();
        
        create people number: 10;
        
        do R_eval("df<-" + to_R_dataframe(people));
        write R_eval("df");
        write R_eval("df$flipCoin");    
    }
}
species people {
    bool flipCoin <- flip(0.5);
}

experiment ex 
{
	
}
```

**Screenshots**
Crash log:
![crashlog](https://user-images.githubusercontent.com/62107278/224892717-6ca2e45d-24be-4c27-870f-2fbbef0daa36.png)

**Desktop:**
 - OS: Microsoft Windows 11 Pro
 - GAMA version: 1.9.0 14/3
 - Java version: follow GAMA

**Comment by lesquoyb** [comment]
Hello, I tried myself and didn't have any problem running the plugin. 
The only difference I can see between your setup and mine is that I'm using a separate jdk and not the one bundled with gama.
@benoitgaudou any clue ? (we already covered that he was referencing two different versions of R in his environment variables, but fixing them didn't solved anything)

**Comment by lesquoyb** [comment]
Thanks to a feedback from a user on the mailing list we found a workaround: we had to copy the `.dll` files from the R_PATH directory into the jdk `bin` folder and it started working. I still don't understand how or why. On my computer those `dll` are not present in the jdk folder at all so I guess in the case of @curiosity29 something is preventing them from being loaded from the R_PATH variable

**Comment by lesquoyb** [comment]
Ok solved it was just lacking the step were we add `R` to the `Path` variable
