### ISSUE TITLE
macOS: Detached display disappears when moved to a second monitor

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama.old#3670]
**Describe the bug**
In a dual-monitor setup (where monitors do not mirror each other), detaching a display and moving the resulting shell to the other monitor makes it disappear. The only solution to get it back is to move back and forth between the editor perspective and the simulation perspective and even then, the detached display comes back to the main monitor of GAMA.

**To Reproduce**
1. Open any model with a display if you have two monitors with different screens.
2. Pick and hold the tab of the display view until the view is detached
3. move it to the second monitor and see it vanish in thin air !

**Expected behavior**
That the display does not disappear, of course. 

**Desktop (please complete the following information):**
 - OS: macOS Ventura
 - PC Model: MBP M1
 - GAMA version: git
 - Java version: 17
 - Graphics cards / Display system: M1

**Additional context**
The problem is certainly due to the fact that we need to manually "hide" the canvas when switching to the editors perspective. For that, a specific listener has been implemented -- and it is certainly causing this bug.

**Comment by AlexisDrogoul** [comment]
Actually the problem manifests itself for any view in Eclipse. At least on macOS.

**Comment by agrignard** [comment]
I am also able to reproduce it. Instead the window "vanishes" as soon as you place it on the second screen. I don't know if it can help to resolve this issue but you can retrieve it by pressing F3 on mac (to have all the active open window), and by moving "by hand" the detached window  to the second screen you can have it operational on the second screen.

**Comment by AlexisDrogoul** [comment]
Just verified and your workaround is working in Eclipse as well. Not really elegant, but well... And the bug is normally only macOS (another good point).

**Comment by lesquoyb** [comment]
Can you document the workaround in the troubleshooting page so we can close that issue ?

**Comment by AlexisDrogoul** [comment]
It is documented. Closing the issue then !
