### ISSUE TITLE
On windows, java2d displays are broken on second screen

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3671]
**Describe the bug**
When I run gama on my secondary screen that has a different scaling ratio than my primary screen, all the java2d displays are broken:
![image](https://user-images.githubusercontent.com/6374469/225810929-408859e5-4cea-4517-8188-f40083565a17.png)
My guess is that the primary monitor scaling ratio is applied. When I set both ratios to be the same everything works correctly

**To Reproduce**
1. move gama to a secondary screen with a different scaling ratio than the primary
2. run any model that has a java2d display
3. See error

**Desktop (please complete the following information):**
 - OS: windows
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
Unsurprisingly, I can't reproduce on in my dual monitor / dual resolution / dual zoom setup...

**Comment by lesquoyb** [comment]
The trick mentioned in https://github.com/gama-platform/gama/issues/3673#issuecomment-1475188739 does solve this problem, beware to set it to `system` and not `system (enhanced)` as I wrongfully stated in the original comment (edited now), else you'll break 3d displays:
![image](https://user-images.githubusercontent.com/6374469/226170486-b0ac839a-c07c-4d50-bb58-f73f5924d7ec.png)
Closing this one, will close #3673 when the trrick is properly documented
