### ISSUE TITLE
Windows: Icons composed of multiple images are blurry with 150% scaling ratio

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3672]
**Describe the bug**
When running gama on windows with a scaling ratio of 150%, the icons composed of multiple images are blurry, which is not the case with 100% and 200% ratios:
![image](https://user-images.githubusercontent.com/6374469/225813089-0dbec0ca-ab64-46c1-96c3-c2a574bb1c61.png)
we can see at startup, when those icons don't have the green dot yet, that they are perfectly drawn:
![image](https://user-images.githubusercontent.com/6374469/225813176-9c683b7b-ca34-441c-ae18-a7a28c10a661.png)

**To Reproduce**
1. On windows, set your scaling ratio to 150%
2. Open gama
3. See error

**Comment by AlexisDrogoul** [comment]
Fractional scaling seems to be complicated ... https://bugs.eclipse.org/bugs/show_bug.cgi?id=563923

**Comment by lesquoyb** [comment]
As mentioned in #3673 setting `High DPI scaling override` to true and choosing `system (enhanced)` solved the issue, here is an example with those settings and a scaling of 150% (same for 125% etc.)
![image](https://user-images.githubusercontent.com/6374469/226169344-de20e210-9026-4900-850f-ce38a9400488.png)
I'm closing this issue and will close #3673 when the documentation part is done
