### ISSUE TITLE
importing graphml

### ISSUE THREAD

**Issue by shitathakin** [gama-platform/gama.old#3681]
Hi.

going through an old project and the importing of a graph in format .graphml has been used:
`graph the_graph <- load_graph_from_file("graphml", "../includes/eg.graphml",nodepoints,road);`

this is throwing an error and no longer seems to be the way data is imported. 

How is it done now?

thanks

**Comment by AlexisDrogoul** [comment]
Hi,

If you do not provide neither the error nor more details, it is going to be complicated to answer you ! 

Alexis

**Comment by lesquoyb** [comment]
Hello, you can find an example of graphml import in the model `Graph Agents Importation.gaml` or `Graph Importation.gaml` in `Library models`.
The operator to use is `graphml_file` here is its [documentation](https://gama-platform.org/wiki/next/OperatorsDH#graphml_file)

**Comment by lesquoyb** [comment]
closing for now, feel free to reopen with more information if you still have issues with the `graphml_file` operator
