### ISSUE TITLE
Save statement silently fails 

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3684]
**Describe the bug**
I tried to run the model `Model 13.gaml` from `Library models`, and noticed that there's an error raised when running `Optimization`, but no message is shown. 
The error view just opens but stays empty, on the other hand the editor opens on the reflex `save_results_explo`. The status bar is not showing any error message either, if we don't pay much attention we could think everything went well.
If we add the `format` facet the error disappears, but there's not even a warning in the code to tell us that it is required.

**To Reproduce**
1. Go to  `Model 13.gaml` 
2. Run it

**Expected behavior**
An error message is shown in the error view + a warning is present in the editor to indicate that `format` is a mandatory facet.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - GAMA version: latest release

**Comment by AlexisDrogoul** [comment]
Actually, 'format:' is not a mandatory facet. The format should be selected from the name of the file... 🤔

**Comment by lesquoyb** [comment]
well, I did fix a few model that had a runtime error from `Library models` just by adding the format in [this commit](https://github.com/gama-platform/gama/commit/ce50798c37067dc2dcd78eeff15d6776138ebe4b)

**Comment by lesquoyb** [comment]
@ptaillandier confirmed me that he also had to specify the format in his recent models. I added an explanation in the troubleshooting page, but I really would prefer if we made that facet mandatory or at least show an info/warning while it's not clear what's causing it, do you think that's possible @AlexisDrogoul ?

**Comment by AlexisDrogoul** [comment]
I have understood what is causing it. At last. Coming with a workaround / fix.
