### ISSUE TITLE
Can't save shp file two times in a row

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3685]
**Describe the bug**
Running the save statement two times on the same shp file results in an exception:
```
2 occurrences in 2 agents at cycle 0: Java error: I/O error
in Simulation 0
in save self to: 'test.shp' format: shp rewrite: true ;
FileNotFoundException: C:\Users\baptiste\Gama_Workspace2\tests\models\test.shp (The requested operation cannot be performed on a file with a user-mapped section open)
java.base/java.io.FileOutputStream.open0(Native Method)
java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
org.geotools.data.shapefile.files.StorageFile.copyFile(StorageFile.java:154)
org.geotools.data.shapefile.files.StorageFile.replaceOriginals(StorageFile.java:132)
org.geotools.data.shapefile.ShapefileDataStore.createSchema(ShapefileDataStore.java:297)
in save self to: 'test.shp' format: shp rewrite: true ;
in init  {
	save self to: 'test.shp' format: shp rewrite: true ;
}

in agents Simulation 0, a0
```

**To Reproduce**
1. Create this model:
```
model NewModel

global {
	
	init {
		save self to:"test.shp" format:"shp" rewrite:true;
	}
}

experiment a;
```
2. Run it twice
5. See error

**Desktop (please complete the following information):**
 - OS: Windows 11
 - GAMA version: latest release

**Comment by AlexisDrogoul** [comment]
Seems to be widespread on Windows (https://stackoverflow.com/questions/4658354/the-requested-operation-cannot-be-performed-on-a-file-with-a-user-mapped-section). And of course not reproducible on macOS... 🤔

**Comment by AlexisDrogoul** [comment]
Another report (https://stackoverflow.com/questions/12308878/file-overwrite-in-java-user-mapped-section-open-error) makes me think of something. can you try to turn the below "memory mapping" feature off ? 
![Monosnap 2023-03-27 15-04-25](https://user-images.githubusercontent.com/579256/227879568-d966c2c3-c338-42f6-b2e3-d5df4e7b1727.png)

**Comment by lesquoyb** [comment]
After testing many models using the save statement, it's the only format that have this issue. @ptaillandier pointed out that it may be something related to a file not being closed or something like this, which seems correct because it's possible to run the experiment again without error after closing gama.

**Comment by lesquoyb** [comment]
Turning "memory mapping" off solves the problem

**Comment by lesquoyb** [comment]
I added the workaround to the documentation

**Comment by AlexisDrogoul** [comment]
Cannot be reproduced anymore. A small model to verify it has been put in Test Models / issues
