### ISSUE TITLE
Save grid to geotiff doesn't look correct

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3686]
**Describe the bug**
The file saved by the model `Save to Geotiff.gaml` doesn't look like the original grid, here is the grid displayed inside gama:
![image](https://user-images.githubusercontent.com/6374469/227868071-551615fe-5ae4-45d9-919d-863fa9093971.png)
Here is the tif file as displayed in gama:
![image](https://user-images.githubusercontent.com/6374469/227868866-14972015-4a11-4a99-80a8-1189a0961ff0.png)
And here the same tif file but in gimp:
![image](https://user-images.githubusercontent.com/6374469/227869094-2de1f05c-27d6-4fa7-81bd-74d826c63724.png)

**To Reproduce**
1.  Run `Save to Geotiff.gaml`
2. See the resulting file 

**Expected behavior**
I'm not sure what's happening with the colors as it's displayed differently in gama image viewer and gimp, but in any case, if colors are not a part of geotiff standard we should still be able to see more than the four central pixels in gimp.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - GAMA version: latest release

**Comment by hqnghi88** [comment]
You should open it with GIS editor (import to QGIS), as geotiff contains not the colors but the values (maybe in multi-band), and im not gimp can process in the right way

**Comment by lesquoyb** [comment]
You're right, it was just a matter of editor, I found one that managed to display it correctly
