### ISSUE TITLE
GAMA is hanging in Headless mode with output synchronized

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama.old#3696]
Using the headless mode (tested with legacy mode and gama server), if the output have the facet synchronized: true. It hang the whole gama with no error in console, even in GS, no new connecting either, it means the main thread is bugging.
To reproduce, simplest way with the headless legacy:
1. Edit the sample/predatorPrey/predatorPrey.gaml, add "synchronized:true" to line 152 (output declaration)
2. Go to headless folder of release
3. Launch command for corresponding OS, ie win: gama-headless.bat samples\predatorPrey.xml out 
4. Gama is loaded then nothing happen after, until we hard-break it execution
Gama git, newest alpha release

**Comment by lesquoyb** [comment]
last commit fixed it for my, can you try @hqnghi88 ?

**Comment by hqnghi88** [comment]
Yes, thank you
