### ISSUE TITLE
Can not able to change the max memory size via the Preferences window.

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama.old#3709]
**Describe the bug**
The maximum memory textbox in the Preferences windows is disabled, users can not change the max. memory size in the Preferences

**To Reproduce**
1. Go to 'Help\Preferences'
2. Click on 'Execution tab'
3. Scroll down to 'The max. memory allocated ...'
4. The textbox can not be changed, it is disabled

**Expected behavior**

**Screenshots**
<img width="710" alt="can not modify max memory in preferences" src="https://user-images.githubusercontent.com/11825516/231197444-0b634aed-7637-403d-ae7c-3d8825bfcf38.png">

**Desktop (please complete the following information):**
 - OS: [e.g. macOS High Sierra]
 - PC Model: [if applicable, can be useful for displays, OpenGL problems)]
 - GAMA version: [e.g. git, 1.7.1, etc.]
 - Java version: [e.g. 1.8]
 - Graphics cards / Display system: [can be useful for displays, OpenGL problems]

**Additional context**

**Comment by tcquang** [comment]
**Desktop (please complete the following information):**
 - OS: Windows 10 64
 - PC Model: Lenovo
 - GAMA version: Windows 64 zip 1.9
 - Java version: 17

**Comment by AlexisDrogoul** [comment]
I will close this issue if you don't mind as the reason why we cant change it in the preferences is explained... in these preferences : it can be modified in Eclipse (developer version) or in Gama.ini file.
