### ISSUE TITLE
Close Simulation confirmation Window problem  on Mac OS 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama.old#3712]
**Describe the bug**

<img width="540" alt="Screenshot 2023-04-11 at 23 18 00" src="https://user-images.githubusercontent.com/3928502/231225809-5d8885cf-d510-4454-bb19-b1e17e3f51c2.png">

The pop up window asking to close the previous experiment is hidden behind the main display and make GAMA freeze (unless you manage in certain case when you have several displays to see the pop up window behind and move it so that you can click on ok)

**To Reproduce**
1. Open any model 
2. Launch it
3. Go back to modelling perspective
4. Relaunch it

**Expected behavior**
A working pop window on top of the display

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS M1 and Intel

**Comment by AlexisDrogoul** [comment]
Three questions : 

- Running the release / eclipse version ? 
- Running GAMA in fullscreen or not ? 
- Is it hidden behind the display or behind GAMA ?

**Comment by agrignard** [comment]
last release
no fullscreen (it happens on any model)
behind the display (you can actually see the window behind when you have more than one display)
<img width="1728" alt="Screenshot 2023-04-12 at 00 21 00" src="https://user-images.githubusercontent.com/3928502/231240568-6a57e76b-5f72-457d-9279-8ba379be2eb7.png">

**Comment by AlexisDrogoul** [comment]
From what I can test, it only appears with OpenGL displays. Can you confirm ?

**Comment by agrignard** [comment]
Yes indeed only with opengl
