### ISSUE TITLE
no tooltip on run/pause/stop... buttons in GUI

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama.old#3714]
There are no tooltips visible on the simulation toolbar when you hover a mouse on these buttons.

<img width="624" alt="image" src="https://user-images.githubusercontent.com/12668606/231241208-83b941f3-c6ae-4e30-a15f-cd770ef34004.png">

**Comment by lesquoyb** [comment]
I do have tooltip info on those buttons, what's your config ?
