### ISSUE TITLE
big blank screen in batch experiments

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama.old#3715]
When running any batch experiment, especially those without a display... almost the entire GAMA screen has a blank space / window. Looks very odd. May be something can be written on ,in place of this blank screen, to suggest that the batch mode is in progress.

<img width="1670" alt="image" src="https://user-images.githubusercontent.com/12668606/231242818-54595ad2-49ad-442a-88f2-5ac1064bff2c.png">

**Comment by AlexisDrogoul** [comment]
Nothing we can really do about this... Sorry !
