### ISSUE TITLE
Toggle icons in black backgound.

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama.old#3719]
In the experiments with black background, It is difficult to see the different status of the toggle icons (Lock/unlock camera; Turn antialias on/off) . If possible please use a different icon when toggled.
![image](https://user-images.githubusercontent.com/11825516/231337116-2152a2e6-a410-4c40-b023-dfbb9ae3ca2a.png)

**Comment by AlexisDrogoul** [comment]
Seems to happen only on Windows 10 -- I close this issue.
