### ISSUE TITLE
Consistency to inspect agents in 2D and 3D

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama.old#3720]
There are 2 different ways to inspect agents in 2D and 3D. 
- In 2D: right click agent\Species: species_name\Agents\agents_number\Inspect
- In 3D: right click agent\agents_number\Inspect (It is assessed directly). 
In the version 1.8 it works nearly directly in 2D mode (right click agent\Species: species_name\agents_number\Inspect
If possible please use the same steps to inspect agent in 2D mode as in the 3D.
![image](https://user-images.githubusercontent.com/11825516/231342669-6c8c45aa-9b4e-43e0-ad3a-d13b490a764b.png)

**Comment by sriramab** [comment]
Indeed, menu goes too deep before any action can be performed.
