### ISSUE TITLE
selection - set selectable layers

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama.old#3721]
In qgis or arcgis, there is a feature to select a one or a few layers that can be made "selectable", so that when the user is selecting an object of a certain type, the other "overlapping" objects from the "non selectable" layers are not included in the selection.

If possible, a choice to set the selectable layers would be of great help, especially in interactive models.

**Comment by AlexisDrogoul** [comment]
Should be covered by the `selectable:` keyword on layers and by the "Forbid Selection / Allow Selection" item in the layers menu.
