### ISSUE TITLE
selection - select by polygon

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama.old#3723]
Requesting for a feature which enables selecting agents by drawing a rectangle.  Currently we have to pinpoint on an agent to access the context-menu and only one agent can be inspected. Would be nice if we can drag a polygon to select all agents within this polygon and for example see the attribute table for these selected agents. 

This can work in combination with #3721

**Comment by agrignard** [comment]
You can actually do it in opengl display using shift + drag

**Comment by AlexisDrogoul** [comment]
It is actually already covered by the ROI (region of interest) that, as Arnaud says, is obtained by shift-dragging.
