### ISSUE TITLE
invisible tabs - tab distinction in editor

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama.old#3724]
When you open 3 or more models in the editor, the tabs in the editor become indistinguishable and assume a flat merged look. see image 
<img width="686" alt="image" src="https://user-images.githubusercontent.com/12668606/231373077-22636de5-737e-4dd2-9622-7e73d58f45d9.png">

I think it is visually more acceptable to distinctly identify each tab in the editor.

**Comment by AlexisDrogoul** [comment]
Looks like we will need to wait a bit... https://bugs.eclipse.org/bugs/show_bug.cgi?id=563585

**Comment by AlexisDrogoul** [comment]
The best that can be done for the moment is to enable some sort of "rounded tab", which at least shows the separator when hovering the tabs

![Image 2023-04-13 01-57-08](https://user-images.githubusercontent.com/579256/231558029-147025df-9453-4c19-9931-03d6fda3a7f7.png)

In the "Advanced..." preferences.

**Comment by AlexisDrogoul** [comment]
This one will be fixed by Eclipse (maybe) one day -- it will be automatically available in GAMA in that case. Closing this until then...
