### ISSUE TITLE
About Scheduler

### ISSUE THREAD

**Issue by curiosity29** [gama-platform/gama.old#3725]
**Describe the bug**
Using
`Library models/Scheduler/Not Executed Random Manager Scheduler.gaml`
The model executed the manager species, conflicting with its description
```
* Description: This model shows how a species can manage other species execution process. In the facet schedules of the 
			manager species, the list of the agents of the species B and A has been given. B agents will be executed first and then A agents.
			An important point is that the manager is not executed, since it is not scheduled anywhere, but it is still scheduling other species agents.
			This is shown with the reflex write_new_step belonging to the manager species that is not executed, not writing its text to the console.
```

Also, if you write the model like this:
```
species A schedules: manager+(A+B)
species manager schedules:manager+(B+A)
species B schedules:[]
```
then output is
```
-----NEW STEP BY MANAGER-----
I'm B 1
I'm A 1
-----NEW STEP BY MANAGER-----
I'm A 1
I'm B 1
```
which seem to be unexpected as I think it should just be one of the following
+ loop forever
+ error due to conflict
+ ignoring later/prior defined scheduler
+ take the first/last scheduler

**GAMA version: 1.9**

**Comment by ptaillandier** [comment]
I removed "manager" from the manager "schedules" facet to be consistent with the documentation.

for the question:
```
species A schedules: manager+(A+B)
species manager schedules:manager+(B+A)
species B schedules:[]
```
The results are as expected: the first created agent is manager, so it will be activated first and schedules first its reflex, then the reflex of every A agents, then the reflex of every B agents; then agents of species A are activated, running first, the reflex of the manager agent, then the reflex of every B agents, and finally the reflex of every A agents
