### ISSUE TITLE
Continue to draw graph in background

### ISSUE THREAD

**Issue by curiosity29** [gama-platform/gama.old#3726]
**Describe the improvement**
The graph stopped drawing, making a missing gap when you came back if you switch to the code section/hiding it. I'm not sure if there's an option but if there is then I think it's should be turned on by default.

**Comment by AlexisDrogoul** [comment]
The preference is here :

![Image 2023-04-12 14-46-33](https://user-images.githubusercontent.com/579256/231388581-da4c14af-7e32-419c-88fe-d2e5fda15853.png)


And it has been decided to turn it off by default some time ago. I close this issue if you do not mind !
