### ISSUE TITLE
Data missing in  Syntax (1.6).gaml

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama.old#3727]
**Describe the bug**

**To Reproduce**
1. Go to 'Library models'
2. Click on 'GAML Syntax \ System\Syntax (1.6)
3. Scroll down to 'Run experiment', click run
4. See error: 
1 occurence in Simulation 0 at cycle 0: File denoted by something.shp not found.
in Simulation 0
in list<geometry> shapes <- list<geometry>(file<int, geometry>('something.shp'));

**Expected behavior**
Without errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/11825516/231396314-950a89b9-765f-44ad-a769-b0d365c632a9.png)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS High Sierra]
 - PC Model: [if applicable, can be useful for displays, OpenGL problems)]
 - GAMA version: [e.g. git, 1.7.1, etc.]
 - Java version: [e.g. 1.8]
 - Graphics cards / Display system: [can be useful for displays, OpenGL problems]

**Additional context**

**Comment by lesquoyb** [comment]
Also rename it to something meaningful
