### ISSUE TITLE
Crash by running spatial clustering

### ISSUE THREAD

**Issue by curiosity29** [gama-platform/gama.old#3728]
**Describe the bug**
Running the plugin model:
`Plugin models/Clustering Algorithms/Spatial Clustering.gaml`
result in crashing.

**Information**
 - OS Name: Microsoft Windows 11 Pro
 - GAMA version: 1.9

**Comment by AlexisDrogoul** [comment]
What is this model ? Which plugin does it come from ?

**Comment by AlexisDrogoul** [comment]
What kind of crashing exactly ? Freeze, error in the model ... ? At launch, during the running ? Because I cant see any problem in macOS.
