### ISSUE TITLE
Right clicking stopped working after dragging

### ISSUE THREAD

**Issue by curiosity29** [gama-platform/gama.old#3730]
**Describe the bug**
+ Start running the model:
`Plugin models/Diffusion Statement/Diffusion in a curve`
+ Drag the display (start at the top middle of the black and red rectangle) by holding the right mouse button
+ The right-click stop working

**Information**
OS Name: Microsoft Windows 11 Pro
GAMA version: 1.9

**Comment by curiosity29** [comment]
The same thing happens when you right-clicking at the running vehicle of the model:
`Plugin models/Driving Skill/Drive Random.gaml`

**Comment by AlexisDrogoul** [comment]
Just to be sure : what you call dragging is with the **left** button, right ?

**Comment by curiosity29** [comment]
> Just to be sure : what you call dragging is with the **left** button, right ?

Not in this case, you can drag with the right button and that's what caused the said issue.
