### ISSUE TITLE
Picking in Mac Os Wrong behavior

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama.old#3731]
**Describe the bug**
Note a big deal and again that seems really related to Mac OS and the release. 

**To Reproduce**
1. OpenGl Display
2. Pick any agent by rick clicking on it (even the world)
4. Click somewhere else to disable the picking

**Expected behavior**
Normal behavior where the mouse can freely move

**Actual behavior**
The mouse is in drag mode on Mac OS. The drag mode can be disable by double clicking on the display 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS M1 Monterey (seems to be ok on Ventura)
 - GAMA version: Gama 1.9 Release

**Comment by agrignard** [comment]
Working now

**Comment by agrignard** [comment]
@AlexisDrogoul do you want to keep the DEBUG.OUT("Mouse pressed from NEWT"); in CameraHelper?

**Comment by AlexisDrogoul** [comment]
Do not mind the debug messages. They will be silenced in the release
