### ISSUE TITLE
Cleanning the overlapping and testing version in Plugin models\Serializations 

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama.old#3732]
In the Plugin models\Serializations, there are 12 models. In which 5 modes in the main folder and 7 ones in the sub model "test" named with "test----". 
Does the models in Test are the testing versions? If yes, it should be removed?

![image](https://user-images.githubusercontent.com/11825516/231420651-6301a64e-c1c6-4af1-b768-0e1860f26715.png)
![image](https://user-images.githubusercontent.com/11825516/231420781-f929a005-f42e-44fe-b61a-6564782486ba.png)

**Comment by AlexisDrogoul** [comment]
@benoitgaudou Do these tests intend to be in "Test models" or can they happily remain here (as none of the experiments are actually test experiments) ?

**Comment by benoitgaudou** [comment]
I removed several models and files to clean the folder.
Please close if it is OK for you.

**Comment by AlexisDrogoul** [comment]
Thanks Benoit !
