### ISSUE TITLE
Plugin models not working

### ISSUE THREAD

**Issue by curiosity29** [gama-platform/gama.old#3733]
**Describe the bug**
Running:
`Plugin models/Physics Engine/Flow on Terrain.gaml`
`Plugin models/Physics Engine/Hello World.gaml`
result in the display of flashing color intensively.

Either they are bugs or there should be a seizure warning.

**Information**
OS Name: Microsoft Windows 11 Pro
GAMA version: 1.9

**Comment by AlexisDrogoul** [comment]
Closing for a bit more focused issues (as the 2 are completely different)
