### ISSUE TITLE
[Windows 10] Blurry fonts in editor and blurry 2d display, pixelized icons with scaling ratio 150% in windows

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama.old#3734]
**Describe the bug**
Depending on the properties of compatibility for high screen resolutions, the font in the editor may appear blurry, and the icons pixelized with a scaling ratio larger than 100%.

It may be related to former closed issues #3604, #3313.

With the following settings:

- with the 'Replace scaling behavior for high DPI settings' unticked, the font is sharp but icons are blurry

![image](https://user-images.githubusercontent.com/18676913/231431758-d0ee08fa-0616-49da-8276-55e45f5c49cb.png)
![image](https://user-images.githubusercontent.com/18676913/231431829-1fce1b46-b6d9-4127-a815-85e1f5b658ac.png)

- with the 'Replace scaling behavior for high DPI settings' ticked:

* with option 'application', font is mildly blurry, icons are pixellized, 3d is sharp and 2d is blurry

![image](https://user-images.githubusercontent.com/18676913/231430944-1f0f3fdd-42a5-4f67-a2c9-deaa8a309a2b.png)
![image](https://user-images.githubusercontent.com/18676913/231430666-cee9d715-c8c7-4ac9-956f-7df5d1fa115e.png)

* with option 'system', font is very blurry, icons are not pixellized but a bit blurry, 3d and 2d are blurry

![image](https://user-images.githubusercontent.com/18676913/231431112-6d751a3f-c6d3-4d71-8c21-2816d4021813.png)
![image](https://user-images.githubusercontent.com/18676913/231431302-2e4d4ec3-056e-4b7d-8882-0547ccdcba6d.png)

* with option 'system (enhanced)', font is mildly blurry, icons are not pixellized but a bit blurry, 3d and 2d are blurry

![image](https://user-images.githubusercontent.com/18676913/231431510-741b85d3-2129-4b34-9ad3-d93a3798e596.png)
![image](https://user-images.githubusercontent.com/18676913/231431591-aef2d691-3b7e-493d-b442-7de372b72867.png)

With no scaling (100%), font is sharp, icons look good, 2d and 3d are sharp.

**Desktop (please complete the following information):**
 - OS: Win 10
 - GAMA version: 1.9

**Comment by AlexisDrogoul** [comment]
This one can be easily reproduced, but it will never be really fixed -- or if it is, it will be by Eclipse (which doesn't load the 1.5x images)... Sorry for that.
