### ISSUE TITLE
[Windows 10] help popup display glitch with display scaling ratio 150%

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama.old#3735]
**Describe the bug**

May be related to isssue #3734

Horizontal lines and some vertical shift appear when scrolling on the help pop up in the editor when the scaling ratio is high.

![image](https://user-images.githubusercontent.com/18676913/231434524-1dccaaed-2011-4871-b83e-c6054055e121.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GAMA version: 1.9

**Comment by AlexisDrogoul** [comment]
This one will never be fixed, sorry !
