### ISSUE TITLE
[Windows 10] Pop up help window background is sometimes yellow sometimes black in dark mode

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama.old#3736]
**Describe the bug**
 May be related to #3735

The pop up help window background is sometimes dark, sometimes light yellow.

![image](https://user-images.githubusercontent.com/18676913/231437969-190dfe86-e9c5-4caf-ae64-e6b25467c787.png)
![image](https://user-images.githubusercontent.com/18676913/231438158-668f3797-1029-46b3-ba06-a427e1855054.png)

**To Reproduce**
I don't really understand what are the conditions to have the light color. However, changing the scaling ratio in window always turns the dark background into the light one.

**Expected behavior**
The background should always be dark in dark mode.

 - OS: Windows 10 and Windows 11
 - GAMA version: 1.9

**Comment by AlexisDrogoul** [comment]
I can't reproduce it on Win 11. It seems to be specific to Win 10 or maybe some "dark" configurations, I don't know. In any case, this part is entirely taken in charge by Eclipse / XText (we just pass the text to the pop-up), so it's not really fixable here. Sorry  !
