### ISSUE TITLE
[headless] using external skills when running GAMA in headless or server mode

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama.old#3749]
It needs to be checked if models that contain use of RSkills (or skills from other plugins) work as expected when using GAMA in headless model or in server mode.

**Comment by AlexisDrogoul** [comment]
Is it a bug or a question ? Does the `dropins` folder work ?

**Comment by sriramab** [comment]
Headless server works with the python wrapper on GAMA models, but does not work when using RSkills. 
Dropins folder is detected, 
Bundles.info is not updated automatically. 
After manually adding jar path to bundles.info, Server startup detects rjava

RSkills model runs, but does not print the GAMA console messages to client on web-socket server. 

This problem is on MacOS. Windows not tested.

**Comment by lesquoyb** [comment]
Closing as superseded by gama-platform/new.gama#33
