### ISSUE TITLE
until facet not working on gui experiment

### ISSUE THREAD

**Issue by curiosity29** [gama-platform/gama.old#3750]
**Describe the bug**
The condition to stop is cycle > 1 but the simulation stop at cycle = 7.

**To Reproduce**
```
model test

global
{
	reflex stop when: cycle > 5
	{
		do pause;
	}
}

experiment exp type: gui until:cycle >1
{
	output
	{
		display "display"
		{
			chart "log"
			{
				data "log" value: log(cycle+1);
			}
		}
		
	}
}
```

**Expected behavior**
The experiment stop at cycle 2

**Screenshots**
![Screenshot 2023-04-13 145151](https://user-images.githubusercontent.com/62107278/231691692-bf482f7f-da72-4723-a786-bb4d3fd4ae17.png)

**Desktop (please complete the following information):**
 - OS: Window 11 
 - GAMA version: 1.9

**Additional context**
Another stop condition in the global is at satisfied at 6 but the simulation stopped at 7

**Comment by AlexisDrogoul** [comment]
This won't obviously be fixed ... 🤔
![Image 2023-04-13 15-00-08](https://user-images.githubusercontent.com/579256/231693843-65569d81-b0de-41ca-be7e-fbedf0c959af.png)

**Comment by lesquoyb** [comment]
That condition is also used by gama server though.
Also, it's still strange that the simulation stops with `7 cycles elapsed` instead of 6, I have some memories of adding one to `cycle` to get the elapsed cycles in the status bar in some older issue

**Comment by AlexisDrogoul** [comment]
@lesquoyb : gama server does not use the facet, I guess ? And regarding the cycles elapsed vs. cycles running, either it is a completely different issue or it is not ... But not in this issue 😉
