### ISSUE TITLE
Improve the slider of the simulation UI

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama.old#3761]
**Is your request related to a problem? Please describe.**
On top of issue #3760 mailnly for visualization/Interaction  purpose (or visual exploration of some specific phenomenum) it would be great to have a more configurable slider.

<img width="303" alt="Screenshot 2023-04-14 at 12 32 23" src="https://user-images.githubusercontent.com/3928502/231949911-ee63ecc9-2f23-452b-be22-53f050bd81f9.png">

**Describe the improvement you'd like**
For instance being able to specify the min and max value or the type of scale (linear vs logarithmic etc)

**Comment by agrignard** [comment]
Ok we have the logarithmic slider I just keep in the code the old value just in case @AlexisDrogoul might want to give the possibility in the preferences to have a linear one (I don't see yet why someone might want this but we never knows?)

**Comment by AlexisDrogoul** [comment]
I clearly don't see why someone would want a logarithmic one over a linear one 🤔 -- please add a preference, set to true for the linear by default (so as to keep the old behavior) !

**Comment by agrignard** [comment]
Preferences set in Execution -> Experiments 

Can I let you validate the text and where it is placed (could go in the interface but it's very related to the execution also) and eventually test it by setting it to false ;-)
