### ISSUE TITLE
Running headless cannot find Gama.ini on MacOs

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama.old#3762]
**Describe the bug**
When I launch the GAMA 1.9.1 in server mode, the first line that appears is that GAMA cannot find Gama.ini.

**To Reproduce**
1. In the GAMA headless repository
2. Launch GAMA headless in server mode
```
(base) benoitgaudou@x86_64-apple-darwin13 headless % sh gama-headless.sh -socket 6868
grep: ./../Gama.ini: No such file or directory
******************************************************************
* GAMA version 1.9.1                                             *
* http://gama-platform.org                                       *
* (c) 2007-2023 UMI 209 UMMISCO IRD/SU & Partners                *
******************************************************************
> GAMA: version 1.9.0                                   loading on____ macosx 12.3, aarch64, JDK 17.0.6
> JAI : ImageIO extensions                              loaded for____ |jpg|tiff|bmp|gif|arx|tf8|TF8|png|ppm|jp2|asc|tif|TIF|TIFF|btf|BTF|pgm|wbmp|jpeg|pbm
> GAMA: Plugin msi.gama.core                            loaded in_____ 239ms
```
3. the first line is:
`grep: ./../Gama.ini: No such file or directory`

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: 1.9.1 alpha

**Comment by lesquoyb** [comment]
I have many questions:
 - Is your gama server running ? 
 - Is the Gama.ini file present ? 
 - where is your console located ? 
 - can you run the grep command from the console ?

**Comment by benoitgaudou** [comment]
I have a very standard installation : I downloaded GAMA release .app and
copy it in the /Applications folder.

   - *Is your gama server running ?*

When I run the gama-headless.sh script, the server was not running. After
running the command, the server is launched.

   - *Is the Gama.ini file present ?*

[image: Capture d’écran 2023-04-14 à 10.01.04.png]

Gama.ini is present. Nevertheless, as you can notice on the screenshot,
from the headless folder, it is not located at ./../Gama.ini but at
./../Eclipse/Gama.ini

   - *where is your console located ?*

The terminal is located in the headless folder.

   - *can you run the grep command from the console ?*

The grep command is accepted.

Note that if I modify the script gama-headless.sh and that the line:

if [ $memory -eq 0 ]; then

  memory=$(grep Xmx "$( dirname "${BASH_SOURCE[0]}" )"/../Gama.ini || echo
"-Xmx4096m")

is replaced by:

if [ $memory -eq 0 ]; then

  memory=$(grep Xmx "$( dirname "${BASH_SOURCE[0]}" )"/../Eclipse/Gama.ini
|| echo "-Xmx4096m")

The error does not appear anymore.

Benoit

Le ven. 14 avr. 2023 à 09:29, Baptiste Lesquoy ***@***.***> a
écrit :

**Comment by hqnghi88** [comment]
@benoitgaudou it means you have the same issue in HEADLESS , not specific for GamaServer?

**Comment by benoitgaudou** [comment]
Yes, I have the same with any headless launch (eg. `sh ./gama-headless.sh -help`)
