### ISSUE TITLE
[GS] verbose mode disconnects the server

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama.old#3766]
When starting the headless websocket, using the python wrapper, with the **verbose flag**, the connection is not stable and disconnects after the first call.

When starting the headless websocket, using the python wrapper, **"without" the verbose flag**, the connection is stable.

**Comment by sriramab** [comment]
see also gama-platform/gama#3756 gama-platform/gama#3758

**Comment by hqnghi88** [comment]
It is relate with the launch script on Mac OS (gama-headless.sh). The last produced command is:
java -cp ./../Eclipse/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar -Xms512m -Xmx4096m -Djava.awt.headless=true org.eclipse.core.launcher.Main -configuration ./configuration -application msi.gama.headless.product -data -v/.workspace0 -socket 6868 -v

The problem come from -data -v/.workspace0 , it is miss recognized/construct and the workspace is then corrupted that lead to unpredictable error (compilation, runtime error of models)
@RoiArthurB please review the generation of arguments

**Comment by AlexisDrogoul** [comment]
This issue should be moved to a proper repository, either  https://github.com/gama-platform/gama.client or whatever new name we give it (`gama.server` ?).

**Comment by RoiArthurB** [comment]
The wrapper had a little type (copy-pasting ?) path error which was taking the last command parameter in the workspace path giving the error from 3766 (`-data -v/.workspace`, wrong folder name in MacOS). 

In general, it remains a good practice (i.e bug-free) to set `headless options` before any `gama headless runner` command (cf. `bash ./gama-headless.sh -help` to know which is what ;) )
