### ISSUE TITLE
Newsgroup link on the welcome page broken

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama.old#3772]
**Describe the bug**
<img width="1726" alt="Screenshot 2023-04-16 at 03 43 41" src="https://user-images.githubusercontent.com/3928502/232252493-579c72fa-8c30-4425-9513-9605f0d74bab.png">

**To Reproduce**
Click on newsgroup yellow icon on the welcome page

**Desktop (please complete the following information):**
 - GAMA version: GAMA 1.9.1

**Comment by AlexisDrogoul** [comment]
Nothing to do with GAMA, but with some obscure blocking of the site from Vietnam or the Internet provider. Works like a charm with a VPN.
