### ISSUE TITLE
Rename advanced_driving to driving

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama.old#3774]
**Describe the bug**
We have an `advanced_driving` skill in GAMA 1.9.1, but no (more) `driving` skill. Since the previous one is not part of GAMA anymore, we could perhaps get rid of the `advanced_` ? 

(Making `driving` a new skill, subclass in Java of the previous, should be enough).

**Comment by RoiArthurB** [comment]
I see you already made all of those changes in a PR, but I think it would be better to apply this to GAMA 2 and prevent any refactoring (specially on the GAML synthax) for GAMA 1.9.X maintenance 🤔

**Comment by AlexisDrogoul** [comment]
Agree. That's why it is in a PR so we can discuss it. Actually, in my opinion we really did not pay attention and missed an opportunity in 1.9.1 with these awkward skill names: `advanced_driving` when there is no `driving` anymore, `skill_road` and `skill_road_node` instead of simply `road` and `intersection` (and the bizarre english with skill at the beginning) ... The goal is to propose these alternative names (but not force anyone to use them, the old ones are still here around) and the only thing that "should break" is in models already having species names `road` or `intersection` and using these skills. But it should be tested further of course.
