### ISSUE TITLE
Update the tag of the 1.9.1 on the github release page

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama.old#3777]
**Describe the bug**
The current tag of the release says the release there has 43 commit to 1.9.1 after this release

<img width="807" alt="Screenshot 2023-04-16 at 10 04 16" src="https://user-images.githubusercontent.com/3928502/232264037-342c1293-2470-4a56-8002-8dca146e1563.png">

We need to update the release tag with the right one

**Comment by AlexisDrogoul** [comment]
Strange as it is, it doesn't seem to be feasible. I guess we'll have to live with it. Good thing is that final users will never see that when they download from the site.
