### ISSUE TITLE
Unnatural operation precedence with operator 'rotated_by' leads to wrong geometry display (squircles are drawn instead of squares)

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama.old#3780]
Presently, the operation precedence gives priority to 'rotated_by' over arithmetic operations. When adding two numbers to define the rotation angle, the geometry is rotated by the first one, then an 'around' operator is applied to the resulting geometry. 

For example, if you draw the following geometry:

```
geometry carre<- square(40) rotated_by 15+10;
```

the results is a squircle, which was not intended and not a specially desired behavior in that context.

![image](https://user-images.githubusercontent.com/18676913/232280301-1ba4ad58-2f4d-4cbf-9b7f-43443f8bfdf3.png)

**Describe the improvement you'd like**

give precedence to arithmetic operations.

**Comment by AlexisDrogoul** [comment]
Precedence is enforced between arithmetic operators but cannot be enforced between "regular" operators. `+` here is not evaluated as an arithmetic operator but as simply "syntactic sugar" to replace `buffer`. And there is no reason why GAMA would choose to give precedence to `+` over `rotated_by`. The correct way to obtain what you want is either to use the prefixed syntax (`rotated_by(square(40), 15+10)`) or to use parentheses (`square(40) rotated_by (15+10);`)
