### ISSUE TITLE
[Library models] Clock model does not work as intended

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama.old#3782]
**Describe the bug**
In library of models, Clock.gaml is supposed to broadcast a sound based on a clock alarm. The part that is supposed to do that is commented. When the corresponding part is uncommented, the model do not compile anymore (the statement `start_sound` does not exist anymore). If ones really want to try sound braodcast from this model, it can replace the statement by the corresponding operator `play_sound`. However, the provided sample sound is mp3 format, which raises an an error because mp3 is not natively supported by java native sound library (needs to add an extension).

**To Reproduce**
1. Go to Library models > Toy model > Clock > Clock.gaml
2. In species Clock, see commented part > uncomment
3. See the compilation error
4. Replace old statement ```start_sound source: "../includes/Alarm.mp3" ;``` by ```bool l <- play_sound("../includes/Alarm.mp3");```5. 
5. Play model and see UnsupportedAudioFormat error

**Expected behavior**
There is several options:
- Leave no commented code in the original model and do not brand sound broadcast
- Uncomment code part and either change audio format from .mp3 to .wav OR add mp3 support to native java library 

**Desktop (please complete the following information):**
 - OS: macOS monterey
 - PC Model: Apple M1
 - GAMA version: Gama 1.9.1

**Comment by AlexisDrogoul** [comment]
In my opinion, if one needs to have proper sound support in GAMA, it would be better to build a dedicated plugin declaring `sound_file`, maybe a `sound` type and operators to read/write/play/convert these data.. I can do it if you want for the 1.9.2 release. So I would be in favor of just keeping the "clock" and not the "alarm" in this model !
