### ISSUE TITLE
CSV agent first column blank values

### ISSUE THREAD

**Issue by Fineion** [gama-platform/gama.old#3786]
When creating agents from a CSV, the first column always returns null or '0' values, despite data being present in the CSV. Example code is below, and CSV attached. Adding a dummy first column is a workaround to this issue.

```
model CSV_test

global {

init {

create water from:csv_file( "../includes/CSV/water.csv",true) with:

[sa1::int(get("sa1")),

service::((replace(replace(get("service"), "[",""), "]","") split_with ",") collect int(each))

];

}

}

species water {

int sa1;

list<int> service;

}

experiment main type: gui;
```

### Expected behavior
Values from CSV are imported to created agents for all specified columns.

### Actual behavior
Null or zero values for the first column of CSV data.

### System and version 
Windows 10, GAMA 1.9

[water.csv](https://github.com/gama-platform/gama/files/11290687/water.csv)

**Comment by AlexisDrogoul** [comment]
This issue reveals something I never heard of before -- see for instance here: https://stackoverflow.com/questions/62917183/what-is-coder-in-string-value, or here: https://stackoverflow.com/questions/64574044/comparing-strings-with-equivalent-but-different-unicode-code-points-in-java-kotl or also there (more detailed): https://stackoverflow.com/questions/70623855/string-from-bufferedreader-is-not-equal-to-string-literal

Basically, what happens is that the string read from the CSV file (`sa1`) and the string passed by GAMA to get the attribute value (`sa1`) are not considered as equal ! One is encoded as UTF-16, the other one as LATIN1. See here the inspection of the two objects: 

![Image 2023-04-23 22-57-07](https://user-images.githubusercontent.com/579256/233850582-0ce07509-8cca-425c-8405-5f691c8f8b59.png)

I'm not completely sure on how to handle this, I will need to make a tests before, for instance to understand why it only happens on the first column...

**Comment by AlexisDrogoul** [comment]
After some testing, it seems to be linked with the encoding of your initial file -- which explains why it is not so widespread. As soon as I edit the CSV file with another text editor and save it, it works normally.

**Comment by Fineion** [comment]
I should have mentioned that I did find it worked normally sometimes by doing this too. The bug appears on the csv I export via Python pandas, or Excel. Sometimes when I opened and saved it via Notepad++ the first column would work normally - then again, not consistently, so not sure what's going on.
