### ISSUE TITLE
multiple events at the same time cancel each others

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3808]
**Describe the bug**
In a model where you created an event associated to a keyboard key, when you press continuously the key, the event is called repeatedly until you release the key. This seems like a normal/expected behaviour. But when you hold this key and press any other key after, the event associated with the first key is not triggered anymore until you release this key and press it again.
If you associate two keys with two different events and press them at the same time, only one event will be triggered instead of both.
Basically it seems that we can only have one key down event triggered and the last.

**To Reproduce**
1. Run this model:
```
model events

species d;

experiment exp{
	output {
		display a {
			species d;
			event 'e' {write "e";}
			event "f" {write "f";}
		}
	}
}
```
2. Press and hold the key "e"
5. wait a bit and press the key "f" while still holding "e"
6. See that the event associated with "f" is triggered while you hold the key but not the "e" anymore
7. if you release "f" and still hold "e" the event will still not be triggered anymore until you release and press again

It happens indifferently in opengl and java2d

**Expected behavior**
Multiple events can be triggered at the same time without cancelling each others

**Comment by lesquoyb** [comment]
Still not completely solved: 
 * when pressing two keys at the same time, the action is executed for the two events, but when releasing only one key, none are executed. 
 * If after that, while still holding one key, you press any key (even if not defined) the event will be triggered

**Comment by AlexisDrogoul** [comment]
There unfortunately won't be any more progress on this 😔. The key listeners existing in Java are designed for text processing, not games. Meaning you can't track several keys at once unless you do it explicitly -- but even so some events are simply not generated.

**Comment by lesquoyb** [comment]
Closing for now as it already has been improved and the remaining problems do not seem to be a priority. Feel free to reopen if it becomes a need
