### ISSUE TITLE
Inconsistent casting of colours

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3809]
**Describe the bug**
Yet another casting inconsistency issue: the casting of colours to other types raise a few questions:
 - casting a `rgb` to an int result in it's rgb representation encoded in the different bytes of the int, which gives a signed number, for example `int(#pink)` is `-16181`. It can be useful to manipulate images with matrices for example. But what is strange is casting to a float returns `0`. Given that floats in java preserve signed int up until 2^22, there's no risk of altering the colour by converting an rgb into a float, and it gives more possibilities to manipulate colours with arithmetic. In addition you can already convert back a float to an rgb and it will give you the proper colour.
 - converting to point returns a point `{0,0,0}` while we could have the red green and blue instead. There would be a loss of data for the alpha component, but I think it is still more helpful than the `{0,0,0}`
 - converting to list returns a list with the three components red green and blue, but misses the alpha component (was it added afterwards maybe?)
 - casting a colour to a map returns a map where the key and the value is the colour. That's fine because it's the default behaviour when casting to a map and don't know how to handle the type, but I think we can improve this by creating a map populated with the components of the colour instead. So there would be a 'red' key with the value of the red component etc.

**Comment by AlexisDrogoul** [comment]
I've done most of the required changes. Only the last one (with `map`) will not be done as it is very specific and needs to be addressed in a more general way (i.e. when translating any object to a map, can we build a map with the attributes of the object as keys and their values as values ?).

**Comment by lesquoyb** [comment]
Ok with the last point, it would be interesting to have that kind of cast, but I think maybe to integrate into GAMA 2.
The first point with a cast to `float` is also lacking though, is it on purpose ?

**Comment by AlexisDrogoul** [comment]
Just corrected it !
