### ISSUE TITLE
Drawn clipped images are not deallocated

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3814]
**Describe the bug**
The draw statement used with a clipped image causes huge memory use and nothing is deallocated neither during the course of simulation or by clicking on the trash icon. Which quickly leads to a low memory error that you can only solve by restarting gama.

**To Reproduce**
1. Run this model until you reach a significant amount of memory used:
```
/**
* Name: imageallocation
* Based on the internal empty template. 
* Author: baptiste
* Tags: 
*/


model imageallocation


global {
		image wall_txt <- image(image_file("../includes/wall.png"));
		
		init {
			create dummy;
		}
}

species dummy {
	
	int x <- 0;
	
	reflex update {
		x <- (x + 1) mod 10;
	}
	
	aspect default{
		// cut a part of the texture
		image wall_part <- (wall_txt clipped_with (x * 100, 0, 100, wall_txt.height));
		// draw the scaled part 
		draw wall_part at:{x * world.shape.width/10 + world.shape.width/20, world.shape.height/2} ;
					//	size:{world.shape.width/10, world.shape.height};		
	}

}

experiment name type: gui {

	
	
	
	
	output {
		display dummy type:2d {
			species dummy;
		}
	}
}
```
4. Try to run garbage collector
6. Observe that nothing changes

**Expected behavior**
The memory doesn't fill during the simulation + we should be able to garbage collect once the simulation over

**Additional context**
works with 2d and 3d displays. I didn't notice such a problem by using the full image, nor if I simply clip the image without drawing it.
The image I used is available here, though it's nothing special and works with any images:
![wall](https://github.com/gama-platform/gama/assets/6374469/71444455-f5a4-4ca3-a872-ae222a268bfd)

**Comment by AlexisDrogoul** [comment]
The problem should now be solved (faulty use of a cache)

**Comment by lesquoyb** [comment]
I noticed some improvements (the example model runs well now) but on a more complicated one I still have huge problems of memory not being deallocated.
You can have a look here: [incredible model](https://github.com/lesquoyb/gama.wolfenstein/), all the code about drawing and slicing images is in the `eye_of_the_beholder` aspect and the main display. I didn't manage to find what's different from the example model but I'm sure it's related to images (if you try the code you'll find many other image related problems that I couldn't isolate yet like some being rendered as white rectangles instead of displaying their content).
Anyway I'll try to have a look later but don't really know when

**Comment by NaroaCS** [comment]
Sorry for the probably very basic question, but how can I download  a version of Gama with that commit? 
I usually download the latest pre-release from here: https://github.com/gama-platform/gama/releases but that doesn't include commit [7839e38](https://github.com/gama-platform/gama/commit/7839e38a71694621fab9174b1f8a8e5e81f866ec)

**Comment by lesquoyb** [comment]
recent commit indeed improved memory leaks by a lot. There's still a tiny bit of it, but it may not be related.
Keeping the issue open just to remind me to investigate more, but I think it's solved
