### ISSUE TITLE
Display of SVG images with their colors

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama.old#3824]
**Is your request related to a problem? Please describe.**
The following SVG image contains at least 2 colors (perhaps 3 colors with the white in the middle).
 ![sheep](https://github.com/gama-platform/gama/assets/1555274/a15ffae9-75c1-4e41-891e-365b65010c86)

When this image is used in an aspect, it is displayed with only 1 single color (as it seems to be considered as a geometry).
```
		draw image_file("../includes/sheep.svg") size: 1000 rotate:45 color: #black;
```

**Describe the improvement you'd like**
It could be nice to be able to use SVG images as images (with its colors) in the displays and not only as geometries.

**Comment by AlexisDrogoul** [comment]
It would require to define the casting of a SVG file into an image, an easy task -- provided we add the Batik library to GAMA, around 5MB more. @gama-platform/core @lesquoyb do you agree with this addition to 1.9.2 ?

**Comment by lesquoyb** [comment]
Could it break previous use cases ? If not we can add it, it's more of an improvement than an addition

**Comment by AlexisDrogoul** [comment]
I have implemented most of it, which also contributes to solve #3822 and #3823. I have however one last aspect that I don't fully master: some files seem to require a flipping and/or a translation of the coordinates and I am unable so far to distinguish them. I'm investigating !

**Comment by AlexisDrogoul** [comment]
@benoitgaudou  Please test to see if the latest commit has solved this issue.
