### ISSUE TITLE
GAMA splash screen up side down on Mac OS 14

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama.old#3825]
**Describe the bug**
As in the title, the binary version will launch with a rotated splash screen . 

<img width="1103" alt="Screenshot 2023-06-09 at 11 29 22" src="https://github.com/gama-platform/gama/assets/6105384/e6caf73d-55f6-43fa-ab46-e34b44d686bf">

Air M1, git binary, Macos 14 Sonoma

**Comment by AlexisDrogoul** [comment]
Does eclipse have this behavior too ?

**Comment by hqnghi88** [comment]
You are right, the eclipse splash screen have the same behavior.

**Comment by AlexisDrogoul** [comment]
Can you test if Eclipse 2023-06 has the same issue ?

**Comment by hqnghi88** [comment]
Unfortunately, same issue for Eclipse 2306 and new Macos beta 2 (this morning).

**Comment by AlexisDrogoul** [comment]
https://github.com/eclipse-platform/eclipse.platform.swt/issues/751

**Comment by lesquoyb** [comment]
Since there probably won't be any proper fix for this before the release 1.9.2, can we change the splash screen to one that also works when upside down as a temporary workaround for the release?

**Comment by AlexisDrogoul** [comment]
Something like this ? 

<img width="551" alt="image" src="https://github.com/gama-platform/gama/assets/579256/f22a01bf-606e-481a-927d-1dbec85a783d">

**Comment by AlexisDrogoul** [comment]
Two variations. 

<img width="550" alt="image" src="https://github.com/gama-platform/gama/assets/579256/30757fc6-e6d1-46c8-97da-cf2b88e39d0f">

<img width="550" alt="image" src="https://github.com/gama-platform/gama/assets/579256/23774b77-69a9-4c91-b838-0dd763ca9624">

**Comment by lesquoyb** [comment]
I prefer the first one, but yes that works for me

**Comment by Phillipus** [comment]
Why not help to address the underlying issue - https://github.com/eclipse-platform/eclipse.platform.swt/issues/772

**Comment by AlexisDrogoul** [comment]
Because this requires compétences in ObjC that -- to my knowledge -- no one has among GAMA developers !

**Comment by Phillipus** [comment]
> Because this requires compétences in ObjC that -- to my knowledge -- no one has among GAMA developers !

It's not about ObjC. You can do things like confirm the issue, report it to Apple, analyse it, etc.
