### ISSUE TITLE
Generated ASC header throws a warning when importing the file

### ISSUE THREAD

**Issue by ScriBanana** [gama-platform/gama.old#3837]
Hi,

**Describe the bug**
When generating an ASC file with function `save ... to: "....asc";`, the generated ASC file can be written with a header that will throw an error when imported with `file()` and used as world shape or grid defining data.

The bug is #3754, that is marked as fixed, yet doesn't seem to be. Basically, an ASC generated from a grid that got coordinates (from a shapefile, for example), may have a header that, when imported using `file()` and used as a world shape or in the `file:` facet of a grid, throws : `Format of ....asc seems incorrect. Trying to read it anyway`
I would like to add to #3754 that the `save` function as ASC file may generate several types of ASC headers, particularly when setting a shape from a file, including ones that throw a warning.

**To Reproduce**
For example, run the following snippets using the attached [SHP file](https://github.com/gama-platform/gama/files/12182981/mapLimits.tar.gz) with `geometry shape <- envelope(mapLimits);` commented, then uncommented.
<details>
  <summary>Export script </summary>

```java
model TestASCExport

global {
	shape_file mapLimits <- shape_file("../includes/mapLimits.shp");
	geometry shape <- envelope(mapLimits);

	init {
		save cellGrid to: "../results/grid.asc";
	}
}
grid cellGrid {
	float grid_value <- float(rnd(255));
}

experiment GenerateASC;
```
</details>

<details>
  <summary>Import script </summary>

```java
model TestASCImport

global {
	file grid_data <- file('../results/grid.asc') ;
	geometry shape <- envelope(grid_data);
}

experiment gridloading ;
```
</details>

Results:
Header without SHP (no error when importing):
```
ncols         100
nrows         100
xllcorner     0.0
yllcorner     0.0
cellsize      1.0
```
With SHP (importing and using as in the grid file facet or as a shape returns: `Format of grid.asc seems incorrect. Trying to read it anyway.`):
```
ncols         100
nrows         100
xllcorner     -1684940.3713166039
yllcorner     3170668.0308883013
dx            35.576692632995545
dy            51.444238101085645
```
Changing manually `dx` and `dy` fields to a single `cellsize` line removes the warning.

**Additional context**
Tested with various shapefiles generated with QGIS in WGS 84.

**Desktop:**
 - OS: Linux Manjaro & Windows 11
 - GAMA version: 1.9.2 release & a more recent commit

**Comment by ptaillandier** [comment]
Hi,

It is due to the limitation of the ASC format: normally you should be able
to use only square cells with it (
https://desktop.arcgis.com/en/arcmap/latest/manage-data/raster-and-images/esri-ascii-raster-format.htm),
which is not the case in your example - you have rectangle cells (dx:
35.576692632995545, dy: 51.444238101085645), and so GAMA is not able to
read it correctly, which explains the warning. In cases like this one where
you do not have square cells, you should use Geotiff format instead of asc.

Cheers,

Patrick

**Comment by ScriBanana** [comment]
Hi Patrick,

Thanks for the answer!

Well Gama itself produces this header with rectangular cells; it is a bit odd that it generates stuff that we "shouldn't be able to use"...

Either way, I think a warning more specific than "Format .... seems incorrect" would be nice if possible.

As for me, is there any way to "squarise" the grid before saving it in an ASC format to avoid the warnings ?

Thanks
