### ISSUE TITLE
Insert template does not work on Eclipse 2023-06

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama.old#3851]
**Describe the bug**
The menu "Model > Templates > ..." does not allow to insert templates anymore. Furthermore, some templates seem to be missing (for instance, `create` has normally three templates attached, but only one shows up in 1.9.2). 

![Image 2023-08-21 15-04-11](https://github.com/gama-platform/gama/assets/579256/884b9abe-33fc-46a7-8ffe-3f0b91d2d8ff)

**Expected behavior**
That everything works as usual, for example like in 1.9.1 ! 

**Additional information**
It seems that some installations of 1.9.2 are not subject to this bug (@hqnghi88 ?)

**Comment by lesquoyb** [comment]
It seems to depend on the template, I tried the same as the one you have in the screenshot (create) and nothing happened, but those in the `examples` submenu are working well:
<img width="891" alt="image" src="https://github.com/gama-platform/gama/assets/6374469/49621191-55b8-476e-ad9b-a028fb750682">

**Comment by lesquoyb** [comment]
**update**: strangely enough it works like a charm from eclipse:
<img width="945" alt="image" src="https://github.com/gama-platform/gama/assets/6374469/4c5e5d24-7b1f-4158-9281-f155bd0128ed">

**Comment by AlexisDrogoul** [comment]
And for me ... it doesn't work from Eclipse 😂. There is something fishy going on here.

**Comment by lesquoyb** [comment]
I just tested on a build using eclipse 2022-12 and latest commits (thanks @RoiArthurB), and the templates works perfectly. So I guess it is something related to eclipse version/packages bundled or not

**Comment by AlexisDrogoul** [comment]
The issue manifests itself in 1.9.3 with Eclipse 2023-09 and 2023-06.
