### ISSUE TITLE
Gama 1.9.2 splashscreen on Mac M1

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama.old#3870]
**Describe the bug**
Here is the splashscreen when running the new 1.9.2 release on a Mac M1 on Monterey. Actually maybe this is the excepted behaviour (Then 1.9.2 is the black and white mirror of 1.9.1 ?  why not) in this case this issue can be closed.

**To Reproduce**
Download the 1.9.2 and run it

**Expected behavior**

**Screenshots**
<img width="601" alt="Screenshot 2023-09-14 at 14 35 31" src="https://github.com/gama-platform/gama/assets/3928502/452eb430-2530-4bd9-84f9-14cf5446546c">

**Desktop (please complete the following information):**
 - OS: Mac M1 Monterey
 - PC Model: [if applicable, can be useful for displays, OpenGL problems)]
 - GAMA version: 1.9.2

**Comment by RoiArthurB** [comment]
It's the new version's splash screen (check in the down corner of it, 1.9.2 ;) )
