### ISSUE TITLE
Define a user_location_on_display command

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama.old#3873]
**Is your request related to a problem? Please describe.**
In the same way that ```#user_location```  returns the position of the mouse in the model coordinate it could be useful to also get the user position in the screen coordinate. One possible application of this would be to couple the overlay feature and this feature to easily define static user interfaces on a display

**Describe the improvement you'd like**
One potential name could be ```#user_location_on_screen```  or ```#user_location_on_display```

**Comment by AlexisDrogoul** [comment]
#user_location_in_display has been added as a constant, and #user_location now accepts the alternative name #user_location_in_world. Please test and close this issue if it is resolved !
