### ISSUE TITLE
Two displays can have the same name in a simulation without warning

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3874]
**Describe the bug**
In gaml you can define an experiment with multiple displays having the same name. In that case the latest display defined with that name will be the one executed, and not the other. I understand this behaviour, but the problem is that there are no warning or info telling you that the latest defined is going to be the only one printed.

**To Reproduce**
1. Run this model:
```
/**
* Name: samedisplays
* Based on the internal empty template. 
* Author: baptiste
* Tags: 
*/


model samedisplays

experiment a {
	output{
		display a {
			graphics who{
				write "a";				
			}
		}
		display a {
			graphics who{
				write "b";				
			}
		}
	}
}
```
3. Observe that only one display is showed
4. in the console we only see "b" so the first display hasn't been executed at all

**Expected behavior**
Either a warning or an info shows that the last display is going to override the first(s) one(s)

**Additional context**
The title of the displays can be given as a string, an unquoted name or a mix, the problem is the same.
It works if the displays are both 3d or 2d indifferently.
If the displays are not of the same type (2d/3d) then it doesn't work

**Comment by AlexisDrogoul** [comment]
Should be better documented now 



![Image](https://github.com/gama-platform/gama/assets/579256/9616da79-1308-4d00-9bcb-123808949581)
