### ISSUE TITLE
Operator type_of doesn't act as expected

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3875]
**Is your request related to a problem? Please describe.**
To my knowledge, there's currently no proper way to get a variable's type, I don't think it would cost much to add an operator to get a variable's type and could help debugging.

**Describe the improvement you'd like**
Add an operator that can return a variable's type. Maybe to be more complete we could create a special type to describe types as it's the case in other languages, but just a string representation would already be a great improvement.

**Comment by AlexisDrogoul** [comment]
https://gama-platform.org/wiki/OperatorsSZ#type_of 😉

**Comment by lesquoyb** [comment]
Thanks, however I noticed a few problems using this operator.
Using it directly in a write statement works as expected, but storing it in a variable not at all.
For example:
```
write string(type_of (12.0 with_precision 0.01));
```
this works and prints `float` as expected.
but this:
```

model NewModel

global {
	init {
		let j <- string(type_of (12.0 with_precision 0.01));
		write j;		
	}
}

experiment name type: gui {
}
```
shows warning on the `j` assignment line and prints `0.0`. It seems like gama wrongly assumes that the type of `j` is float in that case while it's explicitly casted into a string. If I force j to be a string instead of using `let` it works as expected.
In addition, if I try to catch the type in a gaml_type variable I'm not able to convert it to string afterwards:
```
model NewModel

global {
	init {
		gaml_type j <- type_of (12.0 with_precision 0.01);
		write string(j);		
	}
}

experiment name type: gui {
}
```
this prints `gaml_type` which is incoherent with the example in the documentation.
There may be a way to get the type id as a string from a gaml_type, but this type is completely undocumented
