### ISSUE TITLE
Gama crashes if computer can't assign 4GB of RAM

### ISSUE THREAD

**Issue by WoodenMaiden** [gama-platform/gama.old#3879]
**Describe the bug**
An error is thrown when trying to launch Gama 1.9.2

**To Reproduce**
1. Download at https://github.com/gama-platform/gama/releases/download/1.9.2/GAMA_1.9.2_Linux_with_JDK.deb
2. sudo apt install ./Downloads/GAMA_1.9.2_Linux_with_JDK.deb
3. Open Gama on your desktop

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.2
 - PC Model: KVM virtual machine
 - GAMA version: 1.9.2 with embedded jdk
 - Java version: 17 Temurin

It looks like the problem is caused by the double slash as you can see on the second line

![image](https://github.com/gama-platform/gama/assets/62052467/29637b4c-9be3-4cc8-af8d-973529abc9d3)

**Comment by WoodenMaiden** [comment]
My bad I didn't allocate enough RAM to the VM, nothing to do with path resolution ;)

**Comment by RoiArthurB** [comment]
The solution to this issue was to edit the file `Gama.ini` and set a lower minimal RAM needed by the system : changing `-Xms4096m` (requiring minimum of 4GB of RAM) to `-XmsXXXm`  (requiring minimum of _XXX_ MB of RAM)
