### ISSUE TITLE
Odd visualisation of some models with the default z factor parameter

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3880]
**Describe the bug**
The z factor parameter introduced to solve #3857 break some models by adding an increment that seems way too much even though it's supposed to be only 0.05 by default.

For example on the model `stairs.gaml` in model library:
<img width="669" alt="image" src="https://github.com/gama-platform/gama/assets/6374469/89ffe3dd-8867-4591-9554-80e9c823b898">

@tnguyenh showed me a model where the gap between layers was really extreme. I think the problem might lie in the unit of that offset

**Expected behavior**
There should be no perceivable difference between layers with the default z_factor value

**Comment by AlexisDrogoul** [comment]
Please test !
