### ISSUE TITLE
How can I import a font for an UI from a local file and make it accessible to everyone working on the project?

### ISSUE THREAD

**Issue by maiaaan** [gama-platform/gama.old#3882]
**Describe the bug**

I wanted to change the font of my UI to "Jaldi" with the font operator : 

> operator font (string,int,int) returns font
> Creates a new font, by specifying its name (either a font face name like 'Lucida Grande Bold' or 'Helvetica', or a logical name like 'Dialog', 'SansSerif', 'Serif', etc.), a size in points and a style, either #bold, #italic or #plain or a combination (addition) of them.

However, the operator does not recognize this font (no error but it puts the default font instead). It seems that fonts that can be used are built into the operator as the Jaldi font is installed in my system. Is there another way to use the Jaldi font ?

**Desktop (please complete the following information):**
 - OS: macOS Ventura V13.5.2
 - PC Model: Mac mini
 - GAMA version: 1.9.2

**Comment by AlexisDrogoul** [comment]
Hi -- is it the case with other fonts or only with this one ?

**Comment by maiaaan** [comment]
You have to restart the computer for JAVA to take into account your newly installed font.
