### ISSUE TITLE
Odd behavior of ask statement when addressing simulations in experiment

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama.old#3891]
**Describe the bug**
Probably because of an enforcement of the logic of the scope of experiments (which allow to "pass through" down to the lastly created simulation, so as to allow to manipulate simulation attributes directly in experiments), a statement like : 

```
ask simulations {
    write " ... " + att1; 
}
```

where `att1` is a global (simulation) attribute, does not work as intended if there are many simulations. Only the value of `att1` of the lastly created one (the one denoted by `simulation`)  is written. 

**Expected behavior**
That `att1` is evaluated, in turn, in the context of each of the simulations. 

**Additional context**
Reported here first by @chapuisk : https://groups.google.com/g/gama-dev/c/7DrEJkuVX0I

**Comment by AlexisDrogoul** [comment]
Please test if it is ok now !

**Comment by chapuisk** [comment]
From what I have been able to test (the two models modified in the commit 5d2cf7a), the bug is fixed !
