### ISSUE TITLE
The mess of org.apache.commons.compress in Eclipse 2023-09

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama.old#3892]
**Describe the bug**
It appears that the two same versions of Eclipse (2023-09 - Build 20230907-1323) sport two different versions of `org.apache.commons.compress` in macOS and Windows/Linux ... **with two different names !** 🙄: `org.apache.commons.compress` on Windows and Linux, `org.apache.commons.commons-compress` on macOS... See the screenshots below:

![image](https://github.com/gama-platform/gama/assets/579256/1cd225c3-2dfc-4169-97d6-f356211352ab)

<img width="539" alt="About Eclipse IDE 2023-09-26 09-20-01" src="https://github.com/gama-platform/gama/assets/579256/7d23c8d7-1331-4bf9-a004-b0dc31878539">

This of course creates acute problems when sharing and building the platform (with the necessity to change back the names every time someone commits a MANIFEST.MF file !) as we tend to declare dependencies using plugins (and not packages).  

Before declaring this, I  will experiment three solutions: 
1. declare both plugins as optional (but it might create a problem when compiling with maven)
2. manage the dependencies using packages only (but complicated as compress is a second-hand dependency of some jars in msi.gama.ext
3. directly incorporate compress in msi.gama.ext and export its packages (and remove it from the features, etc.).

**Comment by hqnghi88** [comment]
<img width="1426" alt="Screenshot 2023-09-26 at 09 33 20" src="https://github.com/gama-platform/gama/assets/6105384/3c78ff86-5442-4605-b4f9-a080f270eb7f">
It is org.apache.commons.compress for both my M1 and Win11

**Comment by hqnghi88** [comment]
And it is 1.22.xxx, i cant find the version 1.23 as in your Mac.

**Comment by AlexisDrogoul** [comment]
@hqnghi88 did you install it with the installer or directly downloaded the DSL package ?

**Comment by hqnghi88** [comment]
Yes, both downloaded for DSL package.

**Comment by AlexisDrogoul** [comment]
OK -- first option does not work with Maven. Second one is more complicated than planned (uses of compress are internal to some libraries). I will try the third one.

**Comment by AlexisDrogoul** [comment]
Seems that adding manually `org.apache.commons.compress` in `msi.gama.ext` finally did the trick. I'm closing the issue, fee free to reopen if weird things happen.
