### ISSUE TITLE
Simulations not deallocated in batch mode

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3893]
**Describe the bug**
When running a batch experiment, it seems that the finished simulations are not deallocated until the end of the experiment. Which leads to OutOfMemory exception for demanding simulations.

**To Reproduce**
Here is an example model:
```
/**
* Name: batchallocation
* Based on the internal empty template. 
* Author: baptiste
* Tags: 
*/


model batchallocation



global {
	
	image wall_txt 	<- image(image_file("../includes/wall.png"));
	image floor		<- image(image_file("../includes/floor.png"));
	image sky		<- image(image_file("../includes/sky.png"));
	image gun		<- image(image_file("../includes/gun.png"));
	
	reflex do_heavy_stuff {
		write rnd(0.0,1.0);
	}
}




experiment just_one type:batch repeat:12 parallel:12 until:cycle=10000{
	
}

experiment bug type:batch repeat:100 parallel:12 until:cycle=100{
	
}
```

with the necessary resources here: [resources.zip](https://github.com/gama-platform/gama/files/12724982/resources.zip)

We can see that running the "just_one" experiment, a first batch of 12 simulations are created and running using a somewhat constant amount of memory. But running the "bug" experiment, we can observe that the memory quickly saturates after a few batch of 12 simulations and it is not due to the simulations. 

**Expected behavior**
once a simulation of the batch is over it is deallocated

**Comment by AlexisDrogoul** [comment]
Isn't it what the `keep_simulations:` facet is about ? 

From the doc: `"In the case of a batch experiment, specifies whether or not the simulations should be kept in memory for further analysis or immediately discarded with only their fitness kept in memory"`

**Comment by lesquoyb** [comment]
My bad, I forgot about that facet
