### ISSUE TITLE
Serialization/Deserialization of any object

### ISSUE THREAD

**Issue by LucasGrjs** [gama-platform/gama.old#3896]
Is it possible to define (as it was the case before with XStream): 

1. an operator taking any object (agent, primitive data types,....) or collection of object (list, map, ...) to serialize it to byte[] or String
2. an operator taking a byte[] or a String and deserialize it to Object (so that we can cast it afterwards to the correct type in Java or Gaml)

in Java : 

```
byte[] serialize(Object objectToSerialize);
Object deserialize(byte[] serailizedObject);

byte[] serializedInt = serialize(8) ;
byte[] serializedAgent = serialize(movingAgent) ;
byte[] serializedCollectionOfAgent = serialize([movingAgent1, movingAgent2]) ;

int deserialized = (Integer) serialize(serializedInt);
Agent deserialized = (Agent) serialize(serializedAgent);
IList deserialized = (IList) serialize(serializedCollectionOfAgent);
```

Same goes for GAML

This would allow the serialization/deserialization of any object without having any prior knowledge on the object itself.

**Comment by AlexisDrogoul** [comment]
I've reworked a bit the operators. Now you have : 

1. For agents: `string s <- serialize(my_agent); ` and `create my_species from: s;` or `restore my_agent from: s`
2. For objects: `string s <- serialize(my_object); ` and `unknown obj <- deserialize(s);`

`serialize` can take two other arguments: 
1. the format: "json", "binary", or "xml". "binary" is the default.
2. whether it is compressed or not

Please test !

**Comment by LucasGrjs** [comment]
Working on Windows 11

**Comment by lesquoyb** [comment]
in my case I have a few issues:
* deserialize doesn't find the file on windows, here is the error:
```
1 occurence in t0 at cycle 0: Java error: I/O error
in Simulation 0
in init  {
	create yolo number: 10 ;
}

NoSuchFileException: plop.txt
java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236)
java.base/java.nio.file.Files.newByteChannel(Files.java:380)
java.base/java.nio.file.Files.newByteChannel(Files.java:432)
java.base/java.nio.file.Files.readAllBytes(Files.java:3288)
when applying the deserialize operator on plop.txt
in string c <- deserialize('plop.txt');
in reflex ser  {
	string s <- serialize(range(200));
	write s ;
	save s to: 'plop.txt' format: 'text' ;
	string c <- deserialize('plop.txt');
	write '
	
	
	' + c ;
}

in agent t0
```
* serializing a grid or a species produce unexpected result, for example:
```
model serialisation


grid abc width:100 height:100{
	int i <- rnd(2000000000);
}

experiment t {
	
	reflex ser {
		string s <- serialize(abc);
		write s;
	}
}
```
produces:  
<img width="309" alt="image" src="https://github.com/gama-platform/gama/assets/6374469/86d0c14e-5e6c-4be4-9b4e-ac36e2c80ea6">
which seems wrong

**Comment by AlexisDrogoul** [comment]
@lesquoyb can you test the latest version ? It should solve the second problem (maybe not the first one though).

**Comment by lesquoyb** [comment]
both solved!
