### ISSUE TITLE
Radius with polylines is not shown in 2d

### ISSUE THREAD

**Issue by LorisHenry** [gama-platform/gama.old#3899]
**Describe the bug**
when drawing lines in 2d, specifying the radius in the line operator should return a line with a width, as mentionned in the documentation. So a rectangle in 2d. However, it returns a line, ignoring the passed argument.

It returns correctly a cyclinder with the right radius in 3d displays.
```
**To Reproduce**
/**
* Name: issueline
* Based on the internal empty template. 
* Author: Loris
* Tags: 
*/


model issueline

global {
	float size1 <- 1.0;
	float size2 <- 3.0;
	
	init {
		create a;
	}
}

species a {
	aspect default {
		draw line([{33, 33}, {66, 33}], size1);
		draw line([{33, 66}, {66, 66}], size2);
	}
}

experiment main {
	output {
		display main type:2d{
			species a;
		}
	}
}
```

**Expected behavior**
2 cylinders with different radiuses.

**Comment by AlexisDrogoul** [comment]
I have made sure lines with a depth are correctly displayed as "fat lines" in java2D. Please test !
