### ISSUE TITLE
aspect:condition ? aspect1:aspect2 does not work

### ISSUE THREAD

**Issue by LorisHenry** [gama-platform/gama.old#3901]
Not exactly a bug because this behavior is known, but it is odd as the ternary operator usually works fine on other various facets.`

Error ouptut : "? is not the name of an aspect of a"

**To Reproduce**
```
/**
* Name: issueaspect
* Based on the internal empty template. 
* Author: Loris
* Tags: 
*/
model issueaspect

global {
	bool b <- true;
}

species a {
	aspect default {
		draw circle(10) color:#red;
	}
	aspect alternative {
		draw circle(10) color:#blue;
	}
}

experiment main {
	output {
		display main {
			species a aspect:b ? default:alternative;
		}
	}
}
```

**Comment by AlexisDrogoul** [comment]
Yep. And it will probably never work this way, as this facet expects a label, not an expression. A bit like `var:` for `parameter`. One of the possibilities we could offer (not sure yet if it is relevant) would be to enable a new usage of `draw`, taking another aspect as an argument. This would allow to reuse aspects in other aspects (already an interesting point), but also to write your layer like this : 
```
		display main {
			species a  {if b {draw default;} else { draw alternative;}}
		}
```

**Comment by lesquoyb** [comment]
@AlexisDrogoul any plans on implementing that for 1.9.3  or should we wait for next release ?

**Comment by AlexisDrogoul** [comment]
I have implemented the solution present in my previous comment, which works reasonably well (although none of the facets of draw are used). Please test !

**Comment by lesquoyb** [comment]
Working properly, I also added a model in the library to illustrate it
