### ISSUE TITLE
Palette type is not visible for the user

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3906]
**Is your request related to a problem? Please describe.**
In gaml, it is possible to create "palette" objects, that are basically lists of rgb, this is used in the rendering of mesh (and maybe some other places that I'm not aware of), but it is actually not documented anywhere that those palettes are different than simple lists.

Even worse, the `palette` type itself doesn't exist in gaml and is treated as a `list<rgb>` in the code.
So you end up with this:
```
list<rgb> pal <- palette([#green, #yellow, #orange, #red]);
write pal;
```
and this:
```
list<rgb> pal <- [#green, #yellow, #orange, #red];
write pal;
```
which for the user looks exactly the same and do not show any difference in how to manipulate or in the content of the object, though if used in a `mesh` statement in a display, they will yield a completely different result as it seems that internally gama is keeping track of the fact that one is a palette and not the other.

Example of the difference in the latest Hoan Kiem Air model:
with palette:
<img width="400" alt="image" src="https://github.com/gama-platform/gama/assets/6374469/b8ad2709-f6c0-40c1-bc79-1fc6beb82d30">
without palette:
<img width="388" alt="image" src="https://github.com/gama-platform/gama/assets/6374469/707464cf-8fa8-4b0e-b69c-0e97bb2b2358">

**Describe the improvement you'd like**
At least document in the color facet of `mesh` statement that using the `palette` operator on the list of `rgb` is mandatory for normal behaviour or if it's the only place where we need palette, why not doing the transformation in the code of the facet and completely get rid of the use of palette for the user (removing the operator etc.)
If the palette is important then maybe it's worth having it turned into a proper gaml type and force the facets requiring palettes to use that type instead of `list<rgb>`

**Comment by AlexisDrogoul** [comment]
I have added a more precise documentation to the `color:` facet of the `mesh` statement. I think it is the only interesting development we can have on this topic as the difference between scales, palettes, and gradients only matter here.
