### ISSUE TITLE
operator arc does not return geometry with right radius

### ISSUE THREAD

**Issue by LorisHenry** [gama-platform/gama.old#3907]
**Describe the bug**
arc() returns an arc geometry with a radius of half of the first operand instead of a radius of the first operand
**To Reproduce**
```
/**
* Name: issuearc
* Based on the internal empty template. 
* Author: Loris
* Tags: 
*/


model issuearc

global {
	
	init {
		create a {
			shape <- arc(20, 0, 90, true);
			location <- {50, 75};
		}
		create a {
			shape <- circle(20);
			location <- {50, 25};
		}
	}
}

species a {
	aspect default {
		draw shape;
	}
}

experiment main {
	output {
		display main {
			species a;
		}
	}
}

```
Here, the arc has a radius of 10 instead of 20.

**Comment by AlexisDrogoul** [comment]
Indeed. I've corrected the definition (and one of the tests, which was rendering false because of the simplifications made when drawing circles / arcs)
