### ISSUE TITLE
Text format is not recognized as matching with txt files in save statement

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3909]
**Describe the bug**
When using the `save` statement, it is recommended to use the `format` facet, according to documentation the "text" format is one of the supported and even recommended. But when saving a file with the extension `txt` which is standard for text files, an info message appears to say that it doesn't match the `text` format.
<img width="505" alt="image" src="https://github.com/gama-platform/gama/assets/6374469/2238934e-a66b-4379-8f88-32c2cb5ed65d">

**Comment by AlexisDrogoul** [comment]
I had to add the possibility to define synonyms (I thought it was there, but no) in `ISaveDelegate`. Everything should be ok now.
