### ISSUE TITLE
[GS] step command cannot be executed synchronously anymore

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3913]
**Describe the bug**
On the git version of gama, when running the step command on gama-server the `sync` parameter seems to be ignored.
If I ask to execute 100 steps synchronized and just after getting the `CommandExecutedSuccessfully` message I ask gama-server for the current cycle, I do not get `previous_cycle + 100` but a number between this and `previous_cycle`, so my guess is that the steps are still being executed, which shouldn't happen when the sync parameter is set to true.

**Expected behavior**
Success messages are sent after all steps are executed when the sync parameter is true, as it used to be.

**Comment by hqnghi88** [comment]
Hello Baptiste,
It works on my side, for sync and nb_step, for ex, i request 100000 step, and i eval the cycle later:
request {"type":"step","model":"/Users/hqn88/git/gama/msi.gama.models/models/Tutorials/Road Traffic/models/Model 05.gaml","experiment":"road_traffic","socket_id":0,"exp_id":"1252","console":false,"status":false,"dialog":false,"runtime":false,"auto-export":false,"nb_step":100000,"parameters":[{"name":"Number of people agents","value":111,"type":"int"},{"name":"Value of destruction when a people agent takes a road","value":0.2,"type":"float"}],"sync":true}
------------------------------
{ "type": "CommandExecutedSuccessfully","content": "","command": {"type":"step","model":"\/Users\/hqn88\/git\/gama\/msi.gama.models\/models\/Tutorials\/Road Traffic\/models\/Model 05.gaml","experiment":"road_traffic","socket_id":0,"exp_id":"1252","console":false,"status":false,"dialog":false,"runtime":false,"auto-export":false,"nb_step":100000,"parameters":[{"name":"Number of people agents","value":111,"type":"int"},{"name":"Value of destruction when a people agent takes a road","value":0.2,"type":"float"}],"sync":true}}
------------------------------
request {"type":"expression","model":"/Users/hqn88/git/gama/msi.gama.models/models/Tutorials/Road Traffic/models/Model 05.gaml","experiment":"road_traffic","socket_id":0,"exp_id":"1252","console":false,"status":false,"dialog":false,"runtime":false,"escaped":false,"sync":false,"expr":"cycle"}
------------------------------
{ "type": "CommandExecutedSuccessfully","content": "7263","command": {"type":"expression","model":"\/Users\/hqn88\/git\/gama\/msi.gama.models\/models\/Tutorials\/Road Traffic\/models\/Model 05.gaml","experiment":"road_traffic","socket_id":0,"exp_id":"1252","console":false,"status":false,"dialog":false,"runtime":false,"escaped":false,"sync":false,"expr":"cycle"}}
------------------------------
request {"type":"expression","model":"/Users/hqn88/git/gama/msi.gama.models/models/Tutorials/Road Traffic/models/Model 05.gaml","experiment":"road_traffic","socket_id":0,"exp_id":"1252","console":false,"status":false,"dialog":false,"runtime":false,"escaped":false,"sync":false,"expr":"cycle"}
------------------------------
{ "type": "CommandExecutedSuccessfully","content": "28831","command": {"type":"expression","model":"\/Users\/hqn88\/git\/gama\/msi.gama.models\/models\/Tutorials\/Road Traffic\/models\/Model 05.gaml","experiment":"road_traffic","socket_id":0,"exp_id":"1252","console":false,"status":false,"dialog":false,"runtime":false,"escaped":false,"sync":false,"expr":"cycle"}}
------------------------------
request {"type":"expression","model":"/Users/hqn88/git/gama/msi.gama.models/models/Tutorials/Road Traffic/models/Model 05.gaml","experiment":"road_traffic","socket_id":0,"exp_id":"1252","console":false,"status":false,"dialog":false,"runtime":false,"escaped":false,"sync":false,"expr":"cycle"}
------------------------------
{ "type": "CommandExecutedSuccessfully","content": "59714","command": {"type":"expression","model":"\/Users\/hqn88\/git\/gama\/msi.gama.models\/models\/Tutorials\/Road Traffic\/models\/Model 05.gaml","experiment":"road_traffic","socket_id":0,"exp_id":"1252","console":false,"status":false,"dialog":false,"runtime":false,"escaped":false,"sync":false,"expr":"cycle"}}
------------------------------
request {"type":"expression","model":"/Users/hqn88/git/gama/msi.gama.models/models/Tutorials/Road Traffic/models/Model 05.gaml","experiment":"road_traffic","socket_id":0,"exp_id":"1252","console":false,"status":false,"dialog":false,"runtime":false,"escaped":false,"sync":false,"expr":"cycle"}
------------------------------
{ "type": "CommandExecutedSuccessfully","content": "100000","command": {"type":"expression","model":"\/Users\/hqn88\/git\/gama\/msi.gama.models\/models\/Tutorials\/Road Traffic\/models\/Model 05.gaml","experiment":"road_traffic","socket_id":0,"exp_id":"1252","console":false,"status":false,"dialog":false,"runtime":false,"escaped":false,"sync":false,"expr":"cycle"}}
------------------------------

**Comment by hqnghi88** [comment]
Ah sorry, misunderstood, it is async mode. You are right.
