### ISSUE TITLE
Documentation generated from code is not properly updated in the wiki generated files

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3916]
**Describe the bug**
There has been some change in the java code of gama that is used to generate the documentation, but I don't see those reported on the website, even though the action `Documentation auto refresh` has been called.

**Expected behavior**
Changes are visible on the website, for example the operator `palette` [here](https://gama-platform.org/wiki/next/OperatorsNR#palette) should only have one syntax (instead of three currently)

**Comment by RoiArthurB** [comment]
This issue is actually related to the doc generation and not the website recompilation. You can see in the wiki that the  palette also has 3 examples https://github.com/gama-platform/gama/wiki/OperatorsNR#user-content-palette

Moving this issue in gama repository then

**Comment by AlexisDrogoul** [comment]
Any progress on this one ? What is the issue regarding the generation ?

**Comment by RoiArthurB** [comment]
None, waiting for @benoitgaudou to take a look at it. 

We will see this issue fixed when the text for _palette_ will be fully updated (it's not supposed to talk about `returns a list of n colors [...]` but be way shorter as here https://github.com/gama-platform/gama/blob/GAMA_1.9.3/msi.gama.core/src/msi/gaml/operators/Colors.java#L1213 )

**Comment by lesquoyb** [comment]
Now that I think about it, it may be the reason why we see operators that seem to not exist anymore, as described in #3937, in the documentation as well as partly supported by the IDE.
@benoitgaudou any progress on that issue ?
