### ISSUE TITLE
The operators to check a file's type seem to have disappeared

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3937]
**Describe the bug**
trying to adapt code from 1.8.1 to more recent versions I found out that `is_csv` doesn't work anymore. I got the message: `No operator found for applying 'is_csv' to type string (operators available for [type ])`
When looking for `is_csv` in java files in current code base I have 0 matches. I have similar problems with other file types like `is_shape`. Those operators are still visible in the documentation.
Is the operator still available ? Else what has it been replaced with (and why) or what should we do instead ?

**Desktop (please complete the following information):**
 - GAMA version: 1.9.2/git

**Comment by AlexisDrogoul** [comment]
I've pushed a solution, which now needs to be tested...

**Comment by lesquoyb** [comment]
The operators are available now, but the documentation in the IDE is missing:
![image](https://github.com/gama-platform/gama/assets/6374469/f38a6308-7e45-4f7d-9078-8c2337a9c5ca)
