### ISSUE TITLE
[Windows] Release without JDK is not working anymore

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3939]
**Describe the bug**
I have multiple gama versions installed on my computer, the ones packaged with the jdk work well, but the other ones crash a few seconds after the splash screen.

What I tried so far:

1. I tried to change my `JAVA_HOME` environment  variable to the path of a jdk packaged with one GAMA that is working, but I encountered the same problem.
2. If I add to the `GAMA.ini` file the path to the jdk it works normally.
3. If I run gama headless from the file `gama-headless.bat` it also works without any problem.
For information in that case gama is loaded with this command:
```batch
 call "%JAVA_HOME%\bin\java.exe" -cp !result! -Xms512m -Xmx%memory% !ini_arguments! -Djava.awt.headless=true org.eclipse.core.launcher.Main -configuration ./configuration -application msi.gama.headless.product -data "%workDir%" !param!
```

So my guess is that the way maybe gama is not using `JAVA_HOME` when it runs without jdk ?

Here is a typical log I would get
[1701867147243.log](https://github.com/gama-platform/gama/files/13583211/1701867147243.log)

**To Reproduce**
1. Download gama without jdk for windows, either zip or installer give the same results
2. try to run it

**Desktop (please complete the following information):**
latest alpha release (but I'm quite sure this problem has been running for longer than this, I just never use those versions without jdk)

**Comment by RoiArthurB** [comment]
I'm really confused between your logs and what seems to be the error in the command line. They do not seem to really match...

What seems sure to me is that you shouldn't use the environment variable `%JAVA_HOME%` if you're using GAMA w/ JDK version.

---

> 1. I tried to change my JAVA_HOME environment variable to the path of a jdk packaged with one GAMA that is working, but I encountered the same problem.

You shouldn't edit this path, it's something which is set while you're installing your JDK (17) and is then called automatically. Can you tell me if, with your current edited path, you do have Eclipse working ?

> 2. If I add to the GAMA.ini file the path to the jdk it works normally.

It should be appliable only for the GUI version. Do you have issue with both GUI and headless mode?
What is the default `Gama.ini` in JDK version that you downloaded ?

> So my guess is that the way maybe gama is not using JAVA_HOME when it runs without jdk ?

Can you open a terminal and tell me what this command returns : `java -version`

GAMA is using those variable to start by default. Those variables are, actually, used as relative paths within your system when you launch the `java` command.

**Comment by lesquoyb** [comment]
Ok I found out the issue: some old java version was used by default by windows even though the JAVA_HOME was referring to a newer one.
Closing it because I think it's not something we are responsible for
