### ISSUE TITLE
Graphs are not drawn (and actually should not be)

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama.old#3941]
**Describe the bug**
Many different types of objects can be drawn in GAMA, but nothing is implemented to draw graphs. However, the use of `draw` with objects of type `graph` exists in some places, for instance `Topology.experiment` in `Spatial Tests`. 

**To Reproduce**
Open `Topology.experiment`. Remove all the `grid` and `species` layers in the displays. 

```gaml
experiment visu type: gui {
	output {
		display map4 {
			//grid cell4 border:#grey;
			//species dummy;
			graphics the_graph {
				draw c_graph4 color:#black;
			}
		}	
		display map6 {
			//grid cell6 border:#grey;
			graphics the_graph {
				draw c_graph6 color:#black;
			}
		}
		display map8 {
			//grid cell8 border:#grey;
			graphics the_graph {
				draw c_graph8 color:#black;
			}
		}
	}	
}
```

Open the experiment named `visu`. Nothing appears on screen. 

**Expected behavior**
That either the graphs is drawn if it is spatial or that an error is raised to tell that graphs can't be drawn. 

**Desktop (please complete the following information):**
 - OS: macOS Sonoma
 - PC Model: MBP Pro 16" M1
 - GAMA version: all

**Comment by chapuisk** [comment]
I would have been in favor of drawing the graph rather than raising an exception, but if it is the expected behavior for this fix, it does what it meant to do !
