### ISSUE TITLE
[Code Editor] The description of facet, properties and actions in the documentation when hovering is not available

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3953]
**Describe the bug**
It may be something related to the fix of the small issue described in this [comment ](https://github.com/gama-platform/gama/issues/3937#issuecomment-1849537433) but the descriptions of all the facets, properties and actions that we could read in the documentation that appeared when hovering a statement/species is now replaced with the name of an instance of a java object:
![image](https://github.com/gama-platform/gama/assets/6374469/03d9e72a-0e97-4532-af4f-df433860fc9f)
![image](https://github.com/gama-platform/gama/assets/6374469/30911efe-2dd4-462a-ad3f-432e75346c35)

**To Reproduce**
1. open any model in the code editor
2. hover over a statement or a species
3. Scroll down to the description of facets, properties or actions

**Comment by AlexisDrogoul** [comment]
This should be fixed now in the latest commits.
