### ISSUE TITLE
Some models in library do not compile anymore

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3954]
**Describe the bug**
Following the fix for #3941, models in library that used to draw graphs do not compile anymore

**To Reproduce**
1. Open `Topology.experiment` or `Elements of Syntax.gaml`
2. see the compilation error

**Expected behavior**
change the graphs to spatial ones so it can compile or do not draw them at all

**Comment by AlexisDrogoul** [comment]
The first model has been modified in the corresponding commit, and the second never drew graphs AFAIK.
