### ISSUE TITLE
[GS] server do not start

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3955]
**Describe the bug**
In the current version, gama-server do not start anymore. When running it, the initialisation goes normally:
```
> FLAG  : enable_debug                                  set to________ true
> FLAG  : enable_logging                                set to________ true
> FLAG  : use_global_preference_store                   set to________ true
> GAMA  : version 1.9.3                                 loading on____ win32 10.0, x86_64, JDK 17.0.8.1
> JAI   : ImageIO extensions                            loaded for____ BTF|TF8|TIF|TIFF|arx|asc|bmp|btf|gif|jp2|jpeg|jpg|pbm|pgm|png|ppm|tf8|tif|tiff|wbmp
> GAMA  : Plugin msi.gama.core                          loaded in_____ 2622ms
> GAMA  : Plugin irit.gaml.extensions.database          loaded in_____ 42ms
> GAMA  : Plugin miat.gaml.extensions.pedestrian        loaded in_____ 44ms
> GAMA  : Plugin msi.gama.headless                      loaded in_____ 19ms
> GAML  : Initializing parser                           done in_______ 303ms
> GAMA  : Plugin msi.gama.lang.gaml                     loaded in_____ 313ms
> GAMA  : Plugin msi.gaml.architecture.simplebdi        loaded in_____ 79ms
> GAMA  : Plugin msi.gaml.extensions.fipa               loaded in_____ 14ms
> GAMA  : Plugin simtools.gaml.extensions.physics       loaded in_____ 15ms
> GAMA  : Plugin simtools.gaml.extensions.traffic       loaded in_____ 49ms
> GAMA  : Plugin ummisco.gama.network                   loaded in_____ 6ms
> GAMA  : Plugin ummisco.gama.serialize                 loaded in_____ 14ms
> GAMA  : Snapshot services                             active________ (gui mode)
> GAMA  : Plugin ummisco.gaml.extensions.image          loaded in_____ 130ms
> GAMA  : Plugin ummisco.gaml.extensions.maths          loaded in_____ 172ms
> GAMA  : Plugin ummisco.gaml.extensions.stats          loaded in_____ 46ms
> GAMA  : Loading extensions to 'create'                done in_______ 13ms
> GAMA  : Loading extensions to 'save'                  done in_______ 170ms
> GAMA  : Loading extensions to 'draw'                  done in_______ 10ms
> GAMA  : Loading extensions to 'event'                 done in_______ 2ms
> GAMA  : Gathering built-in models                     done in_______ 3ms
> GAMA  : Loading constants                             done in_______ 532ms
> GAML  : Plugins with language additions               loaded in_____ 6052ms
GAMA configuring and loading...
> GAML  : Artifacts                                     built in______ 84ms
```
but then nothing happen while we should see a line explaining that the server is running on a certain port. Of course no client is able to connect to it.
This only happens in pure server mode and the server seems to run normally in gama gui

**To Reproduce**
1. Run gama-server either from eclipse or with the gama-headless script
2. see that initialisation never reaches the `Server started ` point

**Expected behavior**
It works as it used to do

**Comment by hqnghi88** [comment]
The "Server started" message is not written anymore in onStart() of headless server (it is in GUI server). But i can connect to server by JS , can you report more detail on your failing case that no client could connect to server??
<img width="1697" alt="Screenshot 2024-01-12 at 22 52 04" src="https://github.com/gama-platform/gama/assets/6105384/7cf200e2-a3ff-4bf7-9389-5a10ea212e77">

**Comment by lesquoyb** [comment]
well that's weird because that text is showing when you run the gui version.
Anyways I just run my usual test python script that you can find [here](https://github.com/gama-platform/gama.clients/blob/main/python/examples/sequential_example.py) and it gets stuck at connection with server, but it works as expected with gama gui

**Comment by RoiArthurB** [comment]
Same as Baptiste, we tried to connect it and, what I noticed, the port and the web socket seemed to somewhat start, but it's impossible to actually connect to the server (Timeout error) :/

**Comment by hqnghi88** [comment]
<img width="1724" alt="Screenshot 2024-01-15 at 23 26 12" src="https://github.com/gama-platform/gama/assets/6105384/ae090661-ad8a-4630-a6d4-9ae30a0414b1">
No problem on my side even with your py code.

**Comment by RoiArthurB** [comment]
@hqnghi88 via GAMA headless from Eclipse or build alpha ?

**Comment by hqnghi88** [comment]
Headless product in eclipse

**Comment by hqnghi88** [comment]
<img width="1156" alt="Screenshot 2024-01-16 at 22 28 47" src="https://github.com/gama-platform/gama/assets/6105384/8db3d5c1-3860-459d-af7c-97a21ee39cfa">
even with binary release

**Comment by lesquoyb** [comment]
**update on my side:** I tried with another computer and couldn't reproduce the issue. The `server started` text is not displayed but looking at the code it's fairly normal as it only is printed in gui server now, but apart from that I'm able to interact normally with it. That other computer is a windows 11 one, just like the one I used in the first place

**Comment by RoiArthurB** [comment]
Works on Linux too, I think it would be better to have the server message also display in the headless' logs :thinking:
