### ISSUE TITLE
Toy Model - Vote : Nil value detected

### ISSUE THREAD

**Issue by zarnejo-exers** [gama-platform/gama.old#3965]
**Describe the bug**
Encounters java error upon reloading an experiment.

**To Reproduce**
1. Go to 'Library models/Toy Models/Vote/Vote.gaml'
2. Execute experiment 'vote' -> Click 'Candidate'
3. On the field 'Distribution type of candidates", choose "Random"
4. Click "Reload" 
5. See error

**Expected behavior**
Just resets the parameters and reloads the simulation smoothly again. 

**Screenshots**
<img width="1433" alt="Screenshot 2024-02-19 at 21 27 15" src="https://github.com/gama-platform/gama/assets/3262396/343bd1b2-aadd-4ab2-9a7e-5fc17ebdb06e">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - PC Model: [if applicable, can be useful for displays, OpenGL problems)]
 - GAMA version: GAMA Platform - V1.9.3
 - Java version: java 17.0.2 2022-01-18 LTS
 - Graphics cards / Display system: [can be useful for displays, OpenGL problems]

**Additional context**

**Comment by AlexisDrogoul** [comment]
Impossible to reproduce the bug. Would it be possible to share the error ?

**Comment by benoitgaudou** [comment]
Following instructions, I was able to reproduce it on the 1.9.3 release.
Error I get is:
```
2 occurrences in 2 agents at cycle 0: Java error: nil value detected
in Simulation 0
in data 'Space area covered' color: #blue value: union(candidate collect buffer(each.shape,float(threshold_attraction_candidates))).area / 40000 ;
NullPointerException: Cannot invoke "msi.gama.metamodel.shape.IShape.getArea()" because "<parameter2>[0]" is null
gaml.additions.core.GamlAdditions.lambda$196(GamlAdditions.java:263)
msi.gaml.expressions.operators.UnaryOperator._value(UnaryOperator.java:101)
msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:87)
msi.gaml.expressions.operators.BinaryOperator._value(BinaryOperator.java:148)
msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:87)
msi.gama.outputs.layers.charts.ChartDataSourceUnique.inferDatasetProperties(ChartDataSourceUnique.java:169)
msi.gama.outputs.layers.charts.ChartDataSourceUnique.createInitialSeries(ChartDataSourceUnique.java:186)
when applying the area operator on null
in data 'Space area covered' color: #blue value: union(candidate collect buffer(each.shape,float(threshold_attraction_candidates))).area / 40000 ;
in agents Simulation 0, vote0
```

**Comment by AlexisDrogoul** [comment]
Still not reproducible here. Can you share with me the screenshots of your preferences (Execution and Displays) ?

**Comment by zarnejo-exers** [comment]
Please see the requested screenshots: 

<img width="1357" alt="Screenshot 2024-02-20 at 08 47 57" src="https://github.com/gama-platform/gama/assets/3262396/67bd0769-d8ca-4788-963f-63edc0556de2">

<img width="1357" alt="Screenshot 2024-02-20 at 08 47 44" src="https://github.com/gama-platform/gama/assets/3262396/49468139-12cd-4837-9f3f-79d4bad51d65">
