### ISSUE TITLE
In Co Modeling some agents are not displayed

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama.old#3967]
**Describe the bug**
Open Toy Models/CoModels/Flood Evacuation Models.gaml
Run the model.

Most of the agent are not displayed anymore in 1.9.3 whereas it is in 1.9.2 but it seems that the agent are simply not there no not displayed

<img width="1694" alt="Screenshot 2024-02-19 at 22 13 26" src="https://github.com/gama-platform/gama/assets/3928502/76690a66-5c4b-454f-98f4-3ca29c268e37">

One quick fist could be to synchronize the display in Gaml but it might be due to a deeper issue

**Comment by hqnghi88** [comment]
fix by force synchronized on output

**Comment by hqnghi88** [comment]
Reopen to track down the deeper cause

**Comment by hqnghi88** [comment]
This issue is fixed by b02ad7e .
