### ISSUE TITLE
Inspecting agents during simulation execution breaks the execution

### ISSUE THREAD

**Issue by zarnejo-exers** [gama-platform/gama.old#3968]
**Describe the bug**
Inspecting an agent while the execution is running breaks the execution and throws varied error messages on different models.

**To Reproduce**
1. Go to any of [knn.gaml, Traffic and pollution.gaml, Sugarscape.gaml, Soccer.gaml ....]
2. Run the experiment
3. Right-click anywhere -> World -> [any agent] -> Inspect

We believe many models behave the same...

**Expected behavior**
The simulation continues even while inspecting agents

**Screenshots**
<img width="1014" alt="Screenshot 2024-02-19 at 22 18 20" src="https://github.com/gama-platform/gama/assets/3262396/ef787265-8c0f-4e80-8f3f-30582c83220a">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - PC Model: 
 - GAMA version: V1.9.3
 - Java version: java 17.0.2 2022-01-18 LTS
 - Graphics cards / Display system: [can be useful for displays, OpenGL problems]

**Additional context**

**Comment by AlexisDrogoul** [comment]
I have tested in 1.9.2, where it works, and I can confirm that this bug has been introduced since then. Working on it !
