### ISSUE TITLE
Small change in z-fighting between 1.9.2 and 1.9.3

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama.old#3969]
**Describe the bug**
Open Toy Models/Art/Gama1.9/Gama1.9.gaml.

A z-fighting problem reappeared and might be due somehow to this issue https://github.com/gama-platform/gama/issues/3880. Also the rendering of 1.9.1 is also different and better at least on this model (no aliasing on the 1.9 number at the end)

<img width="1698" alt="Screenshot 2024-02-19 at 22 35 48" src="https://github.com/gama-platform/gama/assets/3928502/4df7f8fd-fd46-4fe0-b7ed-5c92e4eb0202">

**Comment by AlexisDrogoul** [comment]
I've added (back) a factor for the increment (z-fighting), which should be enough for this !

**Comment by agrignard** [comment]
For the GAMA 1.9 model it's ok now. The model mention by @lesquoyb in https://github.com/gama-platform/gama/issues/3880 was Shibuya where side effects can be slightly seen with a factor set to 1 but almost not with the current value of the factor.
