### ISSUE TITLE
Mouse Drag not working in Java2D

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama.old#3970]
**Describe the bug**
Open ```Visualization and User Interaction/User Interaction/Mouse Drag.gaml```
Run it

Two issue
1. Ones need to double click before to be able to do the first drag (maybe not a big deal and impossible to fix (can we force the display to be focused)
2. The drag is not working in java2D (which I somehow can understand but then why having a 2D display? ). If it cannot work in java2D let's remove the java2D display and explain it in the model?

**Comment by AlexisDrogoul** [comment]
Actually it works, but the surface needs to be locked first -- and it cant be done through a facet (it's done through the `camera` statement in OpenGL).

**Comment by lesquoyb** [comment]
closing because superseded by gama-platform/new.gama#9
