### ISSUE TITLE
GAMA crash while trying to execute the Library Model "Text Display"

### ISSUE THREAD

**Issue by lmartinez2001** [gama-platform/gama.old#3975]
**Describe the bug**
Gama crashes when trying to execute the Text Display model located in the Library Models directory.

**To Reproduce**
1. Go to Library Model > Visualization and User Interaction > Visualization > Text Display.gaml
2. Run the "Strings" experiment
3. Crash occurs

**Expected behavior**
The expemiment executing properly

**Desktop (please complete the following information):**
 - OS: Windows 11
 - PC Model: Dell 5515
 - GAMA version: 1.9.3
 - Java version: 1.17
 - Graphics cards / Display system: [can be useful for displays, OpenGL problems]

**Comment by lesquoyb** [comment]
I tried on my computer and it seems to be another case of AMD drivers not compatible with opengl. I fixed it on my computer with the usual workaround and waiting for some updates from @lmartinez2001 to confirm to close it

**Comment by lesquoyb** [comment]
Closing because superseded by gama-platform/new.gama#12
