### ISSUE TITLE
SIR comodel error nil agent

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama.old#3978]
**Describe the bug**
When launching SIR Comodel the simulation repeated an error in the SIR ABM sub model

**To Reproduce**
1. Go to Toy Models / Comodels / SIR Switch / SIR Comodel.gaml
2. Launch Simple_exp
3. See error

**Comment by hqnghi88** [comment]
As a quick observe, it is the same symptome with the last reported issue in Flood Evacuation Comodel (and others comodels). We are investigating this.

**Comment by hqnghi88** [comment]
Fixed as in #3967
