### ISSUE TITLE
Overlay disappearing on right-click in "Legend - Overlay" Library Model

### ISSUE THREAD

**Issue by lmartinez2001** [gama-platform/gama.old#3980]
**Describe the bug**
In the "Legend - Overlay" Library Modelm the overlay disappears from the display on right-click when the experiment is running.  
There seem to be no way to retrieve it. What's more, the right-click trigger does not open the agents/simulation details menu

**To Reproduce**
1. Go to Library Models > Visualization and User Interaction > Visualization > Legend - Overlay.gaml
2. Start the "overlay" experiment
3. Run the experiment
4. Right-click anywhere within the display
5. See the legend overlay disappearing

**Expected behavior**
On right-click, the agents/simulation dropdown menu should be displayed and there should be no impact on the legend overlay.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - PC Model: Dell 5515
 - GAMA version: 1.9.3
 - Java version: 1.17
 - Graphics cards / Display system: AMD chipset

**Comment by lesquoyb** [comment]
closing because superseded by gama-platform/new.gama#10
