### ISSUE TITLE
Operator with data in type of Field

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama.old#3984]
**Describe the bug**
I have 2 variable (A,B) in type of Field. I want to calculate 2 variable with an addition or subtraction (may be * and / also).
C <- A + B
The result showed that C provided the right calculated result, but A had the same result with C.
The results expected: The variable A keeps it original value.

Please try with this code:

/**
* Name: NewModel1
* Based on the internal skeleton template. 
* Author: Lenovo
* Tags: 
*/

model NewModel1

global {
	/** Insert the global definitions, variables and actions here */
	field field_from_matrixA  <- field(matrix([[1,1,1],[2,2,2],[3,3,3]]));
	field field_from_matrixB  <-  field(matrix([[1,1,1],[2,2,2],[3,3,3]]));
	field field_from_matrixC  ;
	init{
		write "Field A:";
		write field_from_matrixA;
		write "Field B:";
		write field_from_matrixB;
		field_from_matrixC<-field_from_matrixA+field_from_matrixB;
		write "Field A after C <- A+B:";
		write field_from_matrixA;
		write "Field C:";
		write field_from_matrixC;
		write "Field A after C <- A-B:";
		field_from_matrixC<-field_from_matrixA-field_from_matrixB;
		write field_from_matrixA;
	} 
	
}

experiment NewModel1 type: gui {
	/** Insert here the definition of the input and output of the model */
	output {
	}
}

**Comment by agrignard** [comment]
According to the documentation one solution was to copy the filed before to make the substraction however even with the copy option the orignal filed is still modified

**Comment by AlexisDrogoul** [comment]
Should be good now.
